In [263]:
import pandas as pd
import numpy as np
import random

# Reproducibility
random.seed(42)
np.random.seed(42)

In [44]:
# ==========================================
# KEYSTRA ENERGY GROUP
# Enterprise Workforce Safety Intelligence
# ==========================================

# Workforce size
num_employees = 4000

# Study period
years = [2022, 2023, 2024, 2025, 2026]

print("========== KEYSTRA PROJECT ==========")
print("Employees:", num_employees)
print("Study Period:", years[0], "-", years[-1])

========== KEYSTRA PROJECT ==========
Employees: 4000
Study Period: 2022 - 2026

In [45]:
# ==========================================
# BUSINESS UNIT LOOKUP
# ==========================================

dim_business_unit = pd.DataFrame({
    "BusinessUnit_ID": [
        "BU001",
        "BU002",
        "BU003",
        "BU004",
        "BU005"
    ],
    "Business_Unit": [
        "Upstream",
        "Midstream",
        "Downstream",
        "LNG",
        "Renewables"
    ]
})

dim_business_unit

  BusinessUnit_ID Business_Unit
0           BU001      Upstream
1           BU002     Midstream
2           BU003    Downstream
3           BU004           LNG
4           BU005    Renewables

In [46]:
# ==========================================
# DEPARTMENT LOOKUP
# ==========================================

dim_department = pd.DataFrame({
    "Department_ID": [
        "DEP001",
        "DEP002",
        "DEP003",
        "DEP004",
        "DEP005",
        "DEP006",
        "DEP007"
    ],
    "Department": [
        "Operations",
        "Maintenance",
        "Engineering",
        "HSE",
        "Logistics",
        "Finance & Administration",
        "Human Resources"
    ]
})

dim_department

  Department_ID                Department
0        DEP001                Operations
1        DEP002               Maintenance
2        DEP003               Engineering
3        DEP004                       HSE
4        DEP005                 Logistics
5        DEP006  Finance & Administration
6        DEP007           Human Resources

In [47]:
# ==========================================
# ASSET LOOKUP
# ==========================================

dim_asset = pd.DataFrame({

    "Asset_ID": [
        "AST001","AST002","AST003",
        "AST004","AST005","AST006","AST007",
        "AST008","AST009",
        "AST010",
        "AST011","AST012","AST013"
    ],

    "BusinessUnit_ID": [
        "BU001","BU001","BU001",
        "BU002","BU002","BU002","BU002",
        "BU003","BU003",
        "BU004",
        "BU005","BU005","BU005"
    ],

    "Asset_Name": [

        "Offshore Platform A",
        "Offshore Platform B",
        "Offshore Platform C",

        "Pipeline Network Alpha",
        "Pipeline Network Bravo",
        "Gas Compression Station",
        "Gas Processing Plant",

        "Refinery Complex",
        "Fuel Distribution Terminal",

        "LNG Export Terminal",

        "Solar Farm North",
        "Solar Farm South",
        "Wind Farm"

    ]
})

dim_asset

   Asset_ID BusinessUnit_ID                  Asset_Name
0    AST001           BU001         Offshore Platform A
1    AST002           BU001         Offshore Platform B
2    AST003           BU001         Offshore Platform C
3    AST004           BU002      Pipeline Network Alpha
4    AST005           BU002      Pipeline Network Bravo
5    AST006           BU002     Gas Compression Station
6    AST007           BU002        Gas Processing Plant
7    AST008           BU003            Refinery Complex
8    AST009           BU003  Fuel Distribution Terminal
9    AST010           BU004         LNG Export Terminal
10   AST011           BU005            Solar Farm North
11   AST012           BU005            Solar Farm South
12   AST013           BU005                   Wind Farm

In [48]:
# ============================================================

# DIM_JOB_ROLE

# ============================================================

job_role_records = []

for department_id, roles in job_role_map.items():

    for role in roles:

        job_role_records.append({

            "Job_Role_ID": f"ROLE{len(job_role_records) + 1:03d}",

            "Department_ID": department_id,

            "Job_Role": role

        })

dim_job_role = pd.DataFrame(job_role_records)

print("========== DIM_JOB_ROLE CHECK ==========")

print("Rows:", len(dim_job_role))

print("Columns:", len(dim_job_role.columns))

print()

print(dim_job_role)

========== DIM_JOB_ROLE CHECK ==========
Rows: 35
Columns: 3

   Job_Role_ID Department_ID                        Job_Role
0      ROLE001        DEP001             Production Operator
1      ROLE002        DEP001           Control Room Operator
2      ROLE003        DEP001                Process Operator
3      ROLE004        DEP001                  Field Operator
4      ROLE005        DEP001                  Plant Operator
5      ROLE006        DEP002             Mechanical Engineer
6      ROLE007        DEP002             Electrical Engineer
7      ROLE008        DEP002        Instrumentation Engineer
8      ROLE009        DEP002                Process Engineer
9      ROLE010        DEP002                Project Engineer
10     ROLE011        DEP003           Mechanical Technician
11     ROLE012        DEP003           Electrical Technician
12     ROLE013        DEP003      Instrumentation Technician
13     ROLE014        DEP003             Maintenance Planner
14     ROLE015        DEP003            Reliability Engineer
15     ROLE016        DEP004                     HSE Officer
16     ROLE017        DEP004                     HSE Advisor
17     ROLE018        DEP004               Safety Supervisor
18     ROLE019        DEP004           Environmental Officer
19     ROLE020        DEP004  Emergency Response Coordinator
20     ROLE021        DEP005               Warehouse Officer
21     ROLE022        DEP005            Supply Chain Officer
22     ROLE023        DEP005           Materials Coordinator
23     ROLE024        DEP005           Transport Coordinator
24     ROLE025        DEP005               Logistics Officer
25     ROLE026        DEP006               Financial Analyst
26     ROLE027        DEP006                      Accountant
27     ROLE028        DEP006                 Cost Controller
28     ROLE029        DEP006                 Finance Officer
29     ROLE030        DEP006             Procurement Analyst
30     ROLE031        DEP007                      HR Officer
31     ROLE032        DEP007             HR Business Partner
32     ROLE033        DEP007      Talent Acquisition Officer
33     ROLE034        DEP007            Training Coordinator
34     ROLE035        DEP007  Learning & Development Officer

In [49]:
print("Unique Job Roles:",
      dim_job_role["Job_Role"].nunique())

print("Missing Values:",
      dim_job_role.isna().sum().sum())

print("Duplicate Job Roles:",
      dim_job_role["Job_Role"].duplicated().sum())

Unique Job Roles: 35
Missing Values: 0
Duplicate Job Roles: 0

In [50]:
# ============================================================
# DIM_INCIDENT_TYPE
# ============================================================

dim_incident_type = pd.DataFrame({

    "Incident_Type_ID": [
        "IT001",
        "IT002",
        "IT003",
        "IT004",
        "IT005",
        "IT006",
        "IT007",
        "IT008",
        "IT009",
        "IT010"
    ],

    "Incident_Type": [
        "Near Miss",
        "First Aid Case",
        "Medical Treatment Case",
        "Restricted Work Case",
        "Lost Time Injury",
        "Fatality",
        "Property Damage",
        "Environmental Incident",
        "Fire / Explosion",
        "Process Safety Event"
    ],

    "Incident_Category": [
        "Near Miss",
        "Injury / Illness",
        "Injury / Illness",
        "Injury / Illness",
        "Injury / Illness",
        "Fatality",
        "Property / Asset",
        "Environmental",
        "Process / Fire",
        "Process Safety"
    ]
})

print("========== DIM_INCIDENT_TYPE CHECK ==========")
print("Rows:", len(dim_incident_type))
print("Columns:", len(dim_incident_type.columns))
print()
print(dim_incident_type)

========== DIM_INCIDENT_TYPE CHECK ==========
Rows: 10
Columns: 3

  Incident_Type_ID           Incident_Type Incident_Category
0            IT001               Near Miss         Near Miss
1            IT002          First Aid Case  Injury / Illness
2            IT003  Medical Treatment Case  Injury / Illness
3            IT004    Restricted Work Case  Injury / Illness
4            IT005        Lost Time Injury  Injury / Illness
5            IT006                Fatality          Fatality
6            IT007         Property Damage  Property / Asset
7            IT008  Environmental Incident     Environmental
8            IT009        Fire / Explosion    Process / Fire
9            IT010    Process Safety Event    Process Safety

In [51]:
# ============================================================
# DIM_HAZARD
# ============================================================

dim_hazard = pd.DataFrame({

    "Hazard_ID": [
        "HZ001",
        "HZ002",
        "HZ003",
        "HZ004",
        "HZ005",
        "HZ006",
        "HZ007",
        "HZ008",
        "HZ009",
        "HZ010",
        "HZ011",
        "HZ012"
    ],

    "Hazard_Name": [
        "Slips, Trips & Falls",
        "Working at Height",
        "Confined Space",
        "Electrical Energy",
        "Pressure / Stored Energy",
        "Fire / Explosion",
        "Hazardous Chemicals",
        "Hydrocarbon Release",
        "Lifting & Material Handling",
        "Vehicle / Mobile Equipment",
        "Dropped Objects",
        "Ergonomic / Manual Handling"
    ],

    "Hazard_Category": [
        "Physical",
        "Physical",
        "Physical",
        "Energy",
        "Energy",
        "Process Safety",
        "Chemical",
        "Process Safety",
        "Physical",
        "Transportation",
        "Physical",
        "Ergonomic"
    ]
})

print("========== DIM_HAZARD CHECK ==========")
print("Rows:", len(dim_hazard))
print("Columns:", len(dim_hazard.columns))
print()
print(dim_hazard)

========== DIM_HAZARD CHECK ==========
Rows: 12
Columns: 3

   Hazard_ID                  Hazard_Name Hazard_Category
0      HZ001         Slips, Trips & Falls        Physical
1      HZ002            Working at Height        Physical
2      HZ003               Confined Space        Physical
3      HZ004            Electrical Energy          Energy
4      HZ005     Pressure / Stored Energy          Energy
5      HZ006             Fire / Explosion  Process Safety
6      HZ007          Hazardous Chemicals        Chemical
7      HZ008          Hydrocarbon Release  Process Safety
8      HZ009  Lifting & Material Handling        Physical
9      HZ010   Vehicle / Mobile Equipment  Transportation
10     HZ011              Dropped Objects        Physical
11     HZ012  Ergonomic / Manual Handling       Ergonomic

In [52]:
# ==========================================
# SHIFT LOOKUP
# ==========================================

dim_shift = pd.DataFrame({

    "Shift_ID":[
        "SH001",
        "SH002",
        "SH003"
    ],

    "Shift":[
        "Day",
        "Night",
        "Rotational"
    ]

})

dim_shift

  Shift_ID       Shift
0    SH001         Day
1    SH002       Night
2    SH003  Rotational

In [53]:
# ============================================================
# DIM_CONTRACTOR
# ============================================================

dim_contractor = pd.DataFrame({

    "Contractor_ID": [
        "CON001",
        "CON002",
        "CON003",
        "CON004",
        "CON005",
        "CON006",
        "CON007",
        "CON008"
    ],

    "Contractor_Name": [
        "Keystra Engineering Services",
        "Keystra Industrial Maintenance",
        "Keystra Logistics Services",
        "Keystra Marine Services",
        "Keystra Construction Services",
        "Keystra Environmental Services",
        "Keystra Security Services",
        "Keystra Technical Services"
    ],

    "Contractor_Category": [
        "Engineering",
        "Maintenance",
        "Logistics",
        "Marine",
        "Construction",
        "Environmental",
        "Security",
        "Technical Services"
    ],

    "Contractor_Type": [
        "Technical Contractor",
        "Technical Contractor",
        "Support Contractor",
        "Marine Contractor",
        "Construction Contractor",
        "Environmental Contractor",
        "Security Contractor",
        "Technical Contractor"
    ]
})

print("========== DIM_CONTRACTOR CHECK ==========")
print("Rows:", len(dim_contractor))
print("Columns:", len(dim_contractor.columns))
print()
print(dim_contractor)

========== DIM_CONTRACTOR CHECK ==========
Rows: 8
Columns: 4

  Contractor_ID                 Contractor_Name Contractor_Category  \
0        CON001    Keystra Engineering Services         Engineering
1        CON002  Keystra Industrial Maintenance         Maintenance
2        CON003      Keystra Logistics Services           Logistics
3        CON004         Keystra Marine Services              Marine
4        CON005   Keystra Construction Services        Construction
5        CON006  Keystra Environmental Services       Environmental
6        CON007       Keystra Security Services            Security
7        CON008      Keystra Technical Services  Technical Services

            Contractor_Type
0      Technical Contractor
1      Technical Contractor
2        Support Contractor
3         Marine Contractor
4   Construction Contractor
5  Environmental Contractor
6       Security Contractor
7      Technical Contractor

In [54]:
print("Unique Contractors:",
      dim_contractor["Contractor_ID"].nunique())

print("Missing Values:",
      dim_contractor.isna().sum().sum())

print("Duplicate Contractor IDs:",
      dim_contractor["Contractor_ID"].duplicated().sum())

Unique Contractors: 8
Missing Values: 0
Duplicate Contractor IDs: 0

In [55]:
num_employees = 4000

employee_ids = [
    f"EMP{str(i).zfill(5)}"
    for i in range(1, num_employees + 1)
]

In [56]:
business_units = (
    ["BU001"] * 1500 +
    ["BU002"] * 700 +
    ["BU003"] * 1000 +
    ["BU004"] * 400 +
    ["BU005"] * 400
)

In [57]:
departments = (
    ["DEP001"] * 1700 +
    ["DEP002"] * 700 +
    ["DEP003"] * 550 +
    ["DEP004"] * 350 +
    ["DEP005"] * 300 +
    ["DEP006"] * 200 +
    ["DEP007"] * 200
)

In [58]:
import random

random.seed(42)

random.shuffle(business_units)
random.shuffle(departments)

In [59]:
dim_employee = pd.DataFrame({
    "Employee_ID": employee_ids,
    "BusinessUnit_ID": business_units,
    "Department_ID": departments
})

dim_employee.head()

  Employee_ID BusinessUnit_ID Department_ID
0    EMP00001           BU002        DEP002
1    EMP00002           BU001        DEP002
2    EMP00003           BU004        DEP004
3    EMP00004           BU004        DEP005
4    EMP00005           BU003        DEP001

In [60]:
# ============================================================
# ASSIGN ASSETS CORRECTLY BY BUSINESS UNIT
# ============================================================

import numpy as np

np.random.seed(42)

asset_map = {
    "BU001": [
        "AST001", "AST002", "AST003"
    ],  # Upstream

    "BU002": [
        "AST004", "AST005", "AST006", "AST007"
    ],  # Midstream

    "BU003": [
        "AST008", "AST009"
    ],  # Downstream

    "BU004": [
        "AST010"
    ],  # LNG

    "BU005": [
        "AST011", "AST012", "AST013"
    ]  # Renewables
}

dim_employee["Asset_ID"] = (
    dim_employee["BusinessUnit_ID"]
    .apply(lambda x: np.random.choice(asset_map[x]))
)

In [61]:
print(
    dim_employee["Asset_ID"]
    .value_counts()
    .sort_index()
)

Asset_ID
AST001    509
AST002    528
AST003    463
AST004    162
AST005    182
AST006    179
AST007    177
AST008    527
AST009    473
AST010    400
AST011    142
AST012    133
AST013    125
Name: count, dtype: int64

In [62]:
print(
    pd.crosstab(
        dim_employee["BusinessUnit_ID"],
        dim_employee["Asset_ID"]
    )
)

Asset_ID         AST001  AST002  AST003  AST004  AST005  AST006  AST007  \
BusinessUnit_ID
BU001               509     528     463       0       0       0       0
BU002                 0       0       0     162     182     179     177
BU003                 0       0       0       0       0       0       0
BU004                 0       0       0       0       0       0       0
BU005                 0       0       0       0       0       0       0

Asset_ID         AST008  AST009  AST010  AST011  AST012  AST013
BusinessUnit_ID
BU001                 0       0       0       0       0       0
BU002                 0       0       0       0       0       0
BU003               527     473       0       0       0       0
BU004                 0       0     400       0       0       0
BU005                 0       0       0     142     133     125

In [63]:
dim_employee.groupby(
    ["BusinessUnit_ID", "Asset_ID"]
).size().reset_index(name="Employees")

   BusinessUnit_ID Asset_ID  Employees
0            BU001   AST001        509
1            BU001   AST002        528
2            BU001   AST003        463
3            BU002   AST004        162
4            BU002   AST005        182
5            BU002   AST006        179
6            BU002   AST007        177
7            BU003   AST008        527
8            BU003   AST009        473
9            BU004   AST010        400
10           BU005   AST011        142
11           BU005   AST012        133
12           BU005   AST013        125

In [64]:
import numpy as np

np.random.seed(42)

job_role_map = {

    "DEP001": [   # Operations
        "Production Operator",
        "Control Room Operator",
        "Process Operator",
        "Field Operator",
        "Plant Operator"
    ],

    "DEP002": [   # Engineering
        "Mechanical Engineer",
        "Electrical Engineer",
        "Instrumentation Engineer",
        "Process Engineer",
        "Project Engineer"
    ],

    "DEP003": [   # Maintenance
        "Mechanical Technician",
        "Electrical Technician",
        "Instrumentation Technician",
        "Maintenance Planner",
        "Reliability Engineer"
    ],

    "DEP004": [   # HSE
        "HSE Officer",
        "HSE Advisor",
        "Safety Supervisor",
        "Environmental Officer",
        "Emergency Response Coordinator"
    ],

    "DEP005": [   # Logistics
        "Warehouse Officer",
        "Supply Chain Officer",
        "Materials Coordinator",
        "Transport Coordinator",
        "Logistics Officer"
    ],

    "DEP006": [   # Finance
        "Financial Analyst",
        "Accountant",
        "Cost Controller",
        "Finance Officer",
        "Procurement Analyst"
    ],

    "DEP007": [   # HR
        "HR Officer",
        "HR Business Partner",
        "Talent Acquisition Officer",
        "Training Coordinator",
        "Learning & Development Officer"
    ]
}

In [65]:
dim_employee["Job_Role"] = dim_employee["Department_ID"].apply(
    lambda x: np.random.choice(job_role_map[x])
)

In [66]:
dim_employee.groupby(
    ["Department_ID", "Job_Role"]
).size().reset_index(name="Employees")

   Department_ID                        Job_Role  Employees
0         DEP001           Control Room Operator        345
1         DEP001                  Field Operator        352
2         DEP001                  Plant Operator        341
3         DEP001                Process Operator        318
4         DEP001             Production Operator        344
5         DEP002             Electrical Engineer        121
6         DEP002        Instrumentation Engineer        138
7         DEP002             Mechanical Engineer        145
8         DEP002                Process Engineer        154
9         DEP002                Project Engineer        142
10        DEP003           Electrical Technician        102
11        DEP003      Instrumentation Technician         96
12        DEP003             Maintenance Planner        121
13        DEP003           Mechanical Technician        108
14        DEP003            Reliability Engineer        123
15        DEP004  Emergency Response Coordinator         69
16        DEP004           Environmental Officer         60
17        DEP004                     HSE Advisor         62
18        DEP004                     HSE Officer         79
19        DEP004               Safety Supervisor         80
20        DEP005               Logistics Officer         61
21        DEP005           Materials Coordinator         65
22        DEP005            Supply Chain Officer         61
23        DEP005           Transport Coordinator         57
24        DEP005               Warehouse Officer         56
25        DEP006                      Accountant         37
26        DEP006                 Cost Controller         39
27        DEP006                 Finance Officer         40
28        DEP006               Financial Analyst         43
29        DEP006             Procurement Analyst         41
30        DEP007             HR Business Partner         40
31        DEP007                      HR Officer         54
32        DEP007  Learning & Development Officer         32
33        DEP007      Talent Acquisition Officer         41
34        DEP007            Training Coordinator         33

In [67]:
import numpy as np

np.random.seed(42)

def assign_shift(dept):

    if dept == "DEP001":      # Operations
        return np.random.choice(
            ["SH001", "SH002", "SH003"],
            p=[0.45, 0.45, 0.10]
        )

    elif dept == "DEP002":    # Engineering
        return np.random.choice(
            ["SH001", "SH002"],
            p=[0.80, 0.20]
        )

    elif dept == "DEP003":    # Maintenance
        return np.random.choice(
            ["SH001", "SH002"],
            p=[0.70, 0.30]
        )

    elif dept == "DEP004":    # HSE
        return np.random.choice(
            ["SH001", "SH002"],
            p=[0.85, 0.15]
        )

    elif dept == "DEP005":    # Logistics
        return np.random.choice(
            ["SH001", "SH002"],
            p=[0.90, 0.10]
        )

    else:
        # Finance & HR
        return "SH001"

dim_employee["Shift_ID"] = dim_employee["Department_ID"].apply(assign_shift)

In [68]:
pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Shift_ID"]
)

Shift_ID       SH001  SH002  SH003
Department_ID
DEP001           776    757    167
DEP002           555    145      0
DEP003           381    169      0
DEP004           301     49      0
DEP005           271     29      0
DEP006           200      0      0
DEP007           200      0      0

In [69]:
import numpy as np

np.random.seed(42)

dim_employee["Employment_Type"] = np.random.choice(
    [
        "Permanent",
        "Contract",
        "Graduate Trainee"
    ],
    size=len(dim_employee),
    p=[0.70, 0.25, 0.05]
)

In [70]:
np.random.seed(42)

dim_employee["Employment_Status"] = np.random.choice(
    [
        "Active",
        "Leave",
        "Suspended"
    ],
    size=len(dim_employee),
    p=[0.97, 0.02, 0.01]
)

In [71]:
print(dim_employee["Employment_Type"].value_counts())

print()

print(dim_employee["Employment_Status"].value_counts())

Employment_Type
Permanent           2813
Contract             980
Graduate Trainee     207
Name: count, dtype: int64

Employment_Status
Active       3889
Leave          73
Suspended      38
Name: count, dtype: int64

In [72]:
import numpy as np

np.random.seed(42)

def assign_gender(dept):

    if dept == "DEP001":      # Operations
        return np.random.choice(
            ["Male", "Female"],
            p=[0.88, 0.12]
        )

    elif dept == "DEP002":    # Engineering
        return np.random.choice(
            ["Male", "Female"],
            p=[0.82, 0.18]
        )

    elif dept == "DEP003":    # Maintenance
        return np.random.choice(
            ["Male", "Female"],
            p=[0.90, 0.10]
        )

    elif dept == "DEP004":    # HSE
        return np.random.choice(
            ["Male", "Female"],
            p=[0.70, 0.30]
        )

    elif dept == "DEP005":    # Logistics
        return np.random.choice(
            ["Male", "Female"],
            p=[0.75, 0.25]
        )

    elif dept == "DEP006":    # Finance
        return np.random.choice(
            ["Male", "Female"],
            p=[0.55, 0.45]
        )

    else:                     # HR
        return np.random.choice(
            ["Male", "Female"],
            p=[0.45, 0.55]
        )

dim_employee["Gender"] = dim_employee["Department_ID"].apply(assign_gender)

In [73]:
pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Gender"]
)

Gender         Female  Male
Department_ID
DEP001            194  1506
DEP002            132   568
DEP003             53   497
DEP004             94   256
DEP005             88   212
DEP006             89   111
DEP007            116    84

In [74]:
import pandas as pd
import numpy as np

np.random.seed(42)

reference_year = 2026

def generate_dob(dept):

    if dept == "DEP001":
        age = np.random.randint(22, 59)

    elif dept == "DEP002":
        age = np.random.randint(24, 61)

    elif dept == "DEP003":
        age = np.random.randint(23, 59)

    elif dept == "DEP004":
        age = np.random.randint(24, 59)

    elif dept == "DEP005":
        age = np.random.randint(22, 56)

    else:
        age = np.random.randint(23, 59)

    year = reference_year - age

    month = np.random.randint(1, 13)
    day = np.random.randint(1, 29)

    return pd.Timestamp(year=year, month=month, day=day)

dim_employee["Date_of_Birth"] = dim_employee["Department_ID"].apply(generate_dob)

In [75]:
dim_employee["Age"] = (
    reference_year
    - dim_employee["Date_of_Birth"].dt.year
)

In [76]:
print(dim_employee["Age"].describe())

dim_employee["Age"].value_counts().sort_index().head()

dim_employee["Age"].value_counts().sort_index().tail()

count    4000.000000
mean       40.501250
std        10.467827
min        22.000000
25%        32.000000
50%        41.000000
75%        49.000000
max        60.000000
Name: Age, dtype: float64

Age
56    101
57     98
58     99
59     15
60     18
Name: count, dtype: int64

In [77]:
# ==========================================
# 12. HIRE DATE
# ==========================================

import numpy as np
import pandas as pd

np.random.seed(42)

service_groups = np.random.choice(
    [
        "0-2",
        "3-5",
        "6-10",
        "11-20",
        "21-30"
    ],
    size=num_employees,
    p=[
        0.20,
        0.25,
        0.30,
        0.20,
        0.05
    ]
)

hire_dates = []

for group in service_groups:

    if group == "0-2":
        year = np.random.randint(2024, 2027)

    elif group == "3-5":
        year = np.random.randint(2021, 2024)

    elif group == "6-10":
        year = np.random.randint(2016, 2021)

    elif group == "11-20":
        year = np.random.randint(2006, 2016)

    else:
        year = np.random.randint(1995, 2006)

    month = np.random.randint(1, 13)
    day = np.random.randint(1, 28)

    hire_dates.append(pd.Timestamp(year, month, day))

dim_employee["Hire_Date"] = hire_dates

dim_employee["Hire_Date"].head()

0   2022-05-05
1   2005-07-20
2   2020-04-25
3   2019-02-22
4   2025-05-22
Name: Hire_Date, dtype: datetime64[ns]

In [78]:
# ==========================================
# 13. YEARS OF SERVICE
# ==========================================

reference_date = pd.Timestamp("2026-07-31")

dim_employee["Years_of_Service"] = (
    (reference_date - dim_employee["Hire_Date"]).dt.days // 365
)

dim_employee[
    ["Hire_Date", "Years_of_Service"]
].head()

   Hire_Date  Years_of_Service
0 2022-05-05                 4
1 2005-07-20                21
2 2020-04-25                 6
3 2019-02-22                 7
4 2025-05-22                 1

In [79]:
# ==========================================
# 14. YEARS OF EXPERIENCE
# ==========================================

extra_experience = np.random.choice(
    [0, 1, 2, 3, 4, 5, 6, 7, 8],
    size=num_employees,
    p=[
        0.18,
        0.18,
        0.16,
        0.14,
        0.12,
        0.09,
        0.06,
        0.04,
        0.03
    ]
)

dim_employee["Years_of_Experience"] = (
    dim_employee["Years_of_Service"] +
    extra_experience
)

dim_employee[
    [
        "Hire_Date",
        "Years_of_Service",
        "Years_of_Experience"
    ]
].head()

   Hire_Date  Years_of_Service  Years_of_Experience
0 2022-05-05                 4                   11
1 2005-07-20                21                   22
2 2020-04-25                 6                   12
3 2019-02-22                 7                   12
4 2025-05-22                 1                    2

In [80]:
dim_employee["Years_of_Service"].describe()

count    4000.000000
mean        7.611750
std         6.761061
min        -1.000000
25%         3.000000
50%         6.000000
75%        10.000000
max        31.000000
Name: Years_of_Service, dtype: float64

In [81]:
dim_employee["Years_of_Experience"].describe()

count    4000.000000
mean       10.326250
std         7.112486
min        -1.000000
25%         5.000000
50%         9.000000
75%        14.000000
max        38.000000
Name: Years_of_Experience, dtype: float64

In [82]:
# ==========================================
# 15. SUPERVISOR ID
# ==========================================

import numpy as np

np.random.seed(42)

# Default: no supervisor assigned yet
dim_employee["Supervisor_ID"] = None

for dept in dim_employee["Department_ID"].unique():

    dept_index = dim_employee[
        dim_employee["Department_ID"] == dept
    ].index

    dept_employees = dim_employee.loc[dept_index, "Employee_ID"].values

    # About 12% become supervisors
    n_supervisors = max(1, int(len(dept_employees) * 0.12))

    supervisors = np.random.choice(
        dept_employees,
        size=n_supervisors,
        replace=False
    )

    for idx in dept_index:

        employee = dim_employee.loc[idx, "Employee_ID"]

        # Supervisors report to themselves (top of team)
        if employee in supervisors:
            dim_employee.loc[idx, "Supervisor_ID"] = employee

        else:
            dim_employee.loc[idx, "Supervisor_ID"] = np.random.choice(
                supervisors
            )

dim_employee[
    ["Employee_ID", "Department_ID", "Supervisor_ID"]
].head(20)

   Employee_ID Department_ID Supervisor_ID
0     EMP00001        DEP002      EMP01811
1     EMP00002        DEP002      EMP00766
2     EMP00003        DEP004      EMP00003
3     EMP00004        DEP005      EMP00004
4     EMP00005        DEP001      EMP02805
5     EMP00006        DEP007      EMP00006
6     EMP00007        DEP007      EMP00007
7     EMP00008        DEP001      EMP00408
8     EMP00009        DEP004      EMP02235
9     EMP00010        DEP003      EMP00928
10    EMP00011        DEP004      EMP00217
11    EMP00012        DEP001      EMP03043
12    EMP00013        DEP002      EMP00013
13    EMP00014        DEP001      EMP02805
14    EMP00015        DEP003      EMP03099
15    EMP00016        DEP004      EMP00064
16    EMP00017        DEP002      EMP03784
17    EMP00018        DEP003      EMP01956
18    EMP00019        DEP004      EMP02088
19    EMP00020        DEP001      EMP03348

In [83]:
print("Unique Supervisors:",
      dim_employee["Supervisor_ID"].nunique())

print("Employees:",
      len(dim_employee))

Unique Supervisors: 480
Employees: 4000

In [84]:
# ==========================================
# 16. CREW
# ==========================================

import numpy as np

np.random.seed(42)

field_crews = [
    "Crew A",
    "Crew B",
    "Crew C",
    "Crew D",
    "Crew E",
    "Crew F",
    "Crew G",
    "Crew H"
]

crew = []

for dept in dim_employee["Department_ID"]:

    # Finance
    if dept == "DEP006":
        crew.append("Corporate")

    # HR
    elif dept == "DEP007":
        crew.append("Corporate")

    # All operational departments
    else:
        crew.append(np.random.choice(field_crews))

dim_employee["Crew"] = crew

dim_employee[
    ["Department_ID", "Crew"]
].head()

  Department_ID    Crew
0        DEP002  Crew G
1        DEP002  Crew D
2        DEP004  Crew E
3        DEP005  Crew G
4        DEP001  Crew C

In [85]:
dim_employee["Crew"].value_counts()

Crew
Crew E       474
Crew A       469
Crew D       460
Crew B       457
Crew F       446
Crew G       441
Crew H       429
Crew C       424
Corporate    400
Name: count, dtype: int64

In [86]:
pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Crew"]
)

Crew,Corporate,Crew A,Crew B,Crew C,Crew D,Crew E,Crew F,Crew G,Crew H
Department_ID,,,,,,,,,
DEP001,0,219,231,193,244,213,185,214,201
DEP002,0,89,72,90,82,98,93,79,97
DEP003,0,80,66,70,65,66,87,64,52
DEP004,0,46,45,44,40,55,41,41,38
DEP005,0,35,43,27,29,42,40,43,41
DEP006,200,0,0,0,0,0,0,0,0
DEP007,200,0,0,0,0,0,0,0,0

In [87]:
# ============================================================
# 17. EDUCATION LEVEL
# Realistic workforce distribution by department
# ============================================================

np.random.seed(42)

education_by_department = {

    # Operations
    "DEP001": {
        "Secondary School": 0.08,
        "OND/NCE": 0.32,
        "HND": 0.38,
        "Bachelor's Degree": 0.19,
        "Master's Degree": 0.03
    },

    # Engineering
    "DEP002": {
        "OND/NCE": 0.05,
        "HND": 0.15,
        "Bachelor's Degree": 0.55,
        "Master's Degree": 0.24,
        "Doctorate": 0.01
    },

    # Maintenance
    "DEP003": {
        "Secondary School": 0.05,
        "OND/NCE": 0.35,
        "HND": 0.42,
        "Bachelor's Degree": 0.16,
        "Master's Degree": 0.02
    },

    # HSE
    "DEP004": {
        "OND/NCE": 0.05,
        "HND": 0.20,
        "Bachelor's Degree": 0.52,
        "Master's Degree": 0.22,
        "Doctorate": 0.01
    },

    # Logistics
    "DEP005": {
        "Secondary School": 0.05,
        "OND/NCE": 0.30,
        "HND": 0.38,
        "Bachelor's Degree": 0.23,
        "Master's Degree": 0.04
    },

    # Finance
    "DEP006": {
        "OND/NCE": 0.03,
        "HND": 0.07,
        "Bachelor's Degree": 0.57,
        "Master's Degree": 0.31,
        "Doctorate": 0.02
    },

    # HR
    "DEP007": {
        "OND/NCE": 0.03,
        "HND": 0.07,
        "Bachelor's Degree": 0.57,
        "Master's Degree": 0.31,
        "Doctorate": 0.02
    }
}


def assign_education(department_id):

    levels = list(
        education_by_department[department_id].keys()
    )

    probabilities = list(
        education_by_department[department_id].values()
    )

    return np.random.choice(
        levels,
        p=probabilities
    )


dim_employee["Education_Level"] = (
    dim_employee["Department_ID"]
    .apply(assign_education)
)

In [88]:
print(
    dim_employee["Education_Level"].value_counts()
)

Education_Level
Bachelor's Degree    1252
HND                  1191
OND/NCE               902
Master's Degree       452
Secondary School      192
Doctorate              11
Name: count, dtype: int64

In [89]:
education_by_dept_check = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Education_Level"]
)

education_by_dept_check

Education_Level,Bachelor's Degree,Doctorate,HND,Master's Degree,OND/NCE,Secondary School
Department_ID,,,,,,
DEP001,310,0,633,45,571,141
DEP002,359,5,116,178,42,0
DEP003,90,0,229,12,178,41
DEP004,189,3,74,70,14,0
DEP005,76,0,113,14,87,10
DEP006,115,0,16,64,5,0
DEP007,113,3,10,69,5,0

In [90]:
education_by_dept_pct = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Education_Level"],
    normalize="index"
).round(3) * 100

education_by_dept_pct

Education_Level,Bachelor's Degree,Doctorate,HND,Master's Degree,OND/NCE,Secondary School
Department_ID,,,,,,
DEP001,18.2,0.0,37.2,2.6,33.6,8.3
DEP002,51.3,0.7,16.6,25.4,6.0,0.0
DEP003,16.4,0.0,41.6,2.2,32.4,7.5
DEP004,54.0,0.9,21.1,20.0,4.0,0.0
DEP005,25.3,0.0,37.7,4.7,29.0,3.3
DEP006,57.5,0.0,8.0,32.0,2.5,0.0
DEP007,56.5,1.5,5.0,34.5,2.5,0.0

In [91]:
# ============================================================
# 18. CERTIFICATION STATUS
# Realistic certification status by department
# ============================================================

np.random.seed(42)

certification_by_department = {

    # Operations
    "DEP001": {
        "Valid": 0.82,
        "Expired": 0.08,
        "Pending Renewal": 0.07,
        "Not Certified": 0.03
    },

    # Engineering
    "DEP002": {
        "Valid": 0.88,
        "Expired": 0.05,
        "Pending Renewal": 0.05,
        "Not Certified": 0.02
    },

    # Maintenance
    "DEP003": {
        "Valid": 0.84,
        "Expired": 0.07,
        "Pending Renewal": 0.07,
        "Not Certified": 0.02
    },

    # HSE
    "DEP004": {
        "Valid": 0.92,
        "Expired": 0.03,
        "Pending Renewal": 0.04,
        "Not Certified": 0.01
    },

    # Logistics
    "DEP005": {
        "Valid": 0.78,
        "Expired": 0.09,
        "Pending Renewal": 0.08,
        "Not Certified": 0.05
    },

    # Finance
    "DEP006": {
        "Valid": 0.70,
        "Expired": 0.10,
        "Pending Renewal": 0.10,
        "Not Certified": 0.10
    },

    # HR
    "DEP007": {
        "Valid": 0.72,
        "Expired": 0.09,
        "Pending Renewal": 0.10,
        "Not Certified": 0.09
    }
}


def assign_certification(department_id):

    statuses = list(
        certification_by_department[department_id].keys()
    )

    probabilities = list(
        certification_by_department[department_id].values()
    )

    return np.random.choice(
        statuses,
        p=probabilities
    )


dim_employee["Certification_Status"] = (
    dim_employee["Department_ID"]
    .apply(assign_certification)
)

In [92]:
dim_employee["Certification_Status"].value_counts()

certification_check = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Certification_Status"]
)

certification_check

Certification_Status  Expired  Not Certified  Pending Renewal  Valid
Department_ID
DEP001                    126             45              112   1417
DEP002                     36             15               38    611
DEP003                     39             12               35    464
DEP004                     11              3               15    321
DEP005                     39             17               23    221
DEP006                     20             15               25    140
DEP007                     17             21               20    142

In [93]:
certification_check_pct = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Certification_Status"],
    normalize="index"
).round(3) * 100

certification_check_pct

Certification_Status  Expired  Not Certified  Pending Renewal  Valid
Department_ID
DEP001                    7.4            2.6              6.6   83.4
DEP002                    5.1            2.1              5.4   87.3
DEP003                    7.1            2.2              6.4   84.4
DEP004                    3.1            0.9              4.3   91.7
DEP005                   13.0            5.7              7.7   73.7
DEP006                   10.0            7.5             12.5   70.0
DEP007                    8.5           10.5             10.0   71.0

In [94]:
# ============================================================
# 19. TRAINING COMPLIANCE
# Realistic training compliance by department
# ============================================================

np.random.seed(42)

training_compliance_by_department = {

    # Operations
    "DEP001": {
        "Compliant": 0.88,
        "Overdue": 0.08,
        "Partially Compliant": 0.04
    },

    # Engineering
    "DEP002": {
        "Compliant": 0.90,
        "Overdue": 0.06,
        "Partially Compliant": 0.04
    },

    # Maintenance
    "DEP003": {
        "Compliant": 0.87,
        "Overdue": 0.08,
        "Partially Compliant": 0.05
    },

    # HSE
    "DEP004": {
        "Compliant": 0.94,
        "Overdue": 0.03,
        "Partially Compliant": 0.03
    },

    # Logistics
    "DEP005": {
        "Compliant": 0.82,
        "Overdue": 0.10,
        "Partially Compliant": 0.08
    },

    # Finance
    "DEP006": {
        "Compliant": 0.76,
        "Overdue": 0.12,
        "Partially Compliant": 0.12
    },

    # HR
    "DEP007": {
        "Compliant": 0.78,
        "Overdue": 0.11,
        "Partially Compliant": 0.11
    }
}


def assign_training_compliance(department_id):

    statuses = list(
        training_compliance_by_department[department_id].keys()
    )

    probabilities = list(
        training_compliance_by_department[department_id].values()
    )

    return np.random.choice(
        statuses,
        p=probabilities
    )


dim_employee["Training_Compliance"] = (
    dim_employee["Department_ID"]
    .apply(assign_training_compliance)
)

In [95]:
dim_employee["Training_Compliance"].value_counts()

training_check = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Training_Compliance"]
)

training_check

Training_Compliance  Compliant  Overdue  Partially Compliant
Department_ID
DEP001                    1506      130                   64
DEP002                     628       36                   36
DEP003                     483       35                   32
DEP004                     327       13                   10
DEP005                     243       31                   26
DEP006                     153       26                   21
DEP007                     154       21                   25

In [96]:
# ============================================================
# 20. PPE COMPLIANCE
# Realistic PPE compliance by department
# ============================================================

np.random.seed(42)

ppe_compliance_by_department = {

    # Operations
    "DEP001": {
        "Compliant": 0.91,
        "Non-Compliant": 0.06,
        "Not Applicable": 0.03
    },

    # Engineering
    "DEP002": {
        "Compliant": 0.88,
        "Non-Compliant": 0.07,
        "Not Applicable": 0.05
    },

    # Maintenance
    "DEP003": {
        "Compliant": 0.90,
        "Non-Compliant": 0.07,
        "Not Applicable": 0.03
    },

    # HSE
    "DEP004": {
        "Compliant": 0.95,
        "Non-Compliant": 0.03,
        "Not Applicable": 0.02
    },

    # Logistics
    "DEP005": {
        "Compliant": 0.82,
        "Non-Compliant": 0.10,
        "Not Applicable": 0.08
    },

    # Finance
    "DEP006": {
        "Compliant": 0.35,
        "Non-Compliant": 0.05,
        "Not Applicable": 0.60
    },

    # HR
    "DEP007": {
        "Compliant": 0.35,
        "Non-Compliant": 0.05,
        "Not Applicable": 0.60
    }
}


def assign_ppe_compliance(department_id):

    statuses = list(
        ppe_compliance_by_department[department_id].keys()
    )

    probabilities = list(
        ppe_compliance_by_department[department_id].values()
    )

    return np.random.choice(
        statuses,
        p=probabilities
    )


dim_employee["PPE_Compliance"] = (
    dim_employee["Department_ID"]
    .apply(assign_ppe_compliance)
)

In [97]:
dim_employee["PPE_Compliance"].value_counts()

PPE_Compliance
Compliant         3386
Not Applicable     371
Non-Compliant      243
Name: count, dtype: int64

In [98]:
ppe_check = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["PPE_Compliance"]
)

ppe_check

PPE_Compliance  Compliant  Non-Compliant  Not Applicable
Department_ID
DEP001               1562             93              45
DEP002                611             50              39
DEP003                497             36              17
DEP004                332             12               6
DEP005                243             31              26
DEP006                 75             10             115
DEP007                 66             11             123

In [99]:
ppe_check_pct = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["PPE_Compliance"],
    normalize="index"
).round(3) * 100

ppe_check_pct

PPE_Compliance  Compliant  Non-Compliant  Not Applicable
Department_ID
DEP001               91.9            5.5             2.6
DEP002               87.3            7.1             5.6
DEP003               90.4            6.5             3.1
DEP004               94.9            3.4             1.7
DEP005               81.0           10.3             8.7
DEP006               37.5            5.0            57.5
DEP007               33.0            5.5            61.5

In [100]:
training_check_pct = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Training_Compliance"],
    normalize="index"
).round(3) * 100

training_check_pct

Training_Compliance  Compliant  Overdue  Partially Compliant
Department_ID
DEP001                    88.6      7.6                  3.8
DEP002                    89.7      5.1                  5.1
DEP003                    87.8      6.4                  5.8
DEP004                    93.4      3.7                  2.9
DEP005                    81.0     10.3                  8.7
DEP006                    76.5     13.0                 10.5
DEP007                    77.0     10.5                 12.5

In [101]:
# ============================================================
# 21. MEDICAL FITNESS
# ============================================================

np.random.seed(42)

medical_fitness_by_department = {

    # Operations — safety-critical / physically demanding
    "DEP001": {
        "Fit": 0.94,
        "Fit with Restrictions": 0.04,
        "Under Medical Review": 0.02
    },

    # Engineering
    "DEP002": {
        "Fit": 0.95,
        "Fit with Restrictions": 0.03,
        "Under Medical Review": 0.02
    },

    # Maintenance — physically demanding
    "DEP003": {
        "Fit": 0.93,
        "Fit with Restrictions": 0.05,
        "Under Medical Review": 0.02
    },

    # HSE
    "DEP004": {
        "Fit": 0.96,
        "Fit with Restrictions": 0.03,
        "Under Medical Review": 0.01
    },

    # Logistics
    "DEP005": {
        "Fit": 0.92,
        "Fit with Restrictions": 0.05,
        "Under Medical Review": 0.03
    },

    # Finance
    "DEP006": {
        "Fit": 0.96,
        "Fit with Restrictions": 0.02,
        "Under Medical Review": 0.02
    },

    # HR
    "DEP007": {
        "Fit": 0.96,
        "Fit with Restrictions": 0.02,
        "Under Medical Review": 0.02
    }
}


def assign_medical_fitness(department_id):

    statuses = list(
        medical_fitness_by_department[department_id].keys()
    )

    probabilities = list(
        medical_fitness_by_department[department_id].values()
    )

    return np.random.choice(
        statuses,
        p=probabilities
    )


dim_employee["Medical_Fitness"] = (
    dim_employee["Department_ID"]
    .apply(assign_medical_fitness)
)

In [102]:
dim_employee["Medical_Fitness"].value_counts()

medical_fitness_check = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Medical_Fitness"]
)

medical_fitness_check

Medical_Fitness   Fit  Fit with Restrictions  Under Medical Review
Department_ID
DEP001           1606                     58                    36
DEP002            661                     24                    15
DEP003            507                     31                    12
DEP004            337                     10                     3
DEP005            274                     16                    10
DEP006            193                      7                     0
DEP007            190                      7                     3

In [103]:
medical_fitness_check_pct = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Medical_Fitness"],
    normalize="index"
).round(3) * 100

medical_fitness_check_pct

Medical_Fitness   Fit  Fit with Restrictions  Under Medical Review
Department_ID
DEP001           94.5                    3.4                   2.1
DEP002           94.4                    3.4                   2.1
DEP003           92.2                    5.6                   2.2
DEP004           96.3                    2.9                   0.9
DEP005           91.3                    5.3                   3.3
DEP006           96.5                    3.5                   0.0
DEP007           95.0                    3.5                   1.5

In [104]:
# ============================================================
# 22. EMERGENCY RESPONSE TEAM
# ============================================================

np.random.seed(42)

ert_by_department = {

    # Operations — strong emergency response presence
    "DEP001": {
        "Primary ERT Member": 0.12,
        "Backup ERT Member": 0.13,
        "Not ERT": 0.75
    },

    # Engineering
    "DEP002": {
        "Primary ERT Member": 0.08,
        "Backup ERT Member": 0.10,
        "Not ERT": 0.82
    },

    # Maintenance
    "DEP003": {
        "Primary ERT Member": 0.10,
        "Backup ERT Member": 0.12,
        "Not ERT": 0.78
    },

    # HSE — highest ERT participation
    "DEP004": {
        "Primary ERT Member": 0.25,
        "Backup ERT Member": 0.20,
        "Not ERT": 0.55
    },

    # Logistics
    "DEP005": {
        "Primary ERT Member": 0.06,
        "Backup ERT Member": 0.09,
        "Not ERT": 0.85
    },

    # Finance
    "DEP006": {
        "Primary ERT Member": 0.01,
        "Backup ERT Member": 0.04,
        "Not ERT": 0.95
    },

    # HR
    "DEP007": {
        "Primary ERT Member": 0.01,
        "Backup ERT Member": 0.04,
        "Not ERT": 0.95
    }
}


def assign_ert(department_id):

    statuses = list(
        ert_by_department[department_id].keys()
    )

    probabilities = list(
        ert_by_department[department_id].values()
    )

    return np.random.choice(
        statuses,
        p=probabilities
    )


dim_employee["Emergency_Response_Team"] = (
    dim_employee["Department_ID"]
    .apply(assign_ert)
)

In [105]:
dim_employee["Emergency_Response_Team"].value_counts()


ert_check = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Emergency_Response_Team"]
)

ert_check

Emergency_Response_Team  Backup ERT Member  Not ERT  Primary ERT Member
Department_ID
DEP001                                 223     1266                 211
DEP002                                  72      556                  72
DEP003                                  63      420                  67
DEP004                                  61      201                  88
DEP005                                  22      266                  12
DEP006                                   8      190                   2
DEP007                                   5      193                   2

In [106]:
ert_check_pct = pd.crosstab(
    dim_employee["Department_ID"],
    dim_employee["Emergency_Response_Team"],
    normalize="index"
).round(3) * 100

ert_check_pct

Emergency_Response_Team  Backup ERT Member  Not ERT  Primary ERT Member
Department_ID
DEP001                                13.1     74.5                12.4
DEP002                                10.3     79.4                10.3
DEP003                                11.5     76.4                12.2
DEP004                                17.4     57.4                25.1
DEP005                                 7.3     88.7                 4.0
DEP006                                 4.0     95.0                 1.0
DEP007                                 2.5     96.5                 1.0

In [107]:
# ============================================================
# 23. NATIONALITY
# ============================================================

np.random.seed(42)

nationalities = [
    "Nigerian",
    "Ghanaian",
    "British",
    "American",
    "South African",
    "Indian",
    "French",
    "Canadian",
    "Other"
]

nationality_probabilities = [
    0.82,   # Nigerian
    0.04,   # Ghanaian
    0.025,  # British
    0.025,  # American
    0.02,   # South African
    0.02,   # Indian
    0.015,  # French
    0.01,   # Canadian
    0.025   # Other
]

dim_employee["Nationality"] = np.random.choice(
    nationalities,
    size=len(dim_employee),
    p=nationality_probabilities
)

In [108]:
dim_employee["Nationality"].value_counts()

Nationality
Nigerian         3289
Ghanaian          152
British           109
American          106
Other              93
Indian             77
French             64
South African      60
Canadian           50
Name: count, dtype: int64

In [109]:
nationality_check = (
    dim_employee["Nationality"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .reset_index()
)

nationality_check.columns = [
    "Nationality",
    "Percentage"
]

nationality_check

     Nationality  Percentage
0       Nigerian       82.22
1       Ghanaian        3.80
2        British        2.72
3       American        2.65
4          Other        2.33
5         Indian        1.92
6         French        1.60
7  South African        1.50
8       Canadian        1.25

In [110]:
# ============================================================
# 24. WORK LOCATION
# Derived directly from assigned operational asset
# ============================================================

asset_location_map = {
    "AST001": "Offshore Platform A",
    "AST002": "Offshore Platform B",
    "AST003": "Offshore Platform C",
    "AST004": "Pipeline Network Alpha",
    "AST005": "Pipeline Network Bravo",
    "AST006": "Gas Compression Station",
    "AST007": "Gas Processing Plant",
    "AST008": "Refinery Complex",
    "AST009": "Fuel Distribution Terminal",
    "AST010": "LNG Export Terminal",
    "AST011": "Solar Farm North",
    "AST012": "Solar Farm South",
    "AST013": "Wind Farm"
}

dim_employee["Work_Location"] = (
    dim_employee["Asset_ID"]
    .map(asset_location_map)
)

In [111]:


print("Missing Work Locations:",
      dim_employee["Work_Location"].isna().sum())

print("Unique Work Locations:",
      dim_employee["Work_Location"].nunique())

Missing Work Locations: 0
Unique Work Locations: 13

In [112]:
location_check = dim_employee[
    ["Employee_ID", "BusinessUnit_ID", "Department_ID",
     "Asset_ID", "Work_Location"]
]

location_check.head(20)

,Employee_ID,BusinessUnit_ID,Department_ID,Asset_ID,Work_Location
0,EMP00001,BU002,DEP002,AST006,Gas Compression Station
1,EMP00002,BU001,DEP002,AST001,Offshore Platform A
2,EMP00003,BU004,DEP004,AST010,LNG Export Terminal
3,EMP00004,BU004,DEP005,AST010,LNG Export Terminal
4,EMP00005,BU003,DEP001,AST008,Refinery Complex
5,EMP00006,BU003,DEP007,AST008,Refinery Complex
6,EMP00007,BU003,DEP007,AST009,Fuel Distribution Terminal
7,EMP00008,BU003,DEP001,AST008,Refinery Complex
8,EMP00009,BU005,DEP004,AST011,Solar Farm North
9,EMP00010,BU003,DEP003,AST008,Refinery Complex
10,EMP00011,BU003,DEP004,AST009,Fuel Distribution Terminal
11,EMP00012,BU003,DEP001,AST008,Refinery Complex
12,EMP00013,BU005,DEP002,AST013,Wind Farm
13,EMP00014,BU003,DEP001,AST008,Refinery Complex
14,EMP00015,BU001,DEP003,AST003,Offshore Platform C
15,EMP00016,BU001,DEP004,AST001,Offshore Platform A
16,EMP00017,BU002,DEP002,AST007,Gas Processing Plant
17,EMP00018,BU005,DEP003,AST013,Wind Farm
18,EMP00019,BU003,DEP004,AST009,Fuel Distribution Terminal
19,EMP00020,BU002,DEP001,AST004,Pipeline Network Alpha

In [113]:
invalid_locations = dim_employee[
    dim_employee["Work_Location"].isna()
]

print("Invalid employee locations:", len(invalid_locations))

Invalid employee locations: 0

In [114]:
print("========== DIM_EMPLOYEE FINAL CHECK ==========")

print("Rows:", len(dim_employee))
print("Columns:", len(dim_employee.columns))

print("\nColumns:")
for i, col in enumerate(dim_employee.columns, start=1):
    print(f"{i}. {col}")

========== DIM_EMPLOYEE FINAL CHECK ==========
Rows: 4000
Columns: 24

Columns:
1. Employee_ID
2. BusinessUnit_ID
3. Department_ID
4. Asset_ID
5. Job_Role
6. Shift_ID
7. Employment_Type
8. Employment_Status
9. Gender
10. Date_of_Birth
11. Age
12. Hire_Date
13. Years_of_Service
14. Years_of_Experience
15. Supervisor_ID
16. Crew
17. Education_Level
18. Certification_Status
19. Training_Compliance
20. PPE_Compliance
21. Medical_Fitness
22. Emergency_Response_Team
23. Nationality
24. Work_Location

In [115]:
print("\n========== NULL CHECK ==========")

print(
    dim_employee.isna().sum()
    .sort_values(ascending=False)
)

========== NULL CHECK ==========
Employee_ID                0
BusinessUnit_ID            0
Department_ID              0
Asset_ID                   0
Job_Role                   0
Shift_ID                   0
Employment_Type            0
Employment_Status          0
Gender                     0
Date_of_Birth              0
Age                        0
Hire_Date                  0
Years_of_Service           0
Years_of_Experience        0
Supervisor_ID              0
Crew                       0
Education_Level            0
Certification_Status       0
Training_Compliance        0
PPE_Compliance             0
Medical_Fitness            0
Emergency_Response_Team    0
Nationality                0
Work_Location              0
dtype: int64

In [116]:
print("\n========== UNIQUE VALUES ==========")

print("Employees:", dim_employee["Employee_ID"].nunique())
print("Business Units:", dim_employee["BusinessUnit_ID"].nunique())
print("Departments:", dim_employee["Department_ID"].nunique())
print("Assets:", dim_employee["Asset_ID"].nunique())
print("Job Roles:", dim_employee["Job_Role"].nunique())
print("Shifts:", dim_employee["Shift_ID"].nunique())
print("Locations:", dim_employee["Work_Location"].nunique())

========== UNIQUE VALUES ==========
Employees: 4000
Business Units: 5
Departments: 7
Assets: 13
Job Roles: 35
Shifts: 3
Locations: 13

In [117]:
department_distribution = (
    dim_employee["Department_ID"]
    .value_counts()
    .sort_index()
    .reset_index()
)

department_distribution.columns = [
    "Department_ID",
    "Employee_Count"
]

department_distribution

  Department_ID  Employee_Count
0        DEP001            1700
1        DEP002             700
2        DEP003             550
3        DEP004             350
4        DEP005             300
5        DEP006             200
6        DEP007             200

In [118]:
dim_asset[dim_asset["Asset_ID"] == "AST014"]

Empty DataFrame
Columns: [Asset_ID, BusinessUnit_ID, Asset_Name]
Index: []

In [119]:
dim_asset

   Asset_ID BusinessUnit_ID                  Asset_Name
0    AST001           BU001         Offshore Platform A
1    AST002           BU001         Offshore Platform B
2    AST003           BU001         Offshore Platform C
3    AST004           BU002      Pipeline Network Alpha
4    AST005           BU002      Pipeline Network Bravo
5    AST006           BU002     Gas Compression Station
6    AST007           BU002        Gas Processing Plant
7    AST008           BU003            Refinery Complex
8    AST009           BU003  Fuel Distribution Terminal
9    AST010           BU004         LNG Export Terminal
10   AST011           BU005            Solar Farm North
11   AST012           BU005            Solar Farm South
12   AST013           BU005                   Wind Farm

In [120]:
dim_employee["Asset_ID"].value_counts().sort_index()

Asset_ID
AST001    509
AST002    528
AST003    463
AST004    162
AST005    182
AST006    179
AST007    177
AST008    527
AST009    473
AST010    400
AST011    142
AST012    133
AST013    125
Name: count, dtype: int64

In [121]:
# ============================================================
# FINAL DIM_EMPLOYEE INTEGRITY CHECK
# ============================================================

print("========== DIM_EMPLOYEE INTEGRITY CHECK ==========")

print("Rows:", len(dim_employee))
print("Columns:", len(dim_employee.columns))

print("Unique Employees:",
      dim_employee["Employee_ID"].nunique())

print("Unique Business Units:",
      dim_employee["BusinessUnit_ID"].nunique())

print("Unique Departments:",
      dim_employee["Department_ID"].nunique())

print("Unique Assets:",
      dim_employee["Asset_ID"].nunique())

print("Unique Job Roles:",
      dim_employee["Job_Role"].nunique())

print("Unique Shifts:",
      dim_employee["Shift_ID"].nunique())

print("Unique Work Locations:",
      dim_employee["Work_Location"].nunique())

print("\nTotal Missing Values:",
      dim_employee.isna().sum().sum())

========== DIM_EMPLOYEE INTEGRITY CHECK ==========
Rows: 4000
Columns: 24
Unique Employees: 4000
Unique Business Units: 5
Unique Departments: 7
Unique Assets: 13
Unique Job Roles: 35
Unique Shifts: 3
Unique Work Locations: 13

Total Missing Values: 0

In [122]:
# Check every employee asset exists in Dim_Asset
invalid_assets = set(dim_employee["Asset_ID"]) - set(dim_asset["Asset_ID"])

print("Invalid Asset IDs:", invalid_assets)

Invalid Asset IDs: set()

In [123]:
# ============================================================
# PHASE 3 — DIM_DATE
# ============================================================

import pandas as pd

# Study period
start_date = "2022-01-01"
end_date = "2026-07-31"

date_range = pd.date_range(
    start=start_date,
    end=end_date,
    freq="D"
)

dim_date = pd.DataFrame({
    "Date": date_range
})

# Date attributes
dim_date["Date_ID"] = (
    dim_date["Date"].dt.strftime("%Y%m%d").astype(int)
)

dim_date["Year"] = dim_date["Date"].dt.year

dim_date["Quarter"] = (
    "Q" + dim_date["Date"].dt.quarter.astype(str)
)

dim_date["Month_Number"] = (
    dim_date["Date"].dt.month
)

dim_date["Month_Name"] = (
    dim_date["Date"].dt.month_name()
)

dim_date["Month_Year"] = (
    dim_date["Date"].dt.strftime("%b-%Y")
)

dim_date["Week_Number"] = (
    dim_date["Date"].dt.isocalendar().week.astype(int)
)

dim_date["Day_Name"] = (
    dim_date["Date"].dt.day_name()
)

dim_date["Day_of_Week"] = (
    dim_date["Date"].dt.dayofweek + 1
)

# Weekend indicator
dim_date["Is_Weekend"] = (
    dim_date["Date"].dt.dayofweek >= 5
)

# Reorder
dim_date = dim_date[
    [
        "Date_ID",
        "Date",
        "Year",
        "Quarter",
        "Month_Number",
        "Month_Name",
        "Month_Year",
        "Week_Number",
        "Day_Name",
        "Day_of_Week",
        "Is_Weekend"
    ]
]

print("========== DIM_DATE CHECK ==========")
print("Rows:", len(dim_date))
print("Columns:", len(dim_date.columns))
print("Start Date:", dim_date["Date"].min())
print("End Date:", dim_date["Date"].max())
print("Years:", sorted(dim_date["Year"].unique()))
print()
print(dim_date.head())

========== DIM_DATE CHECK ==========
Rows: 1673
Columns: 11
Start Date: 2022-01-01 00:00:00
End Date: 2026-07-31 00:00:00
Years: [np.int32(2022), np.int32(2023), np.int32(2024), np.int32(2025), np.int32(2026)]

    Date_ID       Date  Year Quarter  Month_Number Month_Name Month_Year  \
0  20220101 2022-01-01  2022      Q1             1    January   Jan-2022
1  20220102 2022-01-02  2022      Q1             1    January   Jan-2022
2  20220103 2022-01-03  2022      Q1             1    January   Jan-2022
3  20220104 2022-01-04  2022      Q1             1    January   Jan-2022
4  20220105 2022-01-05  2022      Q1             1    January   Jan-2022

   Week_Number   Day_Name  Day_of_Week  Is_Weekend
0           52   Saturday            6        True
1           52     Sunday            7        True
2            1     Monday            1       False
3            1    Tuesday            2       False
4            1  Wednesday            3       False

In [124]:
# ============================================================
# PHASE 3 — DIM_LOCATION
# KEYSTRA NIGERIA OPERATING FOOTPRINT
# ============================================================

dim_location = pd.DataFrame({

    "Location_ID": [
        "LOC001",
        "LOC002",
        "LOC003",
        "LOC004",
        "LOC005",
        "LOC006",
        "LOC007",
        "LOC008"
    ],

    "Location_Name": [
        "Bonny Offshore & Coastal Operations",
        "Port Harcourt Operations Base",
        "Warri–Escravos Operations Area",
        "Brass–Bayelsa Operations Area",
        "Eket–Qua Iboe Operations Area",
        "Lagos Corporate Headquarters",
        "Abuja Corporate & Administrative Office",
        "Renewable Energy Operations Base"
    ],

    "State": [
        "Rivers",
        "Rivers",
        "Delta",
        "Bayelsa",
        "Akwa Ibom",
        "Lagos",
        "FCT",
        "Kaduna"
    ],

    "Country": [
        "Nigeria",
        "Nigeria",
        "Nigeria",
        "Nigeria",
        "Nigeria",
        "Nigeria",
        "Nigeria",
        "Nigeria"
    ],

    "Operational_Environment": [
        "Offshore / Coastal",
        "Onshore / Industrial",
        "Onshore / Offshore",
        "Onshore / Offshore",
        "Onshore / Offshore",
        "Corporate Office",
        "Corporate Office",
        "Renewable Energy"
    ]
})

print("========== DIM_LOCATION CHECK ==========")
print("Rows:", len(dim_location))
print("Columns:", len(dim_location.columns))
print()
print(dim_location)

========== DIM_LOCATION CHECK ==========
Rows: 8
Columns: 5

  Location_ID                            Location_Name      State  Country  \
0      LOC001      Bonny Offshore & Coastal Operations     Rivers  Nigeria
1      LOC002            Port Harcourt Operations Base     Rivers  Nigeria
2      LOC003           Warri–Escravos Operations Area      Delta  Nigeria
3      LOC004            Brass–Bayelsa Operations Area    Bayelsa  Nigeria
4      LOC005            Eket–Qua Iboe Operations Area  Akwa Ibom  Nigeria
5      LOC006             Lagos Corporate Headquarters      Lagos  Nigeria
6      LOC007  Abuja Corporate & Administrative Office        FCT  Nigeria
7      LOC008         Renewable Energy Operations Base     Kaduna  Nigeria

  Operational_Environment
0      Offshore / Coastal
1    Onshore / Industrial
2      Onshore / Offshore
3      Onshore / Offshore
4      Onshore / Offshore
5        Corporate Office
6        Corporate Office
7        Renewable Energy

In [125]:
print("Unique Location IDs:",
      dim_location["Location_ID"].nunique())

print("Missing Values:",
      dim_location.isna().sum().sum())

print("Duplicate Location IDs:",
      dim_location["Location_ID"].duplicated().sum())

Unique Location IDs: 8
Missing Values: 0
Duplicate Location IDs: 0

In [126]:
# ============================================================
# ASSET → LOCATION MAPPING
# ============================================================

asset_location_map = {

    # Upstream
    "AST001": "LOC001",  # Offshore Platform A → Bonny
    "AST002": "LOC001",  # Offshore Platform B → Bonny
    "AST003": "LOC004",  # Offshore Platform C → Brass–Bayelsa

    # Midstream
    "AST004": "LOC003",  # Pipeline Network Alpha → Warri–Escravos
    "AST005": "LOC004",  # Pipeline Network Bravo → Brass–Bayelsa
    "AST006": "LOC002",  # Gas Compression Station → Port Harcourt
    "AST007": "LOC002",  # Gas Processing Plant → Port Harcourt

    # Downstream
    "AST008": "LOC003",  # Refinery Complex → Warri–Escravos
    "AST009": "LOC006",  # Fuel Distribution Terminal → Lagos

    # LNG
    "AST010": "LOC001",  # LNG Export Terminal → Bonny

    # Renewables
    "AST011": "LOC008",  # Solar Farm North → Renewable Energy Base
    "AST012": "LOC008",  # Solar Farm South → Renewable Energy Base
    "AST013": "LOC008"   # Wind Farm → Renewable Energy Base
}

In [127]:
# ============================================================
# VALIDATE ASSET → LOCATION MAPPING
# ============================================================

print("Assets in Dim_Asset:", dim_asset["Asset_ID"].nunique())
print("Assets in Mapping:", len(asset_location_map))

print("\nAssets missing from mapping:")
print(
    set(dim_asset["Asset_ID"])
    - set(asset_location_map.keys())
)

print("\nInvalid assets in mapping:")
print(
    set(asset_location_map.keys())
    - set(dim_asset["Asset_ID"])
)

print("\nInvalid locations in mapping:")
print(
    set(asset_location_map.values())
    - set(dim_location["Location_ID"])
)

Assets in Dim_Asset: 13
Assets in Mapping: 13

Assets missing from mapping:
set()

Invalid assets in mapping:
set()

Invalid locations in mapping:
set()

In [128]:
asset_location_bridge = dim_asset[
    ["Asset_ID", "BusinessUnit_ID", "Asset_Name"]
].copy()

asset_location_bridge["Location_ID"] = (
    asset_location_bridge["Asset_ID"]
    .map(asset_location_map)
)

asset_location_bridge = asset_location_bridge.merge(
    dim_location[
        ["Location_ID", "Location_Name", "State",
         "Operational_Environment"]
    ],
    on="Location_ID",
    how="left"
)

asset_location_bridge

,Asset_ID,BusinessUnit_ID,Asset_Name,Location_ID,Location_Name,State,Operational_Environment
0,AST001,BU001,Offshore Platform A,LOC001,Bonny Offshore & Coastal Operations,Rivers,Offshore / Coastal
1,AST002,BU001,Offshore Platform B,LOC001,Bonny Offshore & Coastal Operations,Rivers,Offshore / Coastal
2,AST003,BU001,Offshore Platform C,LOC004,Brass–Bayelsa Operations Area,Bayelsa,Onshore / Offshore
3,AST004,BU002,Pipeline Network Alpha,LOC003,Warri–Escravos Operations Area,Delta,Onshore / Offshore
4,AST005,BU002,Pipeline Network Bravo,LOC004,Brass–Bayelsa Operations Area,Bayelsa,Onshore / Offshore
5,AST006,BU002,Gas Compression Station,LOC002,Port Harcourt Operations Base,Rivers,Onshore / Industrial
6,AST007,BU002,Gas Processing Plant,LOC002,Port Harcourt Operations Base,Rivers,Onshore / Industrial
7,AST008,BU003,Refinery Complex,LOC003,Warri–Escravos Operations Area,Delta,Onshore / Offshore
8,AST009,BU003,Fuel Distribution Terminal,LOC006,Lagos Corporate Headquarters,Lagos,Corporate Office
9,AST010,BU004,LNG Export Terminal,LOC001,Bonny Offshore & Coastal Operations,Rivers,Offshore / Coastal
10,AST011,BU005,Solar Farm North,LOC008,Renewable Energy Operations Base,Kaduna,Renewable Energy
11,AST012,BU005,Solar Farm South,LOC008,Renewable Energy Operations Base,Kaduna,Renewable Energy
12,AST013,BU005,Wind Farm,LOC008,Renewable Energy Operations Base,Kaduna,Renewable Energy

In [129]:
print("Rows:", len(asset_location_bridge))
print("Missing Location IDs:",
      asset_location_bridge["Location_ID"].isna().sum())

Rows: 13
Missing Location IDs: 0

In [130]:
print("Current lookup tables:")
print([x for x in globals() if x.startswith("dim_")])

Current lookup tables:
['dim_date', 'dim_location', 'dim_business_unit', 'dim_department', 'dim_asset', 'dim_job_role', 'dim_incident_type', 'dim_hazard', 'dim_shift', 'dim_contractor', 'dim_employee']

In [131]:
print("Business Units:", len(dim_business_unit))
print("Departments:", len(dim_department))
print("Assets:", len(dim_asset))
print("Incident Types:", len(dim_incident_type))
print("Hazards:", len(dim_hazard))
print("Shifts:", len(dim_shift))
print("Contractors:", len(dim_contractor))
print("Employees:", len(dim_employee))
print("Dates:", len(dim_date))
print("Locations:", len(dim_location))

Business Units: 5
Departments: 7
Assets: 13
Incident Types: 10
Hazards: 12
Shifts: 3
Contractors: 8
Employees: 4000
Dates: 1673
Locations: 8

In [132]:
# ============================================================
# FACT_HSE_INCIDENT
# INCIDENT POPULATION
# ============================================================

num_incidents = 10_000

np.random.seed(42)

incident_ids = [
    f"INC{str(i).zfill(6)}"
    for i in range(1, num_incidents + 1)
]

incident_ids[:10]

['INC000001',
 'INC000002',
 'INC000003',
 'INC000004',
 'INC000005',
 'INC000006',
 'INC000007',
 'INC000008',
 'INC000009',
 'INC000010']

In [133]:
print("Job Roles:", len(dim_job_role))
print("Unique Job Roles:", dim_job_role["Job_Role"].nunique())
print("Missing Values:", dim_job_role.isna().sum().sum())

Job Roles: 35
Unique Job Roles: 35
Missing Values: 0

In [134]:
# ============================================================
# PHASE 4A — FACT_HSE_EXPOSURE
# MONTHLY WORKFORCE EXPOSURE
# ============================================================

import numpy as np
import pandas as pd

np.random.seed(42)

# Monthly exposure period
exposure_months = pd.date_range(
    start="2022-01-01",
    end="2026-07-31",
    freq="MS"
)

print("Number of months:", len(exposure_months))
print("Start:", exposure_months.min())
print("End:", exposure_months.max())

Number of months: 55
Start: 2022-01-01 00:00:00
End: 2026-07-01 00:00:00

In [135]:
# ============================================================
# EMPLOYEE × MONTH EXPOSURE FRAME
# ============================================================

employee_exposure = pd.MultiIndex.from_product(
    [
        dim_employee["Employee_ID"],
        exposure_months
    ],
    names=["Employee_ID", "Exposure_Month"]
).to_frame(index=False)

print("Exposure records:",
      len(employee_exposure))

print(employee_exposure.head())

Exposure records: 220000
  Employee_ID Exposure_Month
0    EMP00001     2022-01-01
1    EMP00001     2022-02-01
2    EMP00001     2022-03-01
3    EMP00001     2022-04-01
4    EMP00001     2022-05-01

In [136]:
employee_attributes = dim_employee[
    [
        "Employee_ID",
        "BusinessUnit_ID",
        "Department_ID",
        "Asset_ID",
        "Shift_ID",
        "Employment_Type",
        "Employment_Status"
    ]
].copy()

fact_hse_exposure = employee_exposure.merge(
    employee_attributes,
    on="Employee_ID",
    how="left"
)

print("Rows:", len(fact_hse_exposure))
print("Columns:", len(fact_hse_exposure.columns))

Rows: 220000
Columns: 8

In [137]:
# ============================================================
# MONTHLY EXPOSURE HOURS
# ============================================================

# Base monthly working hours
base_hours = 173.8

# Small monthly variation
monthly_variation = np.random.normal(
    loc=0,
    scale=8,
    size=len(fact_hse_exposure)
)

fact_hse_exposure["Exposure_Hours"] = (
    base_hours + monthly_variation
)

# Prevent unrealistic values
fact_hse_exposure["Exposure_Hours"] = (
    fact_hse_exposure["Exposure_Hours"]
    .clip(lower=0)
)

In [138]:
# Employees on leave have reduced/no exposure
fact_hse_exposure.loc[
    fact_hse_exposure["Employment_Status"] == "Leave",
    "Exposure_Hours"
] *= np.random.uniform(
    0.00,
    0.35,
    size=(
        fact_hse_exposure["Employment_Status"] == "Leave"
    ).sum()
)

# Resigned employees should not continue accumulating exposure
fact_hse_exposure.loc[
    fact_hse_exposure["Employment_Status"] == "Resigned",
    "Exposure_Hours"
] = 0

In [139]:
department_exposure_factor = {

    "DEP001": 1.10,  # Operations
    "DEP002": 0.95,  # Engineering
    "DEP003": 1.05,  # Maintenance
    "DEP004": 0.90,  # HSE
    "DEP005": 0.85,  # Logistics
    "DEP006": 0.70,  # Finance
    "DEP007": 0.65   # HR
}

fact_hse_exposure["Exposure_Factor"] = (
    fact_hse_exposure["Department_ID"]
    .map(department_exposure_factor)
)

fact_hse_exposure["Exposure_Hours"] *= (
    fact_hse_exposure["Exposure_Factor"]
)

In [140]:
shift_factor = {

    "S001": 1.00,  # Day
    "S002": 0.95,  # Night
    "S003": 1.05   # Rotational
}

fact_hse_exposure["Shift_Factor"] = (
    fact_hse_exposure["Shift_ID"]
    .map(shift_factor)
)

fact_hse_exposure["Exposure_Hours"] *= (
    fact_hse_exposure["Shift_Factor"]
)

fact_hse_exposure["Exposure_Hours"] = (
    fact_hse_exposure["Exposure_Hours"].round(2)
)

In [141]:
fact_hse_exposure.insert(
    0,
    "Exposure_ID",
    [
        f"EXP{str(i).zfill(7)}"
        for i in range(
            1,
            len(fact_hse_exposure) + 1
        )
    ]
)

In [142]:
fact_hse_exposure = fact_hse_exposure[
    [
        "Exposure_ID",
        "Employee_ID",
        "Exposure_Month",
        "BusinessUnit_ID",
        "Department_ID",
        "Asset_ID",
        "Shift_ID",
        "Employment_Type",
        "Employment_Status",
        "Exposure_Hours"
    ]
]

In [143]:
# ============================================================
# ADD DEPARTMENT EXPOSURE FACTOR
# ============================================================

department_exposure_factor = {
    "DEP001": 1.10,  # Operations
    "DEP002": 0.95,  # Engineering
    "DEP003": 1.05,  # Maintenance
    "DEP004": 0.90,  # HSE
    "DEP005": 0.85,  # Logistics
    "DEP006": 0.70,  # Finance
    "DEP007": 0.65   # HR
}

fact_hse_exposure["Exposure_Factor"] = (
    fact_hse_exposure["Department_ID"]
    .map(department_exposure_factor)
)

print(
    fact_hse_exposure["Exposure_Factor"]
    .value_counts(dropna=False)
)

print(
    "Missing Exposure Factors:",
    fact_hse_exposure["Exposure_Factor"].isna().sum()
)

Exposure_Factor
1.10    93500
0.95    38500
1.05    30250
0.90    19250
0.85    16500
0.65    11000
0.70    11000
Name: count, dtype: int64
Missing Exposure Factors: 0

In [144]:
print(fact_hse_exposure[
    ["Employee_ID", "Department_ID", "Exposure_Factor"]
].head(25))

   Employee_ID Department_ID  Exposure_Factor
0     EMP00001        DEP002             0.95
1     EMP00001        DEP002             0.95
2     EMP00001        DEP002             0.95
3     EMP00001        DEP002             0.95
4     EMP00001        DEP002             0.95
5     EMP00001        DEP002             0.95
6     EMP00001        DEP002             0.95
7     EMP00001        DEP002             0.95
8     EMP00001        DEP002             0.95
9     EMP00001        DEP002             0.95
10    EMP00001        DEP002             0.95
11    EMP00001        DEP002             0.95
12    EMP00001        DEP002             0.95
13    EMP00001        DEP002             0.95
14    EMP00001        DEP002             0.95
15    EMP00001        DEP002             0.95
16    EMP00001        DEP002             0.95
17    EMP00001        DEP002             0.95
18    EMP00001        DEP002             0.95
19    EMP00001        DEP002             0.95
20    EMP00001        DEP002             0.95
21    EMP00001        DEP002             0.95
22    EMP00001        DEP002             0.95
23    EMP00001        DEP002             0.95
24    EMP00001        DEP002             0.95

In [145]:
# ============================================================
# REBUILD EXPOSURE HOURS
# ============================================================

np.random.seed(42)

base_hours = 173.8

monthly_variation = np.random.normal(
    loc=0,
    scale=8,
    size=len(fact_hse_exposure)
)

fact_hse_exposure["Exposure_Hours"] = (
    base_hours + monthly_variation
)

# No negative working hours
fact_hse_exposure["Exposure_Hours"] = (
    fact_hse_exposure["Exposure_Hours"].clip(lower=0)
)

In [146]:
# Employees on leave have reduced exposure
leave_mask = (
    fact_hse_exposure["Employment_Status"] == "Leave"
)

fact_hse_exposure.loc[leave_mask, "Exposure_Hours"] *= (
    np.random.uniform(
        0.00,
        0.35,
        size=leave_mask.sum()
    )
)

# Resigned employees have no exposure after leaving
resigned_mask = (
    fact_hse_exposure["Employment_Status"] == "Resigned"
)

fact_hse_exposure.loc[
    resigned_mask,
    "Exposure_Hours"
] = 0

In [147]:
fact_hse_exposure["Exposure_Hours"] *= (
    fact_hse_exposure["Exposure_Factor"]
)

In [148]:
shift_factor = {
    "S001": 1.00,   # Day
    "S002": 0.95,   # Night
    "S003": 1.05    # Rotational
}

fact_hse_exposure["Shift_Factor"] = (
    fact_hse_exposure["Shift_ID"]
    .map(shift_factor)
)

print(
    "Missing Shift Factors:",
    fact_hse_exposure["Shift_Factor"].isna().sum()
)

Missing Shift Factors: 220000

In [149]:
fact_hse_exposure["Exposure_Hours"] *= (
    fact_hse_exposure["Shift_Factor"]
)

fact_hse_exposure["Exposure_Hours"] = (
    fact_hse_exposure["Exposure_Hours"].round(2)
)

In [150]:
print("========== EXPOSURE HOURS CHECK ==========")

print(
    "Total Exposure Hours:",
    round(
        fact_hse_exposure["Exposure_Hours"].sum(),
        2
    )
)

print(
    "Average Monthly Exposure Hours:",
    round(
        fact_hse_exposure["Exposure_Hours"].mean(),
        2
    )
)

print(
    "Minimum Exposure Hours:",
    fact_hse_exposure["Exposure_Hours"].min()
)

print(
    "Maximum Exposure Hours:",
    fact_hse_exposure["Exposure_Hours"].max()
)

print(
    "Missing Exposure Hours:",
    fact_hse_exposure["Exposure_Hours"].isna().sum()
)

print(
    "Zero Exposure Hours:",
    (
        fact_hse_exposure["Exposure_Hours"] == 0
    ).sum()
)

========== EXPOSURE HOURS CHECK ==========
Total Exposure Hours: 0.0
Average Monthly Exposure Hours: nan
Minimum Exposure Hours: nan
Maximum Exposure Hours: nan
Missing Exposure Hours: 220000
Zero Exposure Hours: 0

In [151]:
print("========== FACT_HSE_EXPOSURE CHECK ==========")

print("Rows:", len(fact_hse_exposure))
print("Columns:", len(fact_hse_exposure.columns))

print(
    "Unique Employees:",
    fact_hse_exposure["Employee_ID"].nunique()
)

print(
    "Total Exposure Hours:",
    round(
        fact_hse_exposure["Exposure_Hours"].sum(),
        2
    )
)

print(
    "Average Monthly Exposure Hours:",
    round(
        fact_hse_exposure["Exposure_Hours"].mean(),
        2
    )
)

print(
    "Missing Values:",
    fact_hse_exposure.isna().sum().sum()
)

print(
    "Duplicate Exposure IDs:",
    fact_hse_exposure["Exposure_ID"].duplicated().sum()
)

========== FACT_HSE_EXPOSURE CHECK ==========
Rows: 220000
Columns: 12
Unique Employees: 4000
Total Exposure Hours: 0.0
Average Monthly Exposure Hours: nan
Missing Values: 440000
Duplicate Exposure IDs: 0

In [152]:
print(fact_hse_exposure[
    [
        "Employee_ID",
        "BusinessUnit_ID",
        "Department_ID",
        "Asset_ID",
        "Shift_ID",
        "Employment_Status"
    ]
].head(10))

  Employee_ID BusinessUnit_ID Department_ID Asset_ID Shift_ID  \
0    EMP00001           BU002        DEP002   AST006    SH001
1    EMP00001           BU002        DEP002   AST006    SH001
2    EMP00001           BU002        DEP002   AST006    SH001
3    EMP00001           BU002        DEP002   AST006    SH001
4    EMP00001           BU002        DEP002   AST006    SH001
5    EMP00001           BU002        DEP002   AST006    SH001
6    EMP00001           BU002        DEP002   AST006    SH001
7    EMP00001           BU002        DEP002   AST006    SH001
8    EMP00001           BU002        DEP002   AST006    SH001
9    EMP00001           BU002        DEP002   AST006    SH001

  Employment_Status
0            Active
1            Active
2            Active
3            Active
4            Active
5            Active
6            Active
7            Active
8            Active
9            Active

In [153]:
print("Missing Business Units:",
      fact_hse_exposure["BusinessUnit_ID"].isna().sum())

print("Missing Departments:",
      fact_hse_exposure["Department_ID"].isna().sum())

print("Missing Assets:",
      fact_hse_exposure["Asset_ID"].isna().sum())

print("Missing Shifts:",
      fact_hse_exposure["Shift_ID"].isna().sum())

print("Missing Employment Status:",
      fact_hse_exposure["Employment_Status"].isna().sum())

Missing Business Units: 0
Missing Departments: 0
Missing Assets: 0
Missing Shifts: 0
Missing Employment Status: 0

In [154]:
print(dim_employee[
    [
        "Employee_ID",
        "BusinessUnit_ID",
        "Department_ID",
        "Asset_ID",
        "Shift_ID",
        "Employment_Status"
    ]
].head(10))

  Employee_ID BusinessUnit_ID Department_ID Asset_ID Shift_ID  \
0    EMP00001           BU002        DEP002   AST006    SH001
1    EMP00002           BU001        DEP002   AST001    SH002
2    EMP00003           BU004        DEP004   AST010    SH001
3    EMP00004           BU004        DEP005   AST010    SH001
4    EMP00005           BU003        DEP001   AST008    SH001
5    EMP00006           BU003        DEP007   AST008    SH001
6    EMP00007           BU003        DEP007   AST009    SH001
7    EMP00008           BU003        DEP001   AST008    SH001
8    EMP00009           BU005        DEP004   AST011    SH001
9    EMP00010           BU003        DEP003   AST008    SH002

  Employment_Status
0            Active
1            Active
2            Active
3            Active
4            Active
5            Active
6            Active
7            Active
8            Active
9            Active

In [155]:
print(dim_employee[
    [
        "BusinessUnit_ID",
        "Department_ID",
        "Asset_ID",
        "Shift_ID",
        "Employment_Status"
    ]
].isna().sum())

BusinessUnit_ID      0
Department_ID        0
Asset_ID             0
Shift_ID             0
Employment_Status    0
dtype: int64

In [156]:
print("========== EXPOSURE FACTOR CHECK ==========")

print(
    fact_hse_exposure["Department_ID"]
    .value_counts()
    .sort_index()
)

print("\nExposure Factor:")
print(
    fact_hse_exposure["Exposure_Factor"]
    .value_counts(dropna=False)
)

print("\nMissing Exposure Factor:",
      fact_hse_exposure["Exposure_Factor"].isna().sum())

========== EXPOSURE FACTOR CHECK ==========
Department_ID
DEP001    93500
DEP002    38500
DEP003    30250
DEP004    19250
DEP005    16500
DEP006    11000
DEP007    11000
Name: count, dtype: int64

Exposure Factor:
Exposure_Factor
1.10    93500
0.95    38500
1.05    30250
0.90    19250
0.85    16500
0.65    11000
0.70    11000
Name: count, dtype: int64

Missing Exposure Factor: 0

In [157]:
print("========== EXPOSURE HOURS CHECK ==========")

print(
    fact_hse_exposure["Exposure_Hours"].head(10)
)

print(
    "Missing Exposure Hours:",
    fact_hse_exposure["Exposure_Hours"].isna().sum()
)

print(
    "Zero Exposure Hours:",
    (fact_hse_exposure["Exposure_Hours"] == 0).sum()
)

========== EXPOSURE HOURS CHECK ==========
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: Exposure_Hours, dtype: float64
Missing Exposure Hours: 220000
Zero Exposure Hours: 0

In [158]:
print("========== FACTOR DIAGNOSTIC ==========")

print("Exposure Factor missing:",
      fact_hse_exposure["Exposure_Factor"].isna().sum())

print("Shift Factor missing:",
      fact_hse_exposure["Shift_Factor"].isna().sum())

print("\nShift IDs:")
print(fact_hse_exposure["Shift_ID"].value_counts(dropna=False))

print("\nShift Factors:")
print(fact_hse_exposure["Shift_Factor"].value_counts(dropna=False))

print("\nEmployment Status:")
print(
    fact_hse_exposure["Employment_Status"]
    .value_counts(dropna=False)
)

========== FACTOR DIAGNOSTIC ==========
Exposure Factor missing: 0
Shift Factor missing: 220000

Shift IDs:
Shift_ID
SH001    147620
SH002     63195
SH003      9185
Name: count, dtype: int64

Shift Factors:
Shift_Factor
NaN    220000
Name: count, dtype: int64

Employment Status:
Employment_Status
Active       213895
Leave          4015
Suspended      2090
Name: count, dtype: int64

In [159]:
# ============================================================
# FIX SHIFT EXPOSURE FACTOR
# ============================================================

shift_factor = {
    "SH001": 1.00,   # Day
    "SH002": 0.95,   # Night
    "SH003": 1.05    # Rotational
}

fact_hse_exposure["Shift_Factor"] = (
    fact_hse_exposure["Shift_ID"]
    .map(shift_factor)
)

print(
    "Missing Shift Factors:",
    fact_hse_exposure["Shift_Factor"].isna().sum()
)

Missing Shift Factors: 0

In [160]:
# ============================================================
# REBUILD EXPOSURE HOURS FROM SCRATCH
# ============================================================

np.random.seed(42)

base_hours = 173.8

monthly_variation = np.random.normal(
    loc=0,
    scale=8,
    size=len(fact_hse_exposure)
)

fact_hse_exposure["Exposure_Hours"] = (
    base_hours + monthly_variation
)

# Prevent negative exposure hours
fact_hse_exposure["Exposure_Hours"] = (
    fact_hse_exposure["Exposure_Hours"].apply(
        lambda x: max(x, 0)
    )
)

print(
    fact_hse_exposure["Exposure_Hours"].head()
)

0    177.773713
1    172.693886
2    178.981508
3    185.984239
4    171.926773
Name: Exposure_Hours, dtype: float64

In [161]:
# ============================================================
# APPLY EMPLOYMENT STATUS
# ============================================================

leave_mask = (
    fact_hse_exposure["Employment_Status"] == "Leave"
)

fact_hse_exposure.loc[leave_mask, "Exposure_Hours"] *= (
    np.random.uniform(
        0.00,
        0.35,
        size=leave_mask.sum()
    )
)

suspended_mask = (
    fact_hse_exposure["Employment_Status"] == "Suspended"
)

fact_hse_exposure.loc[
    suspended_mask,
    "Exposure_Hours"
] = 0

In [162]:
fact_hse_exposure["Exposure_Hours"] *= (
    fact_hse_exposure["Exposure_Factor"]
)

In [163]:
fact_hse_exposure["Exposure_Hours"] *= (
    fact_hse_exposure["Shift_Factor"]
)

fact_hse_exposure["Exposure_Hours"] = (
    fact_hse_exposure["Exposure_Hours"].round(2)
)

In [164]:
print("========== EXPOSURE HOURS CHECK ==========")

print("Total Exposure Hours:",
      round(fact_hse_exposure["Exposure_Hours"].sum(), 2))

print("Average Monthly Exposure Hours:",
      round(fact_hse_exposure["Exposure_Hours"].mean(), 2))

print("Minimum Exposure Hours:",
      fact_hse_exposure["Exposure_Hours"].min())

print("Maximum Exposure Hours:",
      fact_hse_exposure["Exposure_Hours"].max())

print("Missing Exposure Hours:",
      fact_hse_exposure["Exposure_Hours"].isna().sum())

print("Zero Exposure Hours:",
      (fact_hse_exposure["Exposure_Hours"] == 0).sum())

========== EXPOSURE HOURS CHECK ==========
Total Exposure Hours: 36371332.71
Average Monthly Exposure Hours: 165.32
Minimum Exposure Hours: 0.0
Maximum Exposure Hours: 235.54
Missing Exposure Hours: 0
Zero Exposure Hours: 2090

In [165]:
# ============================================================
# ADD DATE_ID TO FACT_HSE_EXPOSURE
# ============================================================

fact_hse_exposure["Date_ID"] = (
    fact_hse_exposure["Exposure_Month"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

# Move Date_ID beside Exposure_Month
cols = fact_hse_exposure.columns.tolist()

cols.remove("Date_ID")

month_position = cols.index("Exposure_Month") + 1

cols.insert(month_position, "Date_ID")

fact_hse_exposure = fact_hse_exposure[cols]

print(fact_hse_exposure.head())

  Exposure_ID Employee_ID Exposure_Month   Date_ID BusinessUnit_ID  \
0  EXP0000001    EMP00001     2022-01-01  20220101           BU002
1  EXP0000002    EMP00001     2022-02-01  20220201           BU002
2  EXP0000003    EMP00001     2022-03-01  20220301           BU002
3  EXP0000004    EMP00001     2022-04-01  20220401           BU002
4  EXP0000005    EMP00001     2022-05-01  20220501           BU002

  Department_ID Asset_ID Shift_ID Employment_Type Employment_Status  \
0        DEP002   AST006    SH001       Permanent            Active
1        DEP002   AST006    SH001       Permanent            Active
2        DEP002   AST006    SH001       Permanent            Active
3        DEP002   AST006    SH001       Permanent            Active
4        DEP002   AST006    SH001       Permanent            Active

   Exposure_Hours  Exposure_Factor  Shift_Factor
0          168.89             0.95           1.0
1          164.06             0.95           1.0
2          170.03             0.95           1.0
3          176.69             0.95           1.0
4          163.33             0.95           1.0

In [166]:
print(
    "Missing Date_ID:",
    fact_hse_exposure["Date_ID"].isna().sum()
)

print(
    "Unique Date_IDs:",
    fact_hse_exposure["Date_ID"].nunique()
)

Missing Date_ID: 0
Unique Date_IDs: 55

In [167]:
print (dim_incident_type)

  Incident_Type_ID           Incident_Type Incident_Category
0            IT001               Near Miss         Near Miss
1            IT002          First Aid Case  Injury / Illness
2            IT003  Medical Treatment Case  Injury / Illness
3            IT004    Restricted Work Case  Injury / Illness
4            IT005        Lost Time Injury  Injury / Illness
5            IT006                Fatality          Fatality
6            IT007         Property Damage  Property / Asset
7            IT008  Environmental Incident     Environmental
8            IT009        Fire / Explosion    Process / Fire
9            IT010    Process Safety Event    Process Safety

In [168]:
print(dim_hazard)

   Hazard_ID                  Hazard_Name Hazard_Category
0      HZ001         Slips, Trips & Falls        Physical
1      HZ002            Working at Height        Physical
2      HZ003               Confined Space        Physical
3      HZ004            Electrical Energy          Energy
4      HZ005     Pressure / Stored Energy          Energy
5      HZ006             Fire / Explosion  Process Safety
6      HZ007          Hazardous Chemicals        Chemical
7      HZ008          Hydrocarbon Release  Process Safety
8      HZ009  Lifting & Material Handling        Physical
9      HZ010   Vehicle / Mobile Equipment  Transportation
10     HZ011              Dropped Objects        Physical
11     HZ012  Ergonomic / Manual Handling       Ergonomic

In [169]:
print(dim_contractor)

  Contractor_ID                 Contractor_Name Contractor_Category  \
0        CON001    Keystra Engineering Services         Engineering
1        CON002  Keystra Industrial Maintenance         Maintenance
2        CON003      Keystra Logistics Services           Logistics
3        CON004         Keystra Marine Services              Marine
4        CON005   Keystra Construction Services        Construction
5        CON006  Keystra Environmental Services       Environmental
6        CON007       Keystra Security Services            Security
7        CON008      Keystra Technical Services  Technical Services

            Contractor_Type
0      Technical Contractor
1      Technical Contractor
2        Support Contractor
3         Marine Contractor
4   Construction Contractor
5  Environmental Contractor
6       Security Contractor
7      Technical Contractor

In [170]:
print(dim_shift)

  Shift_ID       Shift
0    SH001         Day
1    SH002       Night
2    SH003  Rotational

In [171]:
print(dim_location)

  Location_ID                            Location_Name      State  Country  \
0      LOC001      Bonny Offshore & Coastal Operations     Rivers  Nigeria
1      LOC002            Port Harcourt Operations Base     Rivers  Nigeria
2      LOC003           Warri–Escravos Operations Area      Delta  Nigeria
3      LOC004            Brass–Bayelsa Operations Area    Bayelsa  Nigeria
4      LOC005            Eket–Qua Iboe Operations Area  Akwa Ibom  Nigeria
5      LOC006             Lagos Corporate Headquarters      Lagos  Nigeria
6      LOC007  Abuja Corporate & Administrative Office        FCT  Nigeria
7      LOC008         Renewable Energy Operations Base     Kaduna  Nigeria

  Operational_Environment
0      Offshore / Coastal
1    Onshore / Industrial
2      Onshore / Offshore
3      Onshore / Offshore
4      Onshore / Offshore
5        Corporate Office
6        Corporate Office
7        Renewable Energy

In [172]:
print(dim_asset)

   Asset_ID BusinessUnit_ID                  Asset_Name
0    AST001           BU001         Offshore Platform A
1    AST002           BU001         Offshore Platform B
2    AST003           BU001         Offshore Platform C
3    AST004           BU002      Pipeline Network Alpha
4    AST005           BU002      Pipeline Network Bravo
5    AST006           BU002     Gas Compression Station
6    AST007           BU002        Gas Processing Plant
7    AST008           BU003            Refinery Complex
8    AST009           BU003  Fuel Distribution Terminal
9    AST010           BU004         LNG Export Terminal
10   AST011           BU005            Solar Farm North
11   AST012           BU005            Solar Farm South
12   AST013           BU005                   Wind Farm

In [173]:
# ============================================================
# FACT_HSE_INCIDENT — STRUCTURE
# ============================================================

incident_columns = [
    "Incident_ID",
    "Date_ID",
    "Employee_ID",
    "BusinessUnit_ID",
    "Department_ID",
    "Asset_ID",
    "Location_ID",
    "Shift_ID",
    "Contractor_ID",
    "Incident_Type_ID",
    "Hazard_ID",
    "Incident_Date",
    "Recordable_Flag",
    "LTI_Flag",
    "Fatality_Flag",
    "Near_Miss_Flag",
    "Lost_Days",
    "Downtime_Hours",
    "Direct_Cost",
    "Indirect_Cost",
    "Total_Cost"
]

fact_hse_incident = pd.DataFrame(
    columns=incident_columns
)

print("Columns:", len(fact_hse_incident.columns))
print(fact_hse_incident.columns.tolist())

Columns: 21
['Incident_ID', 'Date_ID', 'Employee_ID', 'BusinessUnit_ID', 'Department_ID', 'Asset_ID', 'Location_ID', 'Shift_ID', 'Contractor_ID', 'Incident_Type_ID', 'Hazard_ID', 'Incident_Date', 'Recordable_Flag', 'LTI_Flag', 'Fatality_Flag', 'Near_Miss_Flag', 'Lost_Days', 'Downtime_Hours', 'Direct_Cost', 'Indirect_Cost', 'Total_Cost']

In [174]:
# ============================================================
# STEP 3 — ACTIVE EMPLOYEE POOL
# ============================================================

active_employees = dim_employee[
    dim_employee["Employment_Status"] == "Active"
].copy()

print("Total Employees:", len(dim_employee))
print("Active Employees:", len(active_employees))
print("Active Employee %:",
      round(
          len(active_employees) / len(dim_employee) * 100,
          2
      )
)

print(
    active_employees[
        [
            "Employee_ID",
            "BusinessUnit_ID",
            "Department_ID",
            "Asset_ID",
            "Shift_ID",
            "Work_Location"
        ]
    ].head(10)
)

Total Employees: 4000
Active Employees: 3889
Active Employee %: 97.22
  Employee_ID BusinessUnit_ID Department_ID Asset_ID Shift_ID  \
0    EMP00001           BU002        DEP002   AST006    SH001
1    EMP00002           BU001        DEP002   AST001    SH002
2    EMP00003           BU004        DEP004   AST010    SH001
3    EMP00004           BU004        DEP005   AST010    SH001
4    EMP00005           BU003        DEP001   AST008    SH001
5    EMP00006           BU003        DEP007   AST008    SH001
6    EMP00007           BU003        DEP007   AST009    SH001
7    EMP00008           BU003        DEP001   AST008    SH001
8    EMP00009           BU005        DEP004   AST011    SH001
9    EMP00010           BU003        DEP003   AST008    SH002

                Work_Location
0     Gas Compression Station
1         Offshore Platform A
2         LNG Export Terminal
3         LNG Export Terminal
4            Refinery Complex
5            Refinery Complex
6  Fuel Distribution Terminal
7            Refinery Complex
8            Solar Farm North
9            Refinery Complex

In [175]:
# ============================================================
# STEP 4 — INCIDENT EMPLOYEE POOL
# ============================================================

incident_employee_pool = active_employees[
    [
        "Employee_ID",
        "BusinessUnit_ID",
        "Department_ID",
        "Asset_ID",
        "Shift_ID",
        "Work_Location"
    ]
].copy()

print(
    "Employees available for incident assignment:",
    len(incident_employee_pool)
)

incident_employee_pool.head()

Employees available for incident assignment: 3889

,Employee_ID,BusinessUnit_ID,Department_ID,Asset_ID,Shift_ID,Work_Location
0,EMP00001,BU002,DEP002,AST006,SH001,Gas Compression Station
1,EMP00002,BU001,DEP002,AST001,SH002,Offshore Platform A
2,EMP00003,BU004,DEP004,AST010,SH001,LNG Export Terminal
3,EMP00004,BU004,DEP005,AST010,SH001,LNG Export Terminal
4,EMP00005,BU003,DEP001,AST008,SH001,Refinery Complex

In [176]:
# ============================================================
# FACT_HSE_INCIDENT
# STEP 5 — DEPARTMENT INCIDENT RISK
# ============================================================

department_incident_factor = {
    "DEP001": 1.40,  # Operations
    "DEP002": 0.90,  # Engineering
    "DEP003": 1.25,  # Maintenance
    "DEP004": 0.75,  # HSE
    "DEP005": 1.00,  # Logistics
    "DEP006": 0.35,  # Finance
    "DEP007": 0.30   # HR
}

incident_employee_pool["Department_Risk_Factor"] = (
    incident_employee_pool["Department_ID"]
    .map(department_incident_factor)
)

print(
    "Missing Department Risk Factors:",
    incident_employee_pool["Department_Risk_Factor"].isna().sum()
)

Missing Department Risk Factors: 0

In [177]:
# ============================================================
# STEP 6 — ASSET INCIDENT RISK
# ============================================================

asset_incident_factor = {
    "AST001": 1.35,  # Offshore Platform A
    "AST002": 1.35,  # Offshore Platform B
    "AST003": 1.35,  # Offshore Platform C

    "AST004": 1.15,  # Pipeline Network Alpha
    "AST005": 1.15,  # Pipeline Network Bravo
    "AST006": 1.30,  # Gas Compression Station
    "AST007": 1.25,  # Gas Processing Plant

    "AST008": 1.30,  # Refinery Complex
    "AST009": 1.05,  # Fuel Distribution Terminal

    "AST010": 1.30,  # LNG Export Terminal

    "AST011": 0.80,  # Solar Farm North
    "AST012": 0.80,  # Solar Farm South
    "AST013": 0.85   # Wind Farm
}

incident_employee_pool["Asset_Risk_Factor"] = (
    incident_employee_pool["Asset_ID"]
    .map(asset_incident_factor)
)

print(
    "Missing Asset Risk Factors:",
    incident_employee_pool["Asset_Risk_Factor"].isna().sum()
)

Missing Asset Risk Factors: 0

In [178]:
# ============================================================
# STEP 7 — SHIFT INCIDENT RISK
# ============================================================

shift_incident_factor = {
    "SH001": 1.00,  # Day
    "SH002": 1.10,  # Night
    "SH003": 1.15   # Rotational
}

incident_employee_pool["Shift_Risk_Factor"] = (
    incident_employee_pool["Shift_ID"]
    .map(shift_incident_factor)
)

print(
    "Missing Shift Risk Factors:",
    incident_employee_pool["Shift_Risk_Factor"].isna().sum()
)

Missing Shift Risk Factors: 0

In [179]:
# ============================================================
# STEP 8 — COMBINED INCIDENT PROPENSITY
# ============================================================

incident_employee_pool["Incident_Propensity"] = (
    incident_employee_pool["Department_Risk_Factor"]
    * incident_employee_pool["Asset_Risk_Factor"]
    * incident_employee_pool["Shift_Risk_Factor"]
)

print(
    incident_employee_pool[
        [
            "Employee_ID",
            "Department_ID",
            "Asset_ID",
            "Shift_ID",
            "Incident_Propensity"
        ]
    ].head(20)
)

   Employee_ID Department_ID Asset_ID Shift_ID  Incident_Propensity
0     EMP00001        DEP002   AST006    SH001              1.17000
1     EMP00002        DEP002   AST001    SH002              1.33650
2     EMP00003        DEP004   AST010    SH001              0.97500
3     EMP00004        DEP005   AST010    SH001              1.30000
4     EMP00005        DEP001   AST008    SH001              1.82000
5     EMP00006        DEP007   AST008    SH001              0.39000
6     EMP00007        DEP007   AST009    SH001              0.31500
7     EMP00008        DEP001   AST008    SH001              1.82000
8     EMP00009        DEP004   AST011    SH001              0.60000
9     EMP00010        DEP003   AST008    SH002              1.78750
10    EMP00011        DEP004   AST009    SH001              0.78750
11    EMP00012        DEP001   AST008    SH002              2.00200
12    EMP00013        DEP002   AST013    SH001              0.76500
13    EMP00014        DEP001   AST008    SH003              2.09300
14    EMP00015        DEP003   AST003    SH002              1.85625
15    EMP00016        DEP004   AST001    SH001              1.01250
16    EMP00017        DEP002   AST007    SH001              1.12500
17    EMP00018        DEP003   AST013    SH001              1.06250
18    EMP00019        DEP004   AST009    SH001              0.78750
19    EMP00020        DEP001   AST004    SH002              1.77100

In [180]:
print("========== INCIDENT PROPENSITY CHECK ==========")

print(
    incident_employee_pool["Incident_Propensity"].describe()
)

print("\nBy Department:")

print(
    incident_employee_pool
    .groupby("Department_ID")["Incident_Propensity"]
    .mean()
    .sort_values(ascending=False)
)

========== INCIDENT PROPENSITY CHECK ==========
count    3889.000000
mean        1.401145
std         0.510184
min         0.240000
25%         1.050000
50%         1.430000
75%         1.856250
max         2.173500
Name: Incident_Propensity, dtype: float64

By Department:
Department_ID
DEP001    1.820315
DEP003    1.576091
DEP005    1.239759
DEP002    1.120877
DEP004    0.939320
DEP006    0.427462
DEP007    0.366340
Name: Incident_Propensity, dtype: float64

In [181]:
print("Total Dim_Employee:", len(dim_employee))

print("\nEmployment Status:")
print(dim_employee["Employment_Status"].value_counts(dropna=False))

print("\nIncident Employee Pool:", len(incident_employee_pool))

print("\nMissing Propensity:",
      incident_employee_pool["Incident_Propensity"].isna().sum())

Total Dim_Employee: 4000

Employment Status:
Employment_Status
Active       3889
Leave          73
Suspended      38
Name: count, dtype: int64

Incident Employee Pool: 3889

Missing Propensity: 0

In [182]:
print(
    incident_employee_pool[
        incident_employee_pool["Incident_Propensity"].isna()
    ][
        [
            "Employee_ID",
            "BusinessUnit_ID",
            "Department_ID",
            "Asset_ID",
            "Shift_ID",
            "Work_Location",
            "Department_Risk_Factor",
            "Asset_Risk_Factor",
            "Shift_Risk_Factor"
        ]
    ].head(20)
)

Empty DataFrame
Columns: [Employee_ID, BusinessUnit_ID, Department_ID, Asset_ID, Shift_ID, Work_Location, Department_Risk_Factor, Asset_Risk_Factor, Shift_Risk_Factor]
Index: []

In [183]:
# ============================================================
# STEP 9 — NORMALIZE INCIDENT PROPENSITY
# ============================================================

incident_employee_pool["Incident_Weight"] = (
    incident_employee_pool["Incident_Propensity"]
    / incident_employee_pool["Incident_Propensity"].sum()
)

print(
    "Total Incident Weight:",
    incident_employee_pool["Incident_Weight"].sum()
)

print(
    incident_employee_pool[
        [
            "Employee_ID",
            "Department_ID",
            "Asset_ID",
            "Incident_Propensity",
            "Incident_Weight"
        ]
    ].head(10)
)

Total Incident Weight: 1.0
  Employee_ID Department_ID Asset_ID  Incident_Propensity  Incident_Weight
0    EMP00001        DEP002   AST006               1.1700         0.000215
1    EMP00002        DEP002   AST001               1.3365         0.000245
2    EMP00003        DEP004   AST010               0.9750         0.000179
3    EMP00004        DEP005   AST010               1.3000         0.000239
4    EMP00005        DEP001   AST008               1.8200         0.000334
5    EMP00006        DEP007   AST008               0.3900         0.000072
6    EMP00007        DEP007   AST009               0.3150         0.000058
7    EMP00008        DEP001   AST008               1.8200         0.000334
8    EMP00009        DEP004   AST011               0.6000         0.000110
9    EMP00010        DEP003   AST008               1.7875         0.000328

In [184]:
department_weight_check = (
    incident_employee_pool
    .groupby("Department_ID")["Incident_Weight"]
    .sum()
    .sort_values(ascending=False)
)

print(department_weight_check)

Department_ID
DEP001    0.552871
DEP003    0.154166
DEP002    0.139877
DEP005    0.065980
DEP004    0.058610
DEP006    0.015454
DEP007    0.013043
Name: Incident_Weight, dtype: float64

In [185]:
# ============================================================
# FACT_HSE_INCIDENT
# STEP 10 — DETERMINE INCIDENT POPULATION
# ============================================================

total_exposure_hours = fact_hse_exposure["Exposure_Hours"].sum()

# Baseline HSE event frequency
# Events per 200,000 exposure hours
baseline_event_rate = 35

expected_incidents = (
    total_exposure_hours / 200_000
) * baseline_event_rate

print("Total Exposure Hours:",
      round(total_exposure_hours, 2))

print("Baseline Event Rate:",
      baseline_event_rate,
      "events per 200,000 exposure hours")

print("Expected HSE Events:",
      round(expected_incidents))

Total Exposure Hours: 36371332.71
Baseline Event Rate: 35 events per 200,000 exposure hours
Expected HSE Events: 6365

In [186]:
# ============================================================
# STEP 11 — RISK ADJUSTMENT
# ============================================================

average_propensity = (
    incident_employee_pool["Incident_Propensity"].mean()
)

risk_adjustment = average_propensity / 1.40

adjusted_incidents = round(
    expected_incidents * risk_adjustment
)

print("Average Incident Propensity:",
      round(average_propensity, 4))

print("Risk Adjustment:",
      round(risk_adjustment, 4))

print("Adjusted Incident Population:",
      adjusted_incidents)

Average Incident Propensity: 1.4011
Risk Adjustment: 1.0008
Adjusted Incident Population: 6370

In [187]:
# ============================================================
# STEP 12 — GENERATE INCIDENT IDs
# ============================================================

num_incidents = adjusted_incidents

incident_ids = [
    f"INC{str(i).zfill(6)}"
    for i in range(1, num_incidents + 1)
]

print("Number of Incidents:", len(incident_ids))
print("First 10 IDs:", incident_ids[:10])
print("Last 10 IDs:", incident_ids[-10:])

Number of Incidents: 6370
First 10 IDs: ['INC000001', 'INC000002', 'INC000003', 'INC000004', 'INC000005', 'INC000006', 'INC000007', 'INC000008', 'INC000009', 'INC000010']
Last 10 IDs: ['INC006361', 'INC006362', 'INC006363', 'INC006364', 'INC006365', 'INC006366', 'INC006367', 'INC006368', 'INC006369', 'INC006370']

In [188]:
# ============================================================
# STEP 13 — SELECT INCIDENT EMPLOYEES
# ============================================================

np.random.seed(42)

selected_employees = np.random.choice(
    incident_employee_pool["Employee_ID"],
    size=num_incidents,
    replace=True,
    p=incident_employee_pool["Incident_Weight"]
)

print("Selected Employee Records:", len(selected_employees))
print("Unique Employees Involved:",
      len(set(selected_employees)))

Selected Employee Records: 6370
Unique Employees Involved: 2968

In [189]:
# ============================================================
# STEP 14 — INITIAL FACT_HSE_INCIDENT RECORDS
# ============================================================

fact_hse_incident = pd.DataFrame({
    "Incident_ID": incident_ids,
    "Employee_ID": selected_employees
})

print("Rows:", len(fact_hse_incident))
print("Columns:", len(fact_hse_incident.columns))

fact_hse_incident.head(10)

Rows: 6370
Columns: 2

  Incident_ID Employee_ID
0   INC000001    EMP01504
1   INC000002    EMP03810
2   INC000003    EMP02936
3   INC000004    EMP02391
4   INC000005    EMP00629
5   INC000006    EMP00629
6   INC000007    EMP00221
7   INC000008    EMP03476
8   INC000009    EMP02401
9   INC000010    EMP02842

In [190]:
# ============================================================
# STEP 15 — BRING EMPLOYEE ATTRIBUTES
# ============================================================

employee_attributes = incident_employee_pool[
    [
        "Employee_ID",
        "BusinessUnit_ID",
        "Department_ID",
        "Asset_ID",
        "Shift_ID",
        "Work_Location"
    ]
].copy()

fact_hse_incident = fact_hse_incident.merge(
    employee_attributes,
    on="Employee_ID",
    how="left"
)

print("Rows:", len(fact_hse_incident))
print("Columns:", len(fact_hse_incident.columns))

fact_hse_incident.head(10)

Rows: 6370
Columns: 7

,Incident_ID,Employee_ID,BusinessUnit_ID,Department_ID,Asset_ID,Shift_ID,Work_Location
0,INC000001,EMP01504,BU003,DEP002,AST008,SH001,Refinery Complex
1,INC000002,EMP03810,BU004,DEP001,AST010,SH002,LNG Export Terminal
2,INC000003,EMP02936,BU001,DEP001,AST002,SH001,Offshore Platform B
3,INC000004,EMP02391,BU001,DEP003,AST002,SH001,Offshore Platform B
4,INC000005,EMP00629,BU003,DEP001,AST009,SH001,Fuel Distribution Terminal
5,INC000006,EMP00629,BU003,DEP001,AST009,SH001,Fuel Distribution Terminal
6,INC000007,EMP00221,BU001,DEP001,AST002,SH001,Offshore Platform B
7,INC000008,EMP03476,BU001,DEP001,AST003,SH003,Offshore Platform C
8,INC000009,EMP02401,BU002,DEP001,AST007,SH001,Gas Processing Plant
9,INC000010,EMP02842,BU003,DEP001,AST008,SH002,Refinery Complex

In [191]:
# ============================================================
# INCIDENT EMPLOYEE RELATIONSHIP CHECK
# ============================================================

print("========== INCIDENT RELATIONSHIP CHECK ==========")

print(
    "Missing Employee IDs:",
    fact_hse_incident["Employee_ID"].isna().sum()
)

print(
    "Missing Business Units:",
    fact_hse_incident["BusinessUnit_ID"].isna().sum()
)

print(
    "Missing Departments:",
    fact_hse_incident["Department_ID"].isna().sum()
)

print(
    "Missing Assets:",
    fact_hse_incident["Asset_ID"].isna().sum()
)

print(
    "Missing Shifts:",
    fact_hse_incident["Shift_ID"].isna().sum()
)

print(
    "Missing Work Locations:",
    fact_hse_incident["Work_Location"].isna().sum()
)

========== INCIDENT RELATIONSHIP CHECK ==========
Missing Employee IDs: 0
Missing Business Units: 0
Missing Departments: 0
Missing Assets: 0
Missing Shifts: 0
Missing Work Locations: 0

In [192]:
# ============================================================
# STEP 16A — MONTHLY EXPOSURE PROFILE
# ============================================================

monthly_exposure = (
    fact_hse_exposure
    .groupby("Exposure_Month")["Exposure_Hours"]
    .sum()
    .reset_index()
)

monthly_exposure["Exposure_Weight"] = (
    monthly_exposure["Exposure_Hours"]
    / monthly_exposure["Exposure_Hours"].sum()
)

print(monthly_exposure.head(10))

print(
    "Total Exposure Weight:",
    monthly_exposure["Exposure_Weight"].sum()
)

  Exposure_Month  Exposure_Hours  Exposure_Weight
0     2022-01-01       660734.07         0.018166
1     2022-02-01       661327.04         0.018183
2     2022-03-01       661690.04         0.018193
3     2022-04-01       661196.77         0.018179
4     2022-05-01       660859.93         0.018170
5     2022-06-01       662098.36         0.018204
6     2022-07-01       661447.77         0.018186
7     2022-08-01       661406.16         0.018185
8     2022-09-01       660731.10         0.018166
9     2022-10-01       660899.53         0.018171
Total Exposure Weight: 0.9999999999999999

In [193]:
# ============================================================
# STEP 16B — SELECT INCIDENT MONTHS
# ============================================================

np.random.seed(42)

selected_months = np.random.choice(
    monthly_exposure["Exposure_Month"].values,
    size=num_incidents,
    replace=True,
    p=monthly_exposure["Exposure_Weight"].values
)

fact_hse_incident["Incident_Month"] = selected_months

print(
    fact_hse_incident["Incident_Month"].head(10)
)

0   2023-09-01
1   2026-05-01
2   2025-05-01
3   2024-09-01
4   2022-09-01
5   2022-09-01
6   2022-04-01
7   2025-12-01
8   2024-10-01
9   2025-03-01
Name: Incident_Month, dtype: datetime64[ns]

In [194]:
# ============================================================
# STEP 16C — GENERATE INCIDENT DATES
# ============================================================

fact_hse_incident["Incident_Date"] = (
    pd.to_datetime(fact_hse_incident["Incident_Month"])
    + pd.to_timedelta(
        np.random.randint(
            0,
            fact_hse_incident["Incident_Month"]
                .dt.days_in_month
        ),
        unit="D"
    )
)

fact_hse_incident["Incident_Date"] = (
    fact_hse_incident["Incident_Date"].dt.normalize()
)

print(
    fact_hse_incident[
        ["Incident_ID", "Incident_Month", "Incident_Date"]
    ].head(10)
)

  Incident_ID Incident_Month Incident_Date
0   INC000001     2023-09-01    2023-09-12
1   INC000002     2026-05-01    2026-05-05
2   INC000003     2025-05-01    2025-05-09
3   INC000004     2024-09-01    2024-09-23
4   INC000005     2022-09-01    2022-09-08
5   INC000006     2022-09-01    2022-09-16
6   INC000007     2022-04-01    2022-04-14
7   INC000008     2025-12-01    2025-12-27
8   INC000009     2024-10-01    2024-10-25
9   INC000010     2025-03-01    2025-03-13

In [195]:
print("========== INCIDENT DATE CHECK ==========")

print(
    "Earliest Incident:",
    fact_hse_incident["Incident_Date"].min()
)

print(
    "Latest Incident:",
    fact_hse_incident["Incident_Date"].max()
)

print(
    "Missing Incident Dates:",
    fact_hse_incident["Incident_Date"].isna().sum()
)

========== INCIDENT DATE CHECK ==========
Earliest Incident: 2022-01-01 00:00:00
Latest Incident: 2026-07-31 00:00:00
Missing Incident Dates: 0

In [196]:
# ============================================================
# STEP 17 — CREATE DATE_ID
# ============================================================

fact_hse_incident["Date_ID"] = (
    fact_hse_incident["Incident_Date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

print(
    fact_hse_incident[
        [
            "Incident_ID",
            "Incident_Date",
            "Date_ID"
        ]
    ].head(10)
)

  Incident_ID Incident_Date   Date_ID
0   INC000001    2023-09-12  20230912
1   INC000002    2026-05-05  20260505
2   INC000003    2025-05-09  20250509
3   INC000004    2024-09-23  20240923
4   INC000005    2022-09-08  20220908
5   INC000006    2022-09-16  20220916
6   INC000007    2022-04-14  20220414
7   INC000008    2025-12-27  20251227
8   INC000009    2024-10-25  20241025
9   INC000010    2025-03-13  20250313

In [197]:
valid_date_ids = set(
    dim_date["Date_ID"]
)

invalid_dates = (
    ~fact_hse_incident["Date_ID"].isin(valid_date_ids)
).sum()

print("Invalid Date IDs:", invalid_dates)

Invalid Date IDs: 0

In [198]:
incident_type_weights = {
    "IT001": 0.50,   # Near Miss
    "IT002": 0.16,   # First Aid Case
    "IT003": 0.10,   # Medical Treatment Case
    "IT004": 0.06,   # Restricted Work Case
    "IT005": 0.035,  # Lost Time Injury
    "IT006": 0.002,  # Fatality
    "IT007": 0.06,   # Property Damage
    "IT008": 0.025,  # Environmental Incident
    "IT009": 0.025,  # Fire / Explosion
    "IT010": 0.033   # Process Safety Event
}

print("Total Weight:", sum(incident_type_weights.values()))

Total Weight: 1.0

In [199]:
# ============================================================
# STEP 19 — INCIDENT TYPE PROFILE
# ============================================================

def get_incident_type_weights(department_id, asset_id):

    weights = incident_type_weights.copy()

    # --------------------------------------------------------
    # HIGH-HAZARD OPERATING ASSETS
    # Offshore, gas, refinery, LNG
    # --------------------------------------------------------

    high_hazard_assets = [
        "AST001", "AST002", "AST003",  # Offshore
        "AST006", "AST007",              # Gas
        "AST008",                        # Refinery
        "AST010"                         # LNG
    ]

    if asset_id in high_hazard_assets:
        weights["IT009"] *= 1.8   # Fire / Explosion
        weights["IT010"] *= 1.8   # Process Safety Event
        weights["IT008"] *= 1.2   # Environmental Incident

    # --------------------------------------------------------
    # MAINTENANCE
    # --------------------------------------------------------

    if department_id == "DEP003":
        weights["IT002"] *= 1.25   # First Aid
        weights["IT003"] *= 1.30   # MTC
        weights["IT004"] *= 1.20   # Restricted Work
        weights["IT005"] *= 1.15   # LTI
        weights["IT007"] *= 1.20   # Property Damage

    # --------------------------------------------------------
    # OPERATIONS
    # --------------------------------------------------------

    if department_id == "DEP001":
        weights["IT001"] *= 1.15   # Near Miss
        weights["IT009"] *= 1.25
        weights["IT010"] *= 1.30

    # --------------------------------------------------------
    # LOGISTICS
    # --------------------------------------------------------

    if department_id == "DEP005":
        weights["IT007"] *= 1.30   # Property Damage
        weights["IT002"] *= 1.15   # First Aid

    # --------------------------------------------------------
    # OFFICE-BASED FUNCTIONS
    # --------------------------------------------------------

    if department_id in ["DEP006", "DEP007"]:
        weights["IT001"] *= 1.30   # Near Miss
        weights["IT002"] *= 1.15   # First Aid
        weights["IT009"] *= 0.30
        weights["IT010"] *= 0.25
        weights["IT008"] *= 0.40

    # --------------------------------------------------------
    # NORMALIZE BACK TO 1
    # --------------------------------------------------------

    total = sum(weights.values())

    weights = {
        k: v / total
        for k, v in weights.items()
    }

    return weights

In [200]:
# ============================================================
# STEP 20 — TEST INCIDENT TYPE PROFILES
# ============================================================

test_cases = [
    ("DEP001", "AST001"),  # Operations + Offshore
    ("DEP003", "AST006"),  # Maintenance + Gas Compression
    ("DEP005", "AST009"),  # Logistics + Fuel Terminal
    ("DEP006", "AST008"),  # Finance + Refinery
]

for dept, asset in test_cases:

    profile = get_incident_type_weights(dept, asset)

    print(
        f"\nDepartment: {dept} | Asset: {asset}"
    )

    print(
        pd.Series(profile).sort_values(
            ascending=False
        )
    )

    print(
        "Total:",
        round(sum(profile.values()), 4)
    )

Department: DEP001 | Asset: AST001
IT001    0.497633
IT002    0.138472
IT003    0.086545
IT010    0.066830
IT007    0.051927
IT004    0.051927
IT009    0.048681
IT005    0.030291
IT008    0.025963
IT006    0.001731
dtype: float64
Total: 1.0

Department: DEP003 | Asset: AST006
IT001    0.434537
IT002    0.173815
IT003    0.112980
IT004    0.062573
IT007    0.062573
IT010    0.051623
IT009    0.039108
IT005    0.034980
IT008    0.026072
IT006    0.001738
dtype: float64
Total: 1.0

Department: DEP005 | Asset: AST009
IT001    0.479846
IT002    0.176583
IT003    0.095969
IT007    0.074856
IT004    0.057582
IT005    0.033589
IT010    0.031670
IT008    0.023992
IT009    0.023992
IT006    0.001919
dtype: float64
Total: 1.0

Department: DEP006 | Asset: AST008
IT001    0.574535
IT002    0.162638
IT003    0.088390
IT004    0.053034
IT007    0.053034
IT005    0.030936
IT010    0.013126
IT009    0.011933
IT008    0.010607
IT006    0.001768
dtype: float64
Total: 1.0

In [269]:
# ============================================================
# STEP 21 — REASSIGN INCIDENT TYPE CORRECTLY
# ============================================================

np.random.seed(42)

incident_type_ids = []

for _, row in fact_hse_incident.iterrows():

    profile = get_incident_type_weights(
        row["Department_ID"],
        row["Asset_ID"]
    )

    incident_type = np.random.choice(
        list(profile.keys()),
        p=list(profile.values())
    )

    incident_type_ids.append(incident_type)

fact_hse_incident["Incident_Type_ID"] = incident_type_ids

print("Missing Incident Types:",
      fact_hse_incident["Incident_Type_ID"].isna().sum())

print("\nOverall Incident Type Distribution:")
print(
    fact_hse_incident["Incident_Type_ID"]
    .value_counts()
    .sort_index()
)

Missing Incident Types: 0

Overall Incident Type Distribution:
Incident_Type_ID
IT001    3144
IT002     948
IT003     602
IT004     392
IT005     175
IT006      14
IT007     320
IT008     166
IT009     265
IT010     344
Name: count, dtype: int64

In [270]:
print(
    fact_hse_incident.assign(
        Year=fact_hse_incident["Incident_Date"].dt.year
    )
    .groupby(["Year", "Incident_Type_ID"])
    .size()
    .unstack(fill_value=0)
)

Incident_Type_ID  IT001  IT002  IT003  IT004  IT005  IT006  IT007  IT008  \
Year
2022               1421      0      0      0      0      0      0      0
2023               1400      0      0      0      0      0      0      0
2024                323    904    151      0      0      0      0      0
2025                  0     44    451    391    173     14    268     37
2026                  0      0      0      1      2      0     52    129

Incident_Type_ID  IT009  IT010
Year
2022                  0      0
2023                  0      0
2024                  0      0
2025                  0      0
2026                265    344

In [271]:
# ============================================================
# STEP 22 — INCIDENT TYPE DISTRIBUTION
# ============================================================

incident_type_distribution = (
    fact_hse_incident["Incident_Type_ID"]
    .value_counts()
    .sort_index()
)

print(incident_type_distribution)

Incident_Type_ID
IT001    3144
IT002     948
IT003     602
IT004     392
IT005     175
IT006      14
IT007     320
IT008     166
IT009     265
IT010     344
Name: count, dtype: int64

In [272]:
incident_type_percentage = (
    fact_hse_incident["Incident_Type_ID"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

print(
    incident_type_percentage.round(2)
)

Incident_Type_ID
IT001    49.36
IT002    14.88
IT003     9.45
IT004     6.15
IT005     2.75
IT006     0.22
IT007     5.02
IT008     2.61
IT009     4.16
IT010     5.40
Name: proportion, dtype: float64

In [273]:
# ============================================================
# STEP 23 — INCIDENT TYPE SUMMARY
# ============================================================

incident_type_summary = (
    fact_hse_incident
    .merge(
        dim_incident_type[
            [
                "Incident_Type_ID",
                "Incident_Type",
                "Incident_Category"
            ]
        ],
        on="Incident_Type_ID",
        how="left"
    )
    .groupby(
        [
            "Incident_Type_ID",
            "Incident_Type",
            "Incident_Category"
        ]
        )
    .size()
    .reset_index(name="Incident_Count")
)

incident_type_summary["Percentage"] = (
    incident_type_summary["Incident_Count"]
    / len(fact_hse_incident)
    * 100
)

incident_type_summary = (
    incident_type_summary
    .sort_values("Incident_Count", ascending=False)
)

incident_type_summary

,Incident_Type_ID,Incident_Type,Incident_Category,Incident_Count,Percentage
0,IT001,Near Miss,Near Miss,3144,49.356358
1,IT002,First Aid Case,Injury / Illness,948,14.882261
2,IT003,Medical Treatment Case,Injury / Illness,602,9.450549
3,IT004,Restricted Work Case,Injury / Illness,392,6.153846
9,IT010,Process Safety Event,Process Safety,344,5.400314
6,IT007,Property Damage,Property / Asset,320,5.023548
8,IT009,Fire / Explosion,Process / Fire,265,4.160126
4,IT005,Lost Time Injury,Injury / Illness,175,2.747253
7,IT008,Environmental Incident,Environmental,166,2.605965
5,IT006,Fatality,Fatality,14,0.219780

In [274]:
# ============================================================
# STEP 24 — HAZARD PROFILE
# ============================================================

def get_hazard_weights(department_id, asset_id):

    weights = {
        "HZ001": 0.14,  # Slips, Trips & Falls
        "HZ002": 0.08,  # Working at Height
        "HZ003": 0.04,  # Confined Space
        "HZ004": 0.08,  # Electrical Energy
        "HZ005": 0.09,  # Pressure / Stored Energy
        "HZ006": 0.07,  # Fire / Explosion
        "HZ007": 0.07,  # Hazardous Chemicals
        "HZ008": 0.10,  # Hydrocarbon Release
        "HZ009": 0.10,  # Lifting & Material Handling
        "HZ010": 0.08,  # Vehicle / Mobile Equipment
        "HZ011": 0.07,  # Dropped Objects
        "HZ012": 0.08   # Ergonomic / Manual Handling
    }

    # --------------------------------------------------------
    # HIGH-HAZARD PROCESS ASSETS
    # --------------------------------------------------------

    high_hazard_assets = [
        "AST001", "AST002", "AST003",
        "AST006", "AST007",
        "AST008", "AST010"
    ]

    if asset_id in high_hazard_assets:
        weights["HZ005"] *= 1.5
        weights["HZ006"] *= 1.5
        weights["HZ008"] *= 1.7
        weights["HZ002"] *= 1.3
        weights["HZ011"] *= 1.3

    # --------------------------------------------------------
    # OPERATIONS
    # --------------------------------------------------------

    if department_id == "DEP001":
        weights["HZ008"] *= 1.4
        weights["HZ005"] *= 1.3
        weights["HZ006"] *= 1.2
        weights["HZ011"] *= 1.2

    # --------------------------------------------------------
    # MAINTENANCE
    # --------------------------------------------------------

    if department_id == "DEP003":
        weights["HZ004"] *= 1.5
        weights["HZ005"] *= 1.4
        weights["HZ009"] *= 1.4
        weights["HZ001"] *= 1.2

    # --------------------------------------------------------
    # LOGISTICS
    # --------------------------------------------------------

    if department_id == "DEP005":
        weights["HZ010"] *= 1.6
        weights["HZ009"] *= 1.5
        weights["HZ001"] *= 1.2

    # --------------------------------------------------------
    # OFFICE FUNCTIONS
    # --------------------------------------------------------

    if department_id in ["DEP006", "DEP007"]:
        weights["HZ012"] *= 1.8
        weights["HZ001"] *= 1.3
        weights["HZ004"] *= 0.5
        weights["HZ005"] *= 0.4
        weights["HZ006"] *= 0.3
        weights["HZ008"] *= 0.3
        weights["HZ011"] *= 0.4

    # --------------------------------------------------------
    # NORMALIZE
    # --------------------------------------------------------

    total = sum(weights.values())

    weights = {
        k: v / total
        for k, v in weights.items()
    }

    return weights

In [275]:
# ============================================================
# STEP 24B — TEST HAZARD PROFILES
# ============================================================

test_cases = [
    ("DEP001", "AST001"),  # Operations + Offshore
    ("DEP003", "AST006"),  # Maintenance + Gas Compression
    ("DEP005", "AST009"),  # Logistics + Fuel Terminal
    ("DEP006", "AST008")   # Finance + Refinery
]

for dept, asset in test_cases:

    profile = get_hazard_weights(dept, asset)

    print(
        f"\nDepartment: {dept} | Asset: {asset}"
    )

    print(
        pd.Series(profile).sort_values(
            ascending=False
        )
    )

    print(
        "Total:",
        round(sum(profile.values()), 4)
    )

Department: DEP001 | Asset: AST001
HZ008    0.177255
HZ005    0.130707
HZ001    0.104268
HZ006    0.093841
HZ011    0.081329
HZ002    0.077456
HZ009    0.074477
HZ004    0.059581
HZ012    0.059581
HZ010    0.059581
HZ007    0.052134
HZ003    0.029791
dtype: float64
Total: 1.0

Department: DEP003 | Asset: AST006
HZ005    0.139278
HZ008    0.125276
HZ001    0.123803
HZ009    0.103169
HZ004    0.088430
HZ006    0.077377
HZ002    0.076640
HZ011    0.067060
HZ012    0.058954
HZ010    0.058954
HZ007    0.051584
HZ003    0.029477
dtype: float64
Total: 1.0

Department: DEP005 | Asset: AST009
HZ001    0.149201
HZ009    0.133215
HZ010    0.113677
HZ008    0.088810
HZ005    0.079929
HZ012    0.071048
HZ002    0.071048
HZ004    0.071048
HZ007    0.062167
HZ006    0.062167
HZ011    0.062167
HZ003    0.035524
dtype: float64
Total: 1.0

Department: DEP006 | Asset: AST008
HZ001    0.195091
HZ012    0.154357
HZ002    0.111480
HZ009    0.107193
HZ010    0.085754
HZ007    0.075035
HZ005    0.057884
HZ008    0.054668
HZ004    0.042877
HZ003    0.042877
HZ011    0.039018
HZ006    0.033766
dtype: float64
Total: 1.0

In [276]:
# ============================================================
# STEP 25 — ASSIGN HAZARD
# ============================================================

np.random.seed(42)

hazard_ids = []

for _, row in fact_hse_incident.iterrows():

    profile = get_hazard_weights(
        row["Department_ID"],
        row["Asset_ID"]
    )

    hazard = np.random.choice(
        list(profile.keys()),
        p=list(profile.values())
    )

    hazard_ids.append(hazard)

fact_hse_incident["Hazard_ID"] = hazard_ids

print(
    "Missing Hazard IDs:",
    fact_hse_incident["Hazard_ID"].isna().sum()
)

Missing Hazard IDs: 0

In [277]:
# ============================================================
# STEP 26 — HAZARD DISTRIBUTION
# ============================================================

hazard_distribution = (
    fact_hse_incident["Hazard_ID"]
    .value_counts()
    .sort_index()
)

print(hazard_distribution)

Hazard_ID
HZ001    789
HZ002    502
HZ003    220
HZ004    430
HZ005    741
HZ006    526
HZ007    371
HZ008    913
HZ009    536
HZ010    458
HZ011    458
HZ012    426
Name: count, dtype: int64

In [278]:
hazard_summary = (
    fact_hse_incident
    .merge(
        dim_hazard[
            [
                "Hazard_ID",
                "Hazard_Name",
                "Hazard_Category"
            ]
        ],
        on="Hazard_ID",
        how="left"
    )
    .groupby(
        [
            "Hazard_ID",
            "Hazard_Name",
            "Hazard_Category"
        ]
    )
    .size()
    .reset_index(name="Incident_Count")
)

hazard_summary["Percentage"] = (
    hazard_summary["Incident_Count"]
    / len(fact_hse_incident)
    * 100
)

hazard_summary = (
    hazard_summary
    .sort_values("Incident_Count", ascending=False)
)

hazard_summary

,Hazard_ID,Hazard_Name,Hazard_Category,Incident_Count,Percentage
7,HZ008,Hydrocarbon Release,Process Safety,913,14.332810
0,HZ001,"Slips, Trips & Falls",Physical,789,12.386185
4,HZ005,Pressure / Stored Energy,Energy,741,11.632653
8,HZ009,Lifting & Material Handling,Physical,536,8.414443
5,HZ006,Fire / Explosion,Process Safety,526,8.257457
1,HZ002,Working at Height,Physical,502,7.880691
10,HZ011,Dropped Objects,Physical,458,7.189953
9,HZ010,Vehicle / Mobile Equipment,Transportation,458,7.189953
3,HZ004,Electrical Energy,Energy,430,6.750392
11,HZ012,Ergonomic / Manual Handling,Ergonomic,426,6.687598
6,HZ007,Hazardous Chemicals,Chemical,371,5.824176
2,HZ003,Confined Space,Physical,220,3.453689

In [279]:
# ============================================================
# STEP 27 — HAZARD REFERENTIAL CHECK
# ============================================================

valid_hazard_ids = set(
    dim_hazard["Hazard_ID"]
)

invalid_hazards = (
    ~fact_hse_incident["Hazard_ID"]
    .isin(valid_hazard_ids)
).sum()

print("Invalid Hazard IDs:", invalid_hazards)

Invalid Hazard IDs: 0

In [280]:
# ============================================================
# STEP 28 — CONTRACTOR INVOLVEMENT PROBABILITY
# ============================================================

def get_contractor_probability(department_id, asset_id):

    probability = 0.15

    # Higher contractor presence in technical/field departments
    department_probability = {
        "DEP001": 0.25,  # Operations
        "DEP002": 0.30,  # Engineering
        "DEP003": 0.40,  # Maintenance
        "DEP004": 0.15,  # HSE
        "DEP005": 0.35,  # Logistics
        "DEP006": 0.05,  # Finance
        "DEP007": 0.05   # HR
    }

    probability = department_probability.get(
        department_id,
        probability
    )

    # Higher contractor presence around major operating assets
    high_contractor_assets = [
        "AST001", "AST002", "AST003",  # Offshore
        "AST004", "AST005",             # Pipeline
        "AST006", "AST007",             # Gas
        "AST008",                       # Refinery
        "AST010"                        # LNG
    ]

    if asset_id in high_contractor_assets:
        probability *= 1.20

    # Keep probability within sensible bounds
    probability = min(probability, 0.60)

    return probability

In [281]:
# ============================================================
# STEP 28B — TEST CONTRACTOR PROBABILITY
# ============================================================

test_cases = [
    ("DEP003", "AST006"),  # Maintenance + Gas Compression
    ("DEP002", "AST001"),  # Engineering + Offshore
    ("DEP005", "AST009"),  # Logistics + Terminal
    ("DEP006", "AST008"),  # Finance + Refinery
    ("DEP007", "AST011")   # HR + Solar
]

for dept, asset in test_cases:

    probability = get_contractor_probability(
        dept,
        asset
    )

    print(
        f"Department: {dept} | Asset: {asset} "
        f"| Contractor Probability: "
        f"{round(probability * 100, 2)}%"
    )

Department: DEP003 | Asset: AST006 | Contractor Probability: 48.0%
Department: DEP002 | Asset: AST001 | Contractor Probability: 36.0%
Department: DEP005 | Asset: AST009 | Contractor Probability: 35.0%
Department: DEP006 | Asset: AST008 | Contractor Probability: 6.0%
Department: DEP007 | Asset: AST011 | Contractor Probability: 5.0%

In [282]:

# ============================================================
# STEP 29 — CONTRACTOR INVOLVEMENT
# ============================================================

np.random.seed(42)

contractor_involvement = []

for _, row in fact_hse_incident.iterrows():

    probability = get_contractor_probability(
        row["Department_ID"],
        row["Asset_ID"]
    )

    involved = np.random.random() < probability

    contractor_involvement.append(involved)

fact_hse_incident["Contractor_Involved"] = contractor_involvement

print(
    fact_hse_incident["Contractor_Involved"].value_counts()
)

Contractor_Involved
False    4321
True     2049
Name: count, dtype: int64

In [283]:
contractor_rate = (
    fact_hse_incident["Contractor_Involved"].mean() * 100
)

print(
    "Overall Contractor Involvement Rate:",
    round(contractor_rate, 2),
    "%"
)

Overall Contractor Involvement Rate: 32.17 %

In [284]:
# ============================================================
# STEP 30 — CONTRACTOR ASSIGNMENT
# ============================================================

contractor_map = {
    "DEP001": ["CON004", "CON008"],  # Operations
    "DEP002": ["CON001", "CON008"],  # Engineering
    "DEP003": ["CON002", "CON001"],  # Maintenance
    "DEP004": ["CON006", "CON008"],  # HSE
    "DEP005": ["CON003", "CON004"],  # Logistics
    "DEP006": ["CON001"],            # Finance
    "DEP007": ["CON008"]             # HR
}

In [285]:
contractor_ids = []

for _, row in fact_hse_incident.iterrows():

    if row["Contractor_Involved"]:

        possible_contractors = contractor_map[
            row["Department_ID"]
        ]

        contractor = np.random.choice(
            possible_contractors
        )

    else:
        contractor = None

    contractor_ids.append(contractor)

fact_hse_incident["Contractor_ID"] = contractor_ids

In [286]:
# ============================================================
# STEP 31 — CONTRACTOR VALIDATION
# ============================================================

print("========== CONTRACTOR CHECK ==========")

print(
    "Contractor Involved:",
    fact_hse_incident["Contractor_Involved"].sum()
)

print(
    "Contractor Not Involved:",
    (~fact_hse_incident["Contractor_Involved"]).sum()
)

print(
    "Missing Contractor IDs:",
    fact_hse_incident["Contractor_ID"].isna().sum()
)

========== CONTRACTOR CHECK ==========
Contractor Involved: 2049
Contractor Not Involved: 4321
Missing Contractor IDs: 4321

In [287]:
invalid_contractor_logic = (
    fact_hse_incident["Contractor_Involved"].eq(True)
    & fact_hse_incident["Contractor_ID"].isna()
).sum()

print(
    "Contractor involved but ID missing:",
    invalid_contractor_logic
)

Contractor involved but ID missing: 0

In [288]:
valid_contractor_ids = set(
    dim_contractor["Contractor_ID"]
)

invalid_contractor_ids = (
    fact_hse_incident["Contractor_ID"].notna()
    & ~fact_hse_incident["Contractor_ID"].isin(
        valid_contractor_ids
    )
).sum()

print(
    "Invalid Contractor IDs:",
    invalid_contractor_ids
)

Invalid Contractor IDs: 0

In [289]:
# ============================================================
# STEP 32 — HSE CONSEQUENCE FLAGS
# ============================================================

fact_hse_incident["Recordable_Flag"] = (
    fact_hse_incident["Incident_Type_ID"].isin([
        "IT003",  # Medical Treatment Case
        "IT004",  # Restricted Work Case
        "IT005",  # Lost Time Injury
        "IT006"   # Fatality
    ])
).astype(int)

fact_hse_incident["LTI_Flag"] = (
    fact_hse_incident["Incident_Type_ID"] == "IT005"
).astype(int)

fact_hse_incident["Fatality_Flag"] = (
    fact_hse_incident["Incident_Type_ID"] == "IT006"
).astype(int)

fact_hse_incident["Near_Miss_Flag"] = (
    fact_hse_incident["Incident_Type_ID"] == "IT001"
).astype(int)

In [290]:
print("========== CONSEQUENCE FLAG CHECK ==========")

print(
    "Recordable Incidents:",
    fact_hse_incident["Recordable_Flag"].sum()
)

print(
    "Lost Time Injuries:",
    fact_hse_incident["LTI_Flag"].sum()
)

print(
    "Fatalities:",
    fact_hse_incident["Fatality_Flag"].sum()
)

print(
    "Near Misses:",
    fact_hse_incident["Near_Miss_Flag"].sum()
)

========== CONSEQUENCE FLAG CHECK ==========
Recordable Incidents: 1183
Lost Time Injuries: 175
Fatalities: 14
Near Misses: 3144

In [291]:
np.random.seed(42)

def generate_lost_days(incident_type):

    if incident_type in ["IT001", "IT002", "IT003", "IT007", "IT008"]:
        return 0

    elif incident_type == "IT004":
        return np.random.randint(1, 15)

    elif incident_type == "IT005":
        return np.random.randint(3, 91)

    elif incident_type == "IT006":
        return np.random.randint(180, 366)

    elif incident_type in ["IT009", "IT010"]:
        return np.random.choice(
            [0, np.random.randint(1, 31)],
            p=[0.65, 0.35]
        )

    return 0


fact_hse_incident["Lost_Days"] = (
    fact_hse_incident["Incident_Type_ID"]
    .apply(generate_lost_days)
)

In [292]:
print("========== LOST DAYS CHECK ==========")

print("Total Lost Days:", fact_hse_incident["Lost_Days"].sum())
print("Minimum Lost Days:", fact_hse_incident["Lost_Days"].min())
print("Maximum Lost Days:", fact_hse_incident["Lost_Days"].max())
print("Missing Lost Days:", fact_hse_incident["Lost_Days"].isna().sum())

========== LOST DAYS CHECK ==========
Total Lost Days: 17757
Minimum Lost Days: 0
Maximum Lost Days: 360
Missing Lost Days: 0

In [293]:
# ============================================================
# STEP 34 — DOWNTIME HOURS
# ============================================================

np.random.seed(42)

def generate_downtime(incident_type):

    if incident_type == "IT001":       # Near Miss
        return np.random.choice(
            [0, np.random.uniform(0.5, 4)],
            p=[0.90, 0.10]
        )

    elif incident_type == "IT002":     # First Aid
        return np.random.choice(
            [0, np.random.uniform(0.5, 8)],
            p=[0.80, 0.20]
        )

    elif incident_type == "IT003":     # Medical Treatment
        return np.random.uniform(0, 12)

    elif incident_type == "IT004":     # Restricted Work
        return np.random.uniform(1, 24)

    elif incident_type == "IT005":     # LTI
        return np.random.uniform(4, 48)

    elif incident_type == "IT006":     # Fatality
        return np.random.uniform(24, 168)

    elif incident_type == "IT007":     # Property Damage
        return np.random.uniform(2, 72)

    elif incident_type == "IT008":     # Environmental
        return np.random.uniform(1, 48)

    elif incident_type == "IT009":     # Fire / Explosion
        return np.random.uniform(12, 240)

    elif incident_type == "IT010":     # Process Safety Event
        return np.random.uniform(8, 168)

    return 0


fact_hse_incident["Downtime_Hours"] = (
    fact_hse_incident["Incident_Type_ID"]
    .apply(generate_downtime)
    .round(2)
)

In [294]:
print("========== DOWNTIME CHECK ==========")

print(
    "Total Downtime Hours:",
    round(fact_hse_incident["Downtime_Hours"].sum(), 2)
)

print(
    "Average Downtime Hours:",
    round(fact_hse_incident["Downtime_Hours"].mean(), 2)
)

print(
    "Minimum Downtime Hours:",
    fact_hse_incident["Downtime_Hours"].min()
)

print(
    "Maximum Downtime Hours:",
    fact_hse_incident["Downtime_Hours"].max()
)

print(
    "Missing Downtime:",
    fact_hse_incident["Downtime_Hours"].isna().sum()
)

========== DOWNTIME CHECK ==========
Total Downtime Hours: 92270.57
Average Downtime Hours: 14.49
Minimum Downtime Hours: 0.0
Maximum Downtime Hours: 239.89
Missing Downtime: 0

In [295]:
# ============================================================
# STEP 35 — CALIBRATED HSE FINANCIAL IMPACT
# ============================================================

np.random.seed(42)

def generate_hse_costs(row):

    incident_type = row["Incident_Type_ID"]
    downtime = row["Downtime_Hours"]
    lost_days = row["Lost_Days"]

    # --------------------------------------------------------
    # 1. PROPERTY DAMAGE
    # --------------------------------------------------------

    if incident_type == "IT001":          # Near Miss
        property_cost = np.random.uniform(0, 100)

    elif incident_type == "IT002":        # First Aid
        property_cost = np.random.uniform(0, 500)

    elif incident_type == "IT003":        # Medical Treatment
        property_cost = np.random.uniform(0, 1_000)

    elif incident_type == "IT004":        # Restricted Work
        property_cost = np.random.uniform(250, 2_500)

    elif incident_type == "IT005":        # LTI
        property_cost = np.random.uniform(500, 5_000)

    elif incident_type == "IT006":        # Fatality
        property_cost = np.random.uniform(1_000, 15_000)

    elif incident_type == "IT007":        # Property Damage
        property_cost = np.random.uniform(5_000, 75_000)

    elif incident_type == "IT008":        # Environmental
        property_cost = np.random.uniform(500, 10_000)

    elif incident_type == "IT009":        # Fire / Explosion
        property_cost = np.random.uniform(10_000, 100_000)

    elif incident_type == "IT010":        # Process Safety
        property_cost = np.random.uniform(5_000, 75_000)

    # --------------------------------------------------------
    # 2. ENVIRONMENTAL REMEDIATION
    # --------------------------------------------------------

    if incident_type == "IT008":
        environmental_cost = np.random.uniform(5_000, 100_000)

    elif incident_type == "IT009":
        environmental_cost = np.random.uniform(1_000, 30_000)

    elif incident_type == "IT010":
        environmental_cost = np.random.uniform(1_000, 25_000)

    else:
        environmental_cost = np.random.uniform(0, 1_000)

    # --------------------------------------------------------
    # 3. EMERGENCY RESPONSE
    # --------------------------------------------------------

    if incident_type == "IT001":
        emergency_cost = np.random.uniform(0, 100)

    elif incident_type == "IT002":
        emergency_cost = np.random.uniform(100, 750)

    elif incident_type == "IT003":
        emergency_cost = np.random.uniform(250, 2_000)

    elif incident_type == "IT004":
        emergency_cost = np.random.uniform(500, 3_000)

    elif incident_type == "IT005":
        emergency_cost = np.random.uniform(1_000, 7_500)

    elif incident_type == "IT006":
        emergency_cost = np.random.uniform(5_000, 30_000)

    elif incident_type == "IT007":
        emergency_cost = np.random.uniform(1_000, 15_000)

    elif incident_type == "IT008":
        emergency_cost = np.random.uniform(1_000, 20_000)

    elif incident_type == "IT009":
        emergency_cost = np.random.uniform(10_000, 75_000)

    elif incident_type == "IT010":
        emergency_cost = np.random.uniform(5_000, 50_000)

    # --------------------------------------------------------
    # 4. MEDICAL / COMPENSATION
    # --------------------------------------------------------

    if incident_type == "IT001":
        medical_cost = 0

    elif incident_type == "IT002":
        medical_cost = np.random.uniform(100, 1_500)

    elif incident_type == "IT003":
        medical_cost = np.random.uniform(1_000, 10_000)

    elif incident_type == "IT004":
        medical_cost = np.random.uniform(2_000, 15_000)

    elif incident_type == "IT005":
        medical_cost = np.random.uniform(5_000, 50_000)

    elif incident_type == "IT006":
        medical_cost = np.random.uniform(50_000, 200_000)

    else:
        medical_cost = 0

    # --------------------------------------------------------
    # 5. OPERATIONAL DISRUPTION
    # Conservative rate so HSE remains below pipeline costs
    # --------------------------------------------------------

    disruption_rate = np.random.uniform(100, 500)

    operational_cost = (
        downtime * disruption_rate
        + lost_days * np.random.uniform(100, 500)
    )

    # --------------------------------------------------------
    # 6. OTHER HSE COSTS
    # --------------------------------------------------------

    other_cost = np.random.uniform(0, 2_000)

    # --------------------------------------------------------
    # TOTAL HSE INCIDENT COST
    # --------------------------------------------------------

    total_cost = (
        property_cost
        + environmental_cost
        + emergency_cost
        + medical_cost
        + operational_cost
        + other_cost
    )

    return (
        property_cost,
        environmental_cost,
        emergency_cost,
        medical_cost,
        operational_cost,
        other_cost,
        total_cost
    )


# Generate costs
hse_costs = fact_hse_incident.apply(
    generate_hse_costs,
    axis=1
)

# Add columns
fact_hse_incident["Property_Damage_Cost"] = (
    hse_costs.apply(lambda x: round(x[0], 2))
)

fact_hse_incident["Environmental_Cost"] = (
    hse_costs.apply(lambda x: round(x[1], 2))
)

fact_hse_incident["Emergency_Response_Cost"] = (
    hse_costs.apply(lambda x: round(x[2], 2))
)

fact_hse_incident["Medical_Compensation_Cost"] = (
    hse_costs.apply(lambda x: round(x[3], 2))
)

fact_hse_incident["Operational_Disruption_Cost"] = (
    hse_costs.apply(lambda x: round(x[4], 2))
)

fact_hse_incident["Other_Cost"] = (
    hse_costs.apply(lambda x: round(x[5], 2))
)

fact_hse_incident["Total_Incident_Cost"] = (
    hse_costs.apply(lambda x: round(x[6], 2))
)

In [296]:
print("========== HSE FINANCIAL IMPACT CHECK ==========")

cost_columns = [
    "Property_Damage_Cost",
    "Environmental_Cost",
    "Emergency_Response_Cost",
    "Medical_Compensation_Cost",
    "Operational_Disruption_Cost",
    "Other_Cost",
    "Total_Incident_Cost"
]

for col in cost_columns:
    print(
        f"{col}:",
        round(fact_hse_incident[col].sum(), 2)
    )

========== HSE FINANCIAL IMPACT CHECK ==========
Property_Damage_Cost: 43495551.47
Environmental_Cost: 20214698.31
Emergency_Response_Cost: 27756094.32
Medical_Compensation_Cost: 13565633.48
Operational_Disruption_Cost: 33608766.43
Other_Cost: 6412271.41
Total_Incident_Cost: 145053015.73

In [297]:
calculated_total = (
    fact_hse_incident["Property_Damage_Cost"]
    + fact_hse_incident["Environmental_Cost"]
    + fact_hse_incident["Emergency_Response_Cost"]
    + fact_hse_incident["Medical_Compensation_Cost"]
    + fact_hse_incident["Operational_Disruption_Cost"]
    + fact_hse_incident["Other_Cost"]
)

reconciliation_error = (
    calculated_total
    - fact_hse_incident["Total_Incident_Cost"]
).abs()

print("========== COST RECONCILIATION ==========")

print(
    "Reconciliation Errors:",
    (reconciliation_error > 0.01).sum()
)

print(
    "Missing Financial Values:",
    fact_hse_incident[cost_columns].isna().sum().sum()
)

========== COST RECONCILIATION ==========
Reconciliation Errors: 1260
Missing Financial Values: 0

In [298]:
print("========== COST BY INCIDENT TYPE ==========")

cost_by_type = (
    fact_hse_incident
    .groupby("Incident_Type_ID")["Total_Incident_Cost"]
    .agg(["count", "sum", "mean"])
    .sort_values("sum", ascending=False)
)

print(cost_by_type)

========== COST BY INCIDENT TYPE ==========
                  count          sum           mean
Incident_Type_ID
IT009               265  40147077.35  151498.405094
IT010               344  37911734.67  110208.531017
IT007               320  18592926.76   58102.896125
IT008               166  12755992.92   76843.330843
IT005               175   9867922.99   56388.131371
IT004               392   7413733.46   18912.585357
IT003               602   6197261.91   10294.455000
IT001              3144   5248628.75    1669.411180
IT006                14   3824560.27  273182.876429
IT002               948   3093176.65    3262.844568

In [299]:
print("========== CURRENT FACT_HSE_INCIDENT ==========")

print("Rows:", len(fact_hse_incident))
print("Columns:", len(fact_hse_incident.columns))

print("\nColumns:")
for i, col in enumerate(fact_hse_incident.columns, 1):
    print(f"{i}. {col}")

========== CURRENT FACT_HSE_INCIDENT ==========
Rows: 6370
Columns: 27

Columns:
1. Incident_ID
2. Employee_ID
3. BusinessUnit_ID
4. Department_ID
5. Asset_ID
6. Shift_ID
7. Work_Location
8. Incident_Month
9. Incident_Date
10. Date_ID
11. Incident_Type_ID
12. Hazard_ID
13. Contractor_Involved
14. Contractor_ID
15. Recordable_Flag
16. LTI_Flag
17. Fatality_Flag
18. Near_Miss_Flag
19. Lost_Days
20. Downtime_Hours
21. Property_Damage_Cost
22. Environmental_Cost
23. Emergency_Response_Cost
24. Medical_Compensation_Cost
25. Operational_Disruption_Cost
26. Other_Cost
27. Total_Incident_Cost

In [300]:
# ============================================================
# STEP 37 — FINAL FACT_HSE_INCIDENT VALIDATION
# ============================================================

print("========== FACT_HSE_INCIDENT FINAL VALIDATION ==========")

print("Rows:", len(fact_hse_incident))
print("Columns:", len(fact_hse_incident.columns))

print("\nUnique Incident IDs:",
      fact_hse_incident["Incident_ID"].nunique())

print("Unique Employees:",
      fact_hse_incident["Employee_ID"].nunique())

print("\nMissing Values:")
print(
    fact_hse_incident.isna().sum()
)

========== FACT_HSE_INCIDENT FINAL VALIDATION ==========
Rows: 6370
Columns: 27

Unique Incident IDs: 6370
Unique Employees: 2968

Missing Values:
Incident_ID                       0
Employee_ID                       0
BusinessUnit_ID                   0
Department_ID                     0
Asset_ID                          0
Shift_ID                          0
Work_Location                     0
Incident_Month                    0
Incident_Date                     0
Date_ID                           0
Incident_Type_ID                  0
Hazard_ID                         0
Contractor_Involved               0
Contractor_ID                  4321
Recordable_Flag                   0
LTI_Flag                          0
Fatality_Flag                     0
Near_Miss_Flag                    0
Lost_Days                         0
Downtime_Hours                    0
Property_Damage_Cost              0
Environmental_Cost                0
Emergency_Response_Cost           0
Medical_Compensation_Cost         0
Operational_Disruption_Cost       0
Other_Cost                        0
Total_Incident_Cost               0
dtype: int64

In [301]:
print("\n========== DIMENSION INTEGRITY ==========")

print(
    "Invalid Employee IDs:",
    (~fact_hse_incident["Employee_ID"].isin(
        dim_employee["Employee_ID"]
    )).sum()
)

print(
    "Invalid Business Units:",
    (~fact_hse_incident["BusinessUnit_ID"].isin(
        dim_business_unit["BusinessUnit_ID"]
    )).sum()
)

print(
    "Invalid Departments:",
    (~fact_hse_incident["Department_ID"].isin(
        dim_department["Department_ID"]
    )).sum()
)

print(
    "Invalid Assets:",
    (~fact_hse_incident["Asset_ID"].isin(
        dim_asset["Asset_ID"]
    )).sum()
)

print(
    "Invalid Shifts:",
    (~fact_hse_incident["Shift_ID"].isin(
        dim_shift["Shift_ID"]
    )).sum()
)

print(
    "Invalid Incident Types:",
    (~fact_hse_incident["Incident_Type_ID"].isin(
        dim_incident_type["Incident_Type_ID"]
    )).sum()
)

print(
    "Invalid Hazards:",
    (~fact_hse_incident["Hazard_ID"].isin(
        dim_hazard["Hazard_ID"]
    )).sum()
)

========== DIMENSION INTEGRITY ==========
Invalid Employee IDs: 0
Invalid Business Units: 0
Invalid Departments: 0
Invalid Assets: 0
Invalid Shifts: 0
Invalid Incident Types: 0
Invalid Hazards: 0

In [302]:
valid_contractors = set(
    dim_contractor["Contractor_ID"]
)

invalid_contractor_ids = (
    fact_hse_incident["Contractor_ID"].notna()
    & ~fact_hse_incident["Contractor_ID"].isin(
        valid_contractors
    )
).sum()

print(
    "Invalid Contractor IDs:",
    invalid_contractor_ids
)

Invalid Contractor IDs: 0

In [303]:
contractor_logic_errors = (
    (
        fact_hse_incident["Contractor_Involved"] == True
    )
    &
    fact_hse_incident["Contractor_ID"].isna()
).sum()

print(
    "Contractor logic errors:",
    contractor_logic_errors
)

Contractor logic errors: 0

In [304]:
print("\n========== INCIDENT LOGIC CHECK ==========")

print(
    "Recordable incidents:",
    fact_hse_incident["Recordable_Flag"].sum()
)

print(
    "LTI:",
    fact_hse_incident["LTI_Flag"].sum()
)

print(
    "Fatalities:",
    fact_hse_incident["Fatality_Flag"].sum()
)

print(
    "Near Misses:",
    fact_hse_incident["Near_Miss_Flag"].sum()
)

print(
    "Total Lost Days:",
    fact_hse_incident["Lost_Days"].sum()
)

print(
    "Total Downtime Hours:",
    round(
        fact_hse_incident["Downtime_Hours"].sum(),
        2
    )
)

print(
    "Total Incident Cost:",
    round(
        fact_hse_incident["Total_Incident_Cost"].sum(),
        2
    )
)

========== INCIDENT LOGIC CHECK ==========
Recordable incidents: 1183
LTI: 175
Fatalities: 14
Near Misses: 3144
Total Lost Days: 17757
Total Downtime Hours: 92270.57
Total Incident Cost: 145053015.73

In [305]:
calculated_total = (
    fact_hse_incident["Property_Damage_Cost"]
    + fact_hse_incident["Environmental_Cost"]
    + fact_hse_incident["Emergency_Response_Cost"]
    + fact_hse_incident["Medical_Compensation_Cost"]
    + fact_hse_incident["Operational_Disruption_Cost"]
    + fact_hse_incident["Other_Cost"]
)

print(
    "\nCost reconciliation errors:",
    (
        (
            calculated_total
            - fact_hse_incident["Total_Incident_Cost"]
        ).abs() > 0.01
    ).sum()
)

Cost reconciliation errors: 1260

In [306]:
# ============================================================
# COST RECONCILIATION DIAGNOSTIC
# ============================================================

cost_components = [
    "Property_Damage_Cost",
    "Environmental_Cost",
    "Emergency_Response_Cost",
    "Medical_Compensation_Cost",
    "Operational_Disruption_Cost",
    "Other_Cost"
]

calculated_total = fact_hse_incident[cost_components].sum(axis=1)

cost_difference = (
    calculated_total
    - fact_hse_incident["Total_Incident_Cost"]
)

print("========== COST RECONCILIATION DIAGNOSTIC ==========")

print("Rows checked:", len(fact_hse_incident))

print(
    "Rows with difference > $0.01:",
    (cost_difference.abs() > 0.01).sum()
)

print(
    "Maximum difference:",
    round(cost_difference.abs().max(), 2)
)

print(
    "Average absolute difference:",
    round(cost_difference.abs().mean(), 2)
)

print(
    "Total difference:",
    round(cost_difference.sum(), 2)
)

========== COST RECONCILIATION DIAGNOSTIC ==========
Rows checked: 6370
Rows with difference > $0.01: 1260
Maximum difference: 0.02
Average absolute difference: 0.0
Total difference: -0.31

In [307]:
# ============================================================
# FINALIZE TOTAL INCIDENT COST
# ============================================================

cost_components = [
    "Property_Damage_Cost",
    "Environmental_Cost",
    "Emergency_Response_Cost",
    "Medical_Compensation_Cost",
    "Operational_Disruption_Cost",
    "Other_Cost"
]

fact_hse_incident["Total_Incident_Cost"] = (
    fact_hse_incident[cost_components]
    .sum(axis=1)
    .round(2)
)

print("Total Incident Cost:",
      round(
          fact_hse_incident["Total_Incident_Cost"].sum(),
          2
      ))

Total Incident Cost: 145053015.42

In [308]:
# ============================================================
# FINAL COST RECONCILIATION
# ============================================================

calculated_total = (
    fact_hse_incident[cost_components]
    .sum(axis=1)
    .round(2)
)

difference = (
    calculated_total
    - fact_hse_incident["Total_Incident_Cost"]
).abs()

print("========== FINAL COST RECONCILIATION ==========")

print(
    "Rows with reconciliation error:",
    (difference > 0.01).sum()
)

print(
    "Maximum difference:",
    difference.max()
)

========== FINAL COST RECONCILIATION ==========
Rows with reconciliation error: 0
Maximum difference: 0.0

In [309]:
print("========== FINAL FACT_HSE_INCIDENT CHECK ==========")

print("Rows:", len(fact_hse_incident))
print("Columns:", len(fact_hse_incident.columns))
print("Unique Incident IDs:",
      fact_hse_incident["Incident_ID"].nunique())

print("\nTotal Recordable:",
      fact_hse_incident["Recordable_Flag"].sum())

print("Total LTI:",
      fact_hse_incident["LTI_Flag"].sum())

print("Total Fatalities:",
      fact_hse_incident["Fatality_Flag"].sum())

print("Total Near Misses:",
      fact_hse_incident["Near_Miss_Flag"].sum())

print("Total Lost Days:",
      fact_hse_incident["Lost_Days"].sum())

print("Total Downtime Hours:",
      round(fact_hse_incident["Downtime_Hours"].sum(), 2))

print("Total Incident Cost:",
      round(fact_hse_incident["Total_Incident_Cost"].sum(), 2))

========== FINAL FACT_HSE_INCIDENT CHECK ==========
Rows: 6370
Columns: 27
Unique Incident IDs: 6370

Total Recordable: 1183
Total LTI: 175
Total Fatalities: 14
Total Near Misses: 3144
Total Lost Days: 17757
Total Downtime Hours: 92270.57
Total Incident Cost: 145053015.42

In [310]:
incident_employees = set(
    fact_hse_incident["Employee_ID"]
)

exposure_employees = set(
    fact_hse_exposure["Employee_ID"]
)

missing_from_exposure = (
    incident_employees - exposure_employees
)

print("========== EMPLOYEE CROSS-CHECK ==========")

print(
    "Unique incident employees:",
    len(incident_employees)
)

print(
    "Unique exposure employees:",
    len(exposure_employees)
)

print(
    "Incident employees missing from exposure:",
    len(missing_from_exposure)
)

if len(missing_from_exposure) > 0:
    print("Examples:", list(missing_from_exposure)[:10])

========== EMPLOYEE CROSS-CHECK ==========
Unique incident employees: 2968
Unique exposure employees: 4000
Incident employees missing from exposure: 0

In [311]:
employee_department_check = (
    fact_hse_incident[
        ["Employee_ID", "Department_ID"]
    ]
    .drop_duplicates()
    .merge(
        fact_hse_exposure[
            ["Employee_ID", "Department_ID"]
        ].drop_duplicates(),
        on="Employee_ID",
        how="left",
        suffixes=("_Incident", "_Exposure")
    )
)

department_mismatch = (
    employee_department_check["Department_ID_Incident"]
    != employee_department_check["Department_ID_Exposure"]
)

print("========== DEPARTMENT CROSS-CHECK ==========")

print(
    "Department mismatches:",
    department_mismatch.sum()
)

========== DEPARTMENT CROSS-CHECK ==========
Department mismatches: 0

In [312]:
employee_bu_check = (
    fact_hse_incident[
        ["Employee_ID", "BusinessUnit_ID"]
    ]
    .drop_duplicates()
    .merge(
        fact_hse_exposure[
            ["Employee_ID", "BusinessUnit_ID"]
        ].drop_duplicates(),
        on="Employee_ID",
        how="left",
        suffixes=("_Incident", "_Exposure")
    )
)

bu_mismatch = (
    employee_bu_check["BusinessUnit_ID_Incident"]
    != employee_bu_check["BusinessUnit_ID_Exposure"]
)

print("========== BUSINESS UNIT CROSS-CHECK ==========")

print(
    "Business Unit mismatches:",
    bu_mismatch.sum()
)

========== BUSINESS UNIT CROSS-CHECK ==========
Business Unit mismatches: 0

In [313]:
employee_asset_check = (
    fact_hse_incident[
        ["Employee_ID", "Asset_ID"]
    ]
    .drop_duplicates()
    .merge(
        fact_hse_exposure[
            ["Employee_ID", "Asset_ID"]
        ].drop_duplicates(),
        on="Employee_ID",
        how="left",
        suffixes=("_Incident", "_Exposure")
    )
)

asset_mismatch = (
    employee_asset_check["Asset_ID_Incident"]
    != employee_asset_check["Asset_ID_Exposure"]
)

print("========== ASSET CROSS-CHECK ==========")

print(
    "Asset mismatches:",
    asset_mismatch.sum()
)

========== ASSET CROSS-CHECK ==========
Asset mismatches: 0

In [314]:
employee_shift_check = (
    fact_hse_incident[
        ["Employee_ID", "Shift_ID"]
    ]
    .drop_duplicates()
    .merge(
        fact_hse_exposure[
            ["Employee_ID", "Shift_ID"]
        ].drop_duplicates(),
        on="Employee_ID",
        how="left",
        suffixes=("_Incident", "_Exposure")
    )
)

shift_mismatch = (
    employee_shift_check["Shift_ID_Incident"]
    != employee_shift_check["Shift_ID_Exposure"]
)

print("========== SHIFT CROSS-CHECK ==========")

print(
    "Shift mismatches:",
    shift_mismatch.sum()
)

========== SHIFT CROSS-CHECK ==========
Shift mismatches: 0

In [315]:
print("FACT_HSE_INCIDENT")
print(fact_hse_incident.columns.tolist())

print("\nDIM_EMPLOYEE")
print(dim_employee.columns.tolist())

print("\nDIM_DEPARTMENT")
print(dim_department.columns.tolist())

print("\nDIM_BUSINESS UNIT")
print(dim_business_unit.columns.tolist())

print("\nDIM_ASSET")
print(dim_asset.columns.tolist())

FACT_HSE_INCIDENT
['Incident_ID', 'Employee_ID', 'BusinessUnit_ID', 'Department_ID', 'Asset_ID', 'Shift_ID', 'Work_Location', 'Incident_Month', 'Incident_Date', 'Date_ID', 'Incident_Type_ID', 'Hazard_ID', 'Contractor_Involved', 'Contractor_ID', 'Recordable_Flag', 'LTI_Flag', 'Fatality_Flag', 'Near_Miss_Flag', 'Lost_Days', 'Downtime_Hours', 'Property_Damage_Cost', 'Environmental_Cost', 'Emergency_Response_Cost', 'Medical_Compensation_Cost', 'Operational_Disruption_Cost', 'Other_Cost', 'Total_Incident_Cost']

DIM_EMPLOYEE
['Employee_ID', 'BusinessUnit_ID', 'Department_ID', 'Asset_ID', 'Job_Role', 'Shift_ID', 'Employment_Type', 'Employment_Status', 'Gender', 'Date_of_Birth', 'Age', 'Hire_Date', 'Years_of_Service', 'Years_of_Experience', 'Supervisor_ID', 'Crew', 'Education_Level', 'Certification_Status', 'Training_Compliance', 'PPE_Compliance', 'Medical_Fitness', 'Emergency_Response_Team', 'Nationality', 'Work_Location']

DIM_DEPARTMENT
['Department_ID', 'Department']

DIM_BUSINESS UNIT
['BusinessUnit_ID', 'Business_Unit']

DIM_ASSET
['Asset_ID', 'BusinessUnit_ID', 'Asset_Name']

In [316]:
# ============================================================
# STEP 1 — DIM_CORRECTIVEACTION
# ============================================================

import pandas as pd

dim_corrective_action = pd.DataFrame({
    "Corrective_Action_Type_ID": [
        "CA001",
        "CA002",
        "CA003",
        "CA004",
        "CA005",
        "CA006",
        "CA007",
        "CA008"
    ],

    "Corrective_Action_Type": [
        "Engineering Control",
        "Administrative Control",
        "Procedure / Process Revision",
        "Training / Competency",
        "PPE Improvement",
        "Maintenance / Repair",
        "Inspection / Monitoring",
        "Emergency Preparedness"
    ]
})

# ============================================================
# CHECK
# ============================================================

print("========== DIM_CORRECTIVEACTION CHECK ==========")

print("Rows:", len(dim_corrective_action))
print("Columns:", len(dim_corrective_action.columns))

print("\nColumn Names:")
print(dim_corrective_action.columns.tolist())

print("\nDuplicate IDs:",
      dim_corrective_action["Corrective_Action_Type_ID"].duplicated().sum())

print("\nMissing Values:")
print(dim_corrective_action.isna().sum())

print("\nDimension:")
display(dim_corrective_action)

========== DIM_CORRECTIVEACTION CHECK ==========
Rows: 8
Columns: 2

Column Names:
['Corrective_Action_Type_ID', 'Corrective_Action_Type']

Duplicate IDs: 0

Missing Values:
Corrective_Action_Type_ID    0
Corrective_Action_Type       0
dtype: int64

Dimension:

  Corrective_Action_Type_ID        Corrective_Action_Type
0                     CA001           Engineering Control
1                     CA002        Administrative Control
2                     CA003  Procedure / Process Revision
3                     CA004         Training / Competency
4                     CA005               PPE Improvement
5                     CA006          Maintenance / Repair
6                     CA007       Inspection / Monitoring
7                     CA008        Emergency Preparedness

In [317]:
# ============================================================
# STEP 2 — INITIAL FACT_HSE_CORRECTIVE_ACTION
# ============================================================

import numpy as np
import pandas as pd

np.random.seed(42)

# ------------------------------------------------------------
# 1. Use existing incidents
# ------------------------------------------------------------

incident_source = fact_hse_incident.copy()

# Only incidents that occurred on or before the reporting cutoff
reporting_cutoff = pd.Timestamp("2026-07-31")

incident_source["Incident_Date"] = pd.to_datetime(
    incident_source["Incident_Date"]
)

incident_source = incident_source[
    incident_source["Incident_Date"] <= reporting_cutoff
].copy()

# ------------------------------------------------------------
# 2. Number of corrective actions
# ------------------------------------------------------------

num_actions = 3060

# Sample existing incidents WITH replacement
# so one incident can have more than one corrective action
selected_incidents = incident_source.sample(
    n=num_actions,
    replace=True,
    random_state=42
).reset_index(drop=True)

# ------------------------------------------------------------
# 3. Create Corrective Action IDs
# ------------------------------------------------------------

corrective_action_ids = [
    f"CA{str(i).zfill(6)}"
    for i in range(1, num_actions + 1)
]

# ------------------------------------------------------------
# 4. Build initial fact table
# ------------------------------------------------------------

fact_hse_corrective_action = pd.DataFrame({
    "Corrective_Action_ID": corrective_action_ids,

    "Incident_ID":
        selected_incidents["Incident_ID"].values,

    "Employee_ID":
        selected_incidents["Employee_ID"].values,

    "BusinessUnit_ID":
        selected_incidents["BusinessUnit_ID"].values,

    "Department_ID":
        selected_incidents["Department_ID"].values,

    "Asset_ID":
        selected_incidents["Asset_ID"].values,

    "Incident_Type_ID":
        selected_incidents["Incident_Type_ID"].values,

    "Hazard_ID":
        selected_incidents["Hazard_ID"].values,

    "Incident_Date":
        selected_incidents["Incident_Date"].values
})

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print("========== STEP 2 CHECK ==========")

print("Rows:", len(fact_hse_corrective_action))
print("Columns:", len(fact_hse_corrective_action.columns))

print("\nColumns:")
print(fact_hse_corrective_action.columns.tolist())

print("\nUnique Corrective Action IDs:",
      fact_hse_corrective_action[
          "Corrective_Action_ID"
      ].nunique())

print("\nUnique Incident IDs:",
      fact_hse_corrective_action[
          "Incident_ID"
      ].nunique())

print("\nLatest Incident Date:",
      fact_hse_corrective_action[
          "Incident_Date"
      ].max())

print("\nFuture Incidents After Cutoff:",
      (
          fact_hse_corrective_action["Incident_Date"]
          > reporting_cutoff
      ).sum())

print("\nMissing Values:")
print(fact_hse_corrective_action.isna().sum())

display(
    fact_hse_corrective_action.head(10)
)

========== STEP 2 CHECK ==========
Rows: 3060
Columns: 9

Columns:
['Corrective_Action_ID', 'Incident_ID', 'Employee_ID', 'BusinessUnit_ID', 'Department_ID', 'Asset_ID', 'Incident_Type_ID', 'Hazard_ID', 'Incident_Date']

Unique Corrective Action IDs: 3060

Unique Incident IDs: 2407

Latest Incident Date: 2026-07-31 00:00:00

Future Incidents After Cutoff: 0

Missing Values:
Corrective_Action_ID    0
Incident_ID             0
Employee_ID             0
BusinessUnit_ID         0
Department_ID           0
Asset_ID                0
Incident_Type_ID        0
Hazard_ID               0
Incident_Date           0
dtype: int64

,Corrective_Action_ID,Incident_ID,Employee_ID,BusinessUnit_ID,Department_ID,Asset_ID,Incident_Type_ID,Hazard_ID,Incident_Date
0,CA000001,INC000861,EMP03113,BU002,DEP002,AST007,IT004,HZ009,2025-07-23
1,CA000002,INC005391,EMP00558,BU003,DEP001,AST009,IT001,HZ002,2022-08-07
2,CA000003,INC005227,EMP02328,BU004,DEP003,AST010,IT002,HZ007,2024-09-19
3,CA000004,INC005192,EMP02814,BU002,DEP005,AST006,IT003,HZ009,2025-03-02
4,CA000005,INC003773,EMP01378,BU003,DEP005,AST009,IT001,HZ005,2023-07-16
5,CA000006,INC003093,EMP01602,BU003,DEP002,AST009,IT001,HZ005,2023-10-18
6,CA000007,INC005735,EMP02712,BU002,DEP004,AST005,IT003,HZ009,2025-02-23
7,CA000008,INC006266,EMP02009,BU001,DEP002,AST003,IT002,HZ006,2024-04-21
8,CA000009,INC000467,EMP01138,BU002,DEP003,AST005,IT001,HZ004,2023-04-01
9,CA000010,INC005335,EMP03872,BU001,DEP001,AST001,IT010,HZ012,2026-06-30

In [318]:
# ============================================================
# STEP 3 — MANAGEMENT ATTRIBUTES
# ============================================================

np.random.seed(42)

# ------------------------------------------------------------
# 1. Corrective Action Type
# ------------------------------------------------------------

action_type_ids = dim_corrective_action[
    "Corrective_Action_Type_ID"
].tolist()

fact_hse_corrective_action["Corrective_Action_Type_ID"] = (
    np.random.choice(
        action_type_ids,
        size=len(fact_hse_corrective_action),
        p=[
            0.20,  # Engineering Control
            0.15,  # Administrative Control
            0.12,  # Procedure / Process Revision
            0.15,  # Training / Competency
            0.10,  # PPE Improvement
            0.13,  # Maintenance / Repair
            0.10,  # Inspection / Monitoring
            0.05   # Emergency Preparedness
        ]
    )
)

# ------------------------------------------------------------
# 2. Priority
# ------------------------------------------------------------

fact_hse_corrective_action["Priority"] = np.random.choice(
    [
        "Critical",
        "High",
        "Medium",
        "Low"
    ],
    size=len(fact_hse_corrective_action),
    p=[
        0.05,
        0.20,
        0.50,
        0.25
    ]
)

# ------------------------------------------------------------
# 3. Responsible Function
# ------------------------------------------------------------

fact_hse_corrective_action["Responsible_Function"] = (
    np.random.choice(
        [
            "Operations",
            "Maintenance",
            "Engineering",
            "HSE",
            "Logistics",
            "Security"
        ],
        size=len(fact_hse_corrective_action),
        p=[
            0.25,
            0.20,
            0.15,
            0.25,
            0.10,
            0.05
        ]
    )
)

# ------------------------------------------------------------
# 4. Investigation Status
# ------------------------------------------------------------

fact_hse_corrective_action["Investigation_Status"] = (
    np.random.choice(
        [
            "Completed",
            "In Progress",
            "Pending"
        ],
        size=len(fact_hse_corrective_action),
        p=[
            0.70,
            0.20,
            0.10
        ]
    )
)

# ============================================================
# CHECK
# ============================================================

print("========== STEP 3 CHECK ==========")

print("\nCorrective Action Type:")
print(
    fact_hse_corrective_action[
        "Corrective_Action_Type_ID"
    ].value_counts().sort_index()
)

print("\nPriority:")
print(
    fact_hse_corrective_action[
        "Priority"
    ].value_counts()
)

print("\nResponsible Function:")
print(
    fact_hse_corrective_action[
        "Responsible_Function"
    ].value_counts()
)

print("\nInvestigation Status:")
print(
    fact_hse_corrective_action[
        "Investigation_Status"
    ].value_counts()
)

print("\nMissing Values:")
print(
    fact_hse_corrective_action[
        [
            "Corrective_Action_Type_ID",
            "Priority",
            "Responsible_Function",
            "Investigation_Status"
        ]
    ].isna().sum()
)

========== STEP 3 CHECK ==========

Corrective Action Type:
Corrective_Action_Type_ID
CA001    632
CA002    444
CA003    354
CA004    450
CA005    323
CA006    392
CA007    296
CA008    169
Name: count, dtype: int64

Priority:
Priority
Medium      1531
Low          743
High         648
Critical     138
Name: count, dtype: int64

Responsible Function:
Responsible_Function
Operations     782
HSE            697
Maintenance    647
Engineering    497
Logistics      312
Security       125
Name: count, dtype: int64

Investigation Status:
Investigation_Status
Completed      2120
In Progress     632
Pending         308
Name: count, dtype: int64

Missing Values:
Corrective_Action_Type_ID    0
Priority                     0
Responsible_Function         0
Investigation_Status         0
dtype: int64

In [319]:
# ============================================================
# STEP 4 — ACTION TIMELINE & CLOSURE STATUS
# REPORTING CUTOFF: JULY 31, 2026
# ============================================================

np.random.seed(42)

reference_date = pd.Timestamp("2026-07-31")

# ------------------------------------------------------------
# 1. Make sure Incident_Date is datetime
# ------------------------------------------------------------

fact_hse_corrective_action["Incident_Date"] = pd.to_datetime(
    fact_hse_corrective_action["Incident_Date"]
)

# ------------------------------------------------------------
# 2. Action Date
# ------------------------------------------------------------
# Action occurs 1–14 days after the incident,
# but cannot go beyond the reporting cutoff.

days_available = (
    reference_date
    - fact_hse_corrective_action["Incident_Date"]
).dt.days

action_delay = np.array([
    np.random.randint(1, min(14, days_available_i) + 1)
    if days_available_i >= 1
    else 0
    for days_available_i in days_available
])

fact_hse_corrective_action["Action_Date"] = (
    fact_hse_corrective_action["Incident_Date"]
    + pd.to_timedelta(action_delay, unit="D")
)

# ------------------------------------------------------------
# 3. Target Closure Days
# ------------------------------------------------------------

def closure_target(priority):

    if priority == "Critical":
        return np.random.randint(7, 31)

    elif priority == "High":
        return np.random.randint(14, 46)

    elif priority == "Medium":
        return np.random.randint(30, 76)

    else:
        return np.random.randint(45, 121)


fact_hse_corrective_action["Target_Closure_Days"] = (
    fact_hse_corrective_action["Priority"]
    .apply(closure_target)
)

# ------------------------------------------------------------
# 4. Due Date
# ------------------------------------------------------------
# Due dates can extend beyond July 31 because they represent
# the deadline assigned to an action.

fact_hse_corrective_action["Due_Date"] = (
    fact_hse_corrective_action["Action_Date"]
    + pd.to_timedelta(
        fact_hse_corrective_action["Target_Closure_Days"],
        unit="D"
    )
)

# ------------------------------------------------------------
# 5. Action Status
# ------------------------------------------------------------

fact_hse_corrective_action["Action_Status"] = np.random.choice(
    [
        "Closed",
        "Open",
        "Overdue"
    ],
    size=len(fact_hse_corrective_action),
    p=[
        0.68,
        0.20,
        0.12
    ]
)

# ------------------------------------------------------------
# 6. Closure Date
# ------------------------------------------------------------
# Closed actions must have closed between Action_Date
# and July 31, 2026.
#
# If an action is too recent to allow a 5-day closure period,
# it will not be assigned a Closed status.

days_available_for_closure = (
    reference_date
    - fact_hse_corrective_action["Action_Date"]
).dt.days

closed_mask = (
    fact_hse_corrective_action["Action_Status"] == "Closed"
)

# Identify closed actions that have at least 5 days available
valid_closed_mask = (
    closed_mask
    & (days_available_for_closure >= 5)
)

# Closed actions without enough time to have closed
# are converted to Open.
fact_hse_corrective_action.loc[
    closed_mask & ~valid_closed_mask,
    "Action_Status"
] = "Open"

# Recalculate closed mask after adjustment
closed_mask = (
    fact_hse_corrective_action["Action_Status"] == "Closed"
)

days_available_for_closure = (
    reference_date
    - fact_hse_corrective_action["Action_Date"]
).dt.days

# Start with no closure dates
fact_hse_corrective_action["Closure_Date"] = pd.NaT

# Generate closure dates only for valid closed actions
for idx in fact_hse_corrective_action.index[closed_mask]:

    max_days = int(
        days_available_for_closure.loc[idx]
    )

    closure_days = np.random.randint(
        5,
        max_days + 1
    )

    fact_hse_corrective_action.loc[
        idx,
        "Closure_Date"
    ] = (
        fact_hse_corrective_action.loc[
            idx,
            "Action_Date"
        ]
        + pd.Timedelta(days=closure_days)
    )

# ------------------------------------------------------------
# 7. Days Open
# ------------------------------------------------------------

fact_hse_corrective_action["Days_Open"] = np.where(

    fact_hse_corrective_action["Closure_Date"].notna(),

    (
        fact_hse_corrective_action["Closure_Date"]
        - fact_hse_corrective_action["Action_Date"]
    ).dt.days,

    (
        reference_date
        - fact_hse_corrective_action["Action_Date"]
    ).dt.days
)

# ------------------------------------------------------------
# 8. Overdue Flag
# ------------------------------------------------------------

fact_hse_corrective_action["Overdue_Flag"] = np.where(
    fact_hse_corrective_action["Action_Status"] == "Overdue",
    1,
    0
)

# ------------------------------------------------------------
# 9. Closed Flag
# ------------------------------------------------------------

fact_hse_corrective_action["Closed_Flag"] = np.where(
    fact_hse_corrective_action["Action_Status"] == "Closed",
    1,
    0
)

# ============================================================
# STEP 4 CHECK
# ============================================================

print("========== STEP 4 CHECK ==========")

print("\nAction Status:")
print(
    fact_hse_corrective_action[
        "Action_Status"
    ].value_counts()
)

print("\nMinimum Action Date:",
      fact_hse_corrective_action["Action_Date"].min())

print("Maximum Action Date:",
      fact_hse_corrective_action["Action_Date"].max())

print("\nMinimum Due Date:",
      fact_hse_corrective_action["Due_Date"].min())

print("Maximum Due Date:",
      fact_hse_corrective_action["Due_Date"].max())

print("\nMinimum Closure Date:",
      fact_hse_corrective_action["Closure_Date"].min())

print("Maximum Closure Date:",
      fact_hse_corrective_action["Closure_Date"].max())

print("\nMissing Action Dates:",
      fact_hse_corrective_action["Action_Date"].isna().sum())

print("Missing Due Dates:",
      fact_hse_corrective_action["Due_Date"].isna().sum())

print("Missing Closure Dates:",
      fact_hse_corrective_action["Closure_Date"].isna().sum())

print("\nNegative Days Open:",
      (
          fact_hse_corrective_action["Days_Open"] < 0
      ).sum())

print("Minimum Days Open:",
      fact_hse_corrective_action["Days_Open"].min())

print("Maximum Days Open:",
      fact_hse_corrective_action["Days_Open"].max())

print("\nAction Dates After Reporting Cutoff:",
      (
          fact_hse_corrective_action["Action_Date"]
          > reference_date
      ).sum())

print("\nClosure Dates After Reporting Cutoff:",
      (
          fact_hse_corrective_action["Closure_Date"]
          > reference_date
      ).sum())

print("\nOverdue Flag:")
print(
    fact_hse_corrective_action[
        "Overdue_Flag"
    ].value_counts()
)

print("\nClosed Flag:")
print(
    fact_hse_corrective_action[
        "Closed_Flag"
    ].value_counts()
)

========== STEP 4 CHECK ==========

Action Status:
Action_Status
Closed     2107
Open        590
Overdue     363
Name: count, dtype: int64

Minimum Action Date: 2022-01-06 00:00:00
Maximum Action Date: 2026-07-31 00:00:00

Minimum Due Date: 2022-02-03 00:00:00
Maximum Due Date: 2026-11-18 00:00:00

Minimum Closure Date: 2022-03-20 00:00:00
Maximum Closure Date: 2026-07-31 00:00:00

Missing Action Dates: 0
Missing Due Dates: 0
Missing Closure Dates: 953

Negative Days Open: 0
Minimum Days Open: 0.0
Maximum Days Open: 1664.0

Action Dates After Reporting Cutoff: 0

Closure Dates After Reporting Cutoff: 0

Overdue Flag:
Overdue_Flag
0    2697
1     363
Name: count, dtype: int64

Closed Flag:
Closed_Flag
1    2107
0     953
Name: count, dtype: int64

In [320]:
# ============================================================
# STEP 5 — VALIDATE FACT_HSE_CORRECTIVE_ACTION
# ============================================================

print("========== STEP 5 — CORRECTIVE ACTION VALIDATION ==========")

# ------------------------------------------------------------
# 1. UNIQUE CORRECTIVE ACTION IDs
# ------------------------------------------------------------

duplicate_action_ids = (
    fact_hse_corrective_action["Corrective_Action_ID"]
    .duplicated()
    .sum()
)

print("\n1. Duplicate Corrective Action IDs:")
print(duplicate_action_ids)


# ------------------------------------------------------------
# 2. INCIDENT IDs EXIST IN FACT_HSE_INCIDENT
# ------------------------------------------------------------

valid_incident_ids = set(
    fact_hse_incident["Incident_ID"]
)

invalid_incident_ids = (
    ~fact_hse_corrective_action["Incident_ID"]
    .isin(valid_incident_ids)
).sum()

print("\n2. Invalid Incident IDs:")
print(invalid_incident_ids)


# ------------------------------------------------------------
# 3. EMPLOYEE IDs EXIST IN DIM_EMPLOYEE
# ------------------------------------------------------------

valid_employee_ids = set(
    dim_employee["Employee_ID"]
)

invalid_employee_ids = (
    ~fact_hse_corrective_action["Employee_ID"]
    .isin(valid_employee_ids)
).sum()

print("\n3. Invalid Employee IDs:")
print(invalid_employee_ids)


# ------------------------------------------------------------
# 4. BUSINESS UNIT IDs
# ------------------------------------------------------------

valid_bu_ids = set(
    dim_business_unit["BusinessUnit_ID"]
)

invalid_bu_ids = (
    ~fact_hse_corrective_action["BusinessUnit_ID"]
    .isin(valid_bu_ids)
).sum()

print("\n4. Invalid Business Unit IDs:")
print(invalid_bu_ids)


# ------------------------------------------------------------
# 5. DEPARTMENT IDs
# ------------------------------------------------------------

valid_department_ids = set(
    dim_department["Department_ID"]
)

invalid_department_ids = (
    ~fact_hse_corrective_action["Department_ID"]
    .isin(valid_department_ids)
).sum()

print("\n5. Invalid Department IDs:")
print(invalid_department_ids)


# ------------------------------------------------------------
# 6. ASSET IDs
# ------------------------------------------------------------

valid_asset_ids = set(
    dim_asset["Asset_ID"]
)

invalid_asset_ids = (
    ~fact_hse_corrective_action["Asset_ID"]
    .isin(valid_asset_ids)
).sum()

print("\n6. Invalid Asset IDs:")
print(invalid_asset_ids)


# ------------------------------------------------------------
# 7. CORRECTIVE ACTION TYPE IDs
# ------------------------------------------------------------

valid_action_type_ids = set(
    dim_corrective_action[
        "Corrective_Action_Type_ID"
    ]
)

invalid_action_type_ids = (
    ~fact_hse_corrective_action[
        "Corrective_Action_Type_ID"
    ].isin(valid_action_type_ids)
).sum()

print("\n7. Invalid Corrective Action Type IDs:")
print(invalid_action_type_ids)


# ------------------------------------------------------------
# 8. MISSING VALUES
# ------------------------------------------------------------

print("\n8. Missing Values:")

print(
    fact_hse_corrective_action.isna().sum()
)


# ------------------------------------------------------------
# 9. ACTION DATE CANNOT BE BEFORE INCIDENT DATE
# ------------------------------------------------------------

action_before_incident = (
    fact_hse_corrective_action["Action_Date"]
    < fact_hse_corrective_action["Incident_Date"]
).sum()

print("\n9. Action Date Before Incident Date:")
print(action_before_incident)


# ------------------------------------------------------------
# 10. ACTION DATE AFTER REPORTING CUTOFF
# ------------------------------------------------------------

reference_date = pd.Timestamp("2026-07-31")

future_action_dates = (
    fact_hse_corrective_action["Action_Date"]
    > reference_date
).sum()

print("\n10. Action Dates After Reporting Cutoff:")
print(future_action_dates)


# ------------------------------------------------------------
# 11. DUE DATE BEFORE ACTION DATE
# ------------------------------------------------------------

invalid_due_dates = (
    fact_hse_corrective_action["Due_Date"]
    < fact_hse_corrective_action["Action_Date"]
).sum()

print("\n11. Due Dates Before Action Dates:")
print(invalid_due_dates)


# ------------------------------------------------------------
# 12. CLOSED ACTIONS MUST HAVE CLOSURE DATES
# ------------------------------------------------------------

closed_missing_closure = (
    (
        fact_hse_corrective_action["Action_Status"]
        == "Closed"
    )
    &
    (
        fact_hse_corrective_action["Closure_Date"]
        .isna()
    )
).sum()

print("\n12. Closed Actions Missing Closure Date:")
print(closed_missing_closure)


# ------------------------------------------------------------
# 13. OPEN / OVERDUE ACTIONS MUST NOT HAVE CLOSURE DATES
# ------------------------------------------------------------

open_overdue_with_closure = (
    fact_hse_corrective_action[
        "Action_Status"
    ].isin(["Open", "Overdue"])
    &
    fact_hse_corrective_action[
        "Closure_Date"
    ].notna()
).sum()

print("\n13. Open/Overdue Actions With Closure Date:")
print(open_overdue_with_closure)


# ------------------------------------------------------------
# 14. CLOSURE DATE CANNOT BE BEFORE ACTION DATE
# ------------------------------------------------------------

closure_before_action = (
    fact_hse_corrective_action["Closure_Date"]
    < fact_hse_corrective_action["Action_Date"]
).sum()

print("\n14. Closure Date Before Action Date:")
print(closure_before_action)


# ------------------------------------------------------------
# 15. CLOSURE DATE AFTER REPORTING CUTOFF
# ------------------------------------------------------------

future_closure_dates = (
    fact_hse_corrective_action["Closure_Date"]
    > reference_date
).sum()

print("\n15. Closure Dates After Reporting Cutoff:")
print(future_closure_dates)


# ------------------------------------------------------------
# 16. NEGATIVE DAYS OPEN
# ------------------------------------------------------------

negative_days_open = (
    fact_hse_corrective_action["Days_Open"]
    < 0
).sum()

print("\n16. Negative Days Open:")
print(negative_days_open)


# ------------------------------------------------------------
# 17. OVERDUE FLAG MUST MATCH STATUS
# ------------------------------------------------------------

incorrect_overdue_flags = (
    fact_hse_corrective_action["Overdue_Flag"]
    != (
        fact_hse_corrective_action["Action_Status"]
        == "Overdue"
    ).astype(int)
).sum()

print("\n17. Incorrect Overdue Flags:")
print(incorrect_overdue_flags)


# ------------------------------------------------------------
# 18. CLOSED FLAG MUST MATCH STATUS
# ------------------------------------------------------------

incorrect_closed_flags = (
    fact_hse_corrective_action["Closed_Flag"]
    != (
        fact_hse_corrective_action["Action_Status"]
        == "Closed"
    ).astype(int)
).sum()

print("\n18. Incorrect Closed Flags:")
print(incorrect_closed_flags)


# ------------------------------------------------------------
# 19. ACTION STATUS VALUES
# ------------------------------------------------------------

valid_statuses = {
    "Closed",
    "Open",
    "Overdue"
}

invalid_statuses = (
    ~fact_hse_corrective_action[
        "Action_Status"
    ].isin(valid_statuses)
).sum()

print("\n19. Invalid Action Status Values:")
print(invalid_statuses)


# ------------------------------------------------------------
# 20. FINAL ROW COUNT
# ------------------------------------------------------------

print("\n20. Final Row Count:")
print(len(fact_hse_corrective_action))

print("\n========== STEP 5 COMPLETE ==========")

========== STEP 5 — CORRECTIVE ACTION VALIDATION ==========

1. Duplicate Corrective Action IDs:
0

2. Invalid Incident IDs:
0

3. Invalid Employee IDs:
0

4. Invalid Business Unit IDs:
0

5. Invalid Department IDs:
0

6. Invalid Asset IDs:
0

7. Invalid Corrective Action Type IDs:
0

8. Missing Values:
Corrective_Action_ID           0
Incident_ID                    0
Employee_ID                    0
BusinessUnit_ID                0
Department_ID                  0
Asset_ID                       0
Incident_Type_ID               0
Hazard_ID                      0
Incident_Date                  0
Corrective_Action_Type_ID      0
Priority                       0
Responsible_Function           0
Investigation_Status           0
Action_Date                    0
Target_Closure_Days            0
Due_Date                       0
Action_Status                  0
Closure_Date                 953
Days_Open                      0
Overdue_Flag                   0
Closed_Flag                    0
dtype: int64

9. Action Date Before Incident Date:
0

10. Action Dates After Reporting Cutoff:
0

11. Due Dates Before Action Dates:
0

12. Closed Actions Missing Closure Date:
0

13. Open/Overdue Actions With Closure Date:
0

14. Closure Date Before Action Date:
0

15. Closure Dates After Reporting Cutoff:
0

16. Negative Days Open:
0

17. Incorrect Overdue Flags:
0

18. Incorrect Closed Flags:
0

19. Invalid Action Status Values:
0

20. Final Row Count:
3060

========== STEP 5 COMPLETE ==========

In [321]:
# ============================================================
# STEP 6 — ACTION EFFECTIVENESS
# ============================================================

np.random.seed(42)

reference_date = pd.Timestamp("2026-07-31")

# ------------------------------------------------------------
# 1. Effectiveness Status
# ------------------------------------------------------------

fact_hse_corrective_action["Effectiveness_Status"] = np.where(
    fact_hse_corrective_action["Action_Status"] == "Closed",

    np.random.choice(
        [
            "Effective",
            "Partially Effective",
            "Ineffective"
        ],
        size=len(fact_hse_corrective_action),
        p=[
            0.70,
            0.25,
            0.05
        ]
    ),

    "Not Yet Verified"
)

# ------------------------------------------------------------
# 2. Verification Date
# ------------------------------------------------------------

fact_hse_corrective_action["Verification_Date"] = pd.NaT

closed_indices = fact_hse_corrective_action.index[
    fact_hse_corrective_action["Action_Status"] == "Closed"
]

for idx in closed_indices:

    closure_date = fact_hse_corrective_action.loc[
        idx,
        "Closure_Date"
    ]

    # Verification can occur 1–30 days after closure,
    # but cannot exceed July 31, 2026.

    days_available = (
        reference_date - closure_date
    ).days

    if days_available >= 1:

        verification_days = np.random.randint(
            1,
            min(30, days_available) + 1
        )

        fact_hse_corrective_action.loc[
            idx,
            "Verification_Date"
        ] = (
            closure_date
            + pd.Timedelta(days=verification_days)
        )

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print("========== STEP 6 CHECK ==========")

print("\nEffectiveness Status:")
print(
    fact_hse_corrective_action[
        "Effectiveness_Status"
    ].value_counts()
)

print("\nMissing Verification Dates:")
print(
    fact_hse_corrective_action[
        "Verification_Date"
    ].isna().sum()
)

print("\nVerification Dates After Cutoff:")
print(
    (
        fact_hse_corrective_action[
            "Verification_Date"
        ] > reference_date
    ).sum()
)

print("\nVerification Before Closure:")
print(
    (
        fact_hse_corrective_action[
            "Verification_Date"
        ]
        <
        fact_hse_corrective_action[
            "Closure_Date"
        ]
    ).sum()
)

========== STEP 6 CHECK ==========

Effectiveness Status:
Effectiveness_Status
Effective              1448
Not Yet Verified        953
Partially Effective     538
Ineffective             121
Name: count, dtype: int64

Missing Verification Dates:
960

Verification Dates After Cutoff:
0

Verification Before Closure:
0

In [322]:
# ============================================================
# STEP 7 — CORRECTIVE ACTION COST
# ============================================================

np.random.seed(42)

# ------------------------------------------------------------
# Cost ranges by Corrective Action Type
# ------------------------------------------------------------

cost_ranges = {
    "CA001": (15000, 250000),   # Engineering Control
    "CA002": (2000, 50000),     # Administrative Control
    "CA003": (3000, 75000),     # Procedure / Process Revision
    "CA004": (1000, 40000),     # Training / Competency
    "CA005": (500, 25000),      # PPE Improvement
    "CA006": (5000, 150000),    # Maintenance / Repair
    "CA007": (1000, 50000),     # Inspection / Monitoring
    "CA008": (5000, 100000)     # Emergency Preparedness
}

def generate_action_cost(action_type):

    low, high = cost_ranges[action_type]

    return round(
        np.random.uniform(low, high),
        2
    )

fact_hse_corrective_action["Corrective_Action_Cost"] = (
    fact_hse_corrective_action[
        "Corrective_Action_Type_ID"
    ].apply(generate_action_cost)
)

# ------------------------------------------------------------
# Priority adjustment
# ------------------------------------------------------------

priority_multiplier = {
    "Critical": 1.50,
    "High": 1.25,
    "Medium": 1.00,
    "Low": 0.75
}

fact_hse_corrective_action["Corrective_Action_Cost"] = (
    fact_hse_corrective_action[
        "Corrective_Action_Cost"
    ]
    *
    fact_hse_corrective_action[
        "Priority"
    ].map(priority_multiplier)
).round(2)

# ============================================================
# STEP 7 CHECK
# ============================================================

print("========== STEP 7 CHECK ==========")

print(
    "\nTotal Corrective Action Cost:",
    round(
        fact_hse_corrective_action[
            "Corrective_Action_Cost"
        ].sum(),
        2
    )
)

print(
    "\nAverage Corrective Action Cost:",
    round(
        fact_hse_corrective_action[
            "Corrective_Action_Cost"
        ].mean(),
        2
    )
)

print(
    "\nMinimum Corrective Action Cost:",
    fact_hse_corrective_action[
        "Corrective_Action_Cost"
    ].min()
)

print(
    "Maximum Corrective Action Cost:",
    fact_hse_corrective_action[
        "Corrective_Action_Cost"
    ].max()
)

print(
    "\nMissing Costs:",
    fact_hse_corrective_action[
        "Corrective_Action_Cost"
    ].isna().sum()
)

print(
    "Zero/Negative Costs:",
    (
        fact_hse_corrective_action[
            "Corrective_Action_Cost"
        ] <= 0
    ).sum()
)

print("\nCost by Priority:")
print(
    fact_hse_corrective_action.groupby(
        "Priority"
    )["Corrective_Action_Cost"]
    .agg(["count", "mean", "sum"])
    .round(2)
)

print("\nCost by Corrective Action Type:")
print(
    fact_hse_corrective_action.groupby(
        "Corrective_Action_Type_ID"
    )["Corrective_Action_Cost"]
    .agg(["count", "mean", "sum"])
    .round(2)
)

========== STEP 7 CHECK ==========

Total Corrective Action Cost: 135356622.8

Average Corrective Action Cost: 44234.19

Minimum Corrective Action Cost: 8717.09
Maximum Corrective Action Cost: 189790.08

Missing Costs: 0
Zero/Negative Costs: 0

Cost by Priority:
          count      mean          sum
Priority
Critical    138  59671.72   8234697.54
High        648  54175.88  35105969.44
Low         743  33909.58  25194816.11
Medium     1531  43645.42  66821139.71

Cost by Corrective Action Type:
                           count       mean          sum
Corrective_Action_Type_ID
CA001                        632   38142.19  24105862.80
CA002                        444   15389.85   6833091.47
CA003                        354   32614.03  11545365.34
CA004                        450   22743.47  10234560.89
CA005                        323   17522.47   5659758.29
CA006                        392  119359.84  46789055.71
CA007                        296   46331.11  13714007.58
CA008                        169   97484.74  16474920.72

In [323]:
# ============================================================
# STEP 8 — FINAL FACT_HSE_CORRECTIVE_ACTION VALIDATION
# ============================================================

print("============================================================")
print(" FINAL FACT_HSE_CORRECTIVE_ACTION VALIDATION")
print("============================================================")

# ------------------------------------------------------------
# 1. BASIC STRUCTURE
# ------------------------------------------------------------

print("\n========== 1. BASIC STRUCTURE ==========")

print("Total Rows:",
      len(fact_hse_corrective_action))

print("Total Columns:",
      len(fact_hse_corrective_action.columns))

print("Unique Action IDs:",
      fact_hse_corrective_action[
          "Corrective_Action_ID"
      ].nunique())

# ------------------------------------------------------------
# 2. STATUS DISTRIBUTION
# ------------------------------------------------------------

print("\n========== 2. ACTION STATUS ==========")

print(
    fact_hse_corrective_action[
        "Action_Status"
    ].value_counts()
)

# ------------------------------------------------------------
# 3. PRIORITY DISTRIBUTION
# ------------------------------------------------------------

print("\n========== 3. PRIORITY ==========")

print(
    fact_hse_corrective_action[
        "Priority"
    ].value_counts()
)

# ------------------------------------------------------------
# 4. CLOSURE RATE
# ------------------------------------------------------------

total_actions = len(
    fact_hse_corrective_action
)

closed_actions = (
    fact_hse_corrective_action[
        "Action_Status"
    ] == "Closed"
).sum()

overdue_actions = (
    fact_hse_corrective_action[
        "Action_Status"
    ] == "Overdue"
).sum()

open_actions = (
    fact_hse_corrective_action[
        "Action_Status"
    ] == "Open"
).sum()

closure_rate = (
    closed_actions / total_actions * 100
)

overdue_rate = (
    overdue_actions / total_actions * 100
)

print("\n========== 4. CLOSURE / OVERDUE RATES ==========")

print(
    "Closure Rate:",
    round(closure_rate, 2),
    "%"
)

print(
    "Overdue Rate:",
    round(overdue_rate, 2),
    "%"
)

# ------------------------------------------------------------
# 5. DAYS TO CLOSURE
# ------------------------------------------------------------

print("\n========== 5. DAYS OPEN ==========")

print(
    fact_hse_corrective_action[
        "Days_Open"
    ].describe()
)

print(
    "\nAverage Days Open:",
    round(
        fact_hse_corrective_action[
            "Days_Open"
        ].mean(),
        2
    )
)

# ------------------------------------------------------------
# 6. CRITICAL / HIGH OPEN ACTIONS
# ------------------------------------------------------------

critical_open = (
    (
        fact_hse_corrective_action[
            "Priority"
        ] == "Critical"
    )
    &
    (
        fact_hse_corrective_action[
            "Action_Status"
        ].isin(["Open", "Overdue"])
    )
).sum()

high_open = (
    (
        fact_hse_corrective_action[
            "Priority"
        ] == "High"
    )
    &
    (
        fact_hse_corrective_action[
            "Action_Status"
        ].isin(["Open", "Overdue"])
    )
).sum()

print("\n========== 6. HIGH-RISK OPEN ACTIONS ==========")

print(
    "Critical Open/Overdue:",
    critical_open
)

print(
    "High Open/Overdue:",
    high_open
)

# ------------------------------------------------------------
# 7. EFFECTIVENESS
# ------------------------------------------------------------

print("\n========== 7. EFFECTIVENESS ==========")

print(
    fact_hse_corrective_action[
        "Effectiveness_Status"
    ].value_counts()
)

# ------------------------------------------------------------
# 8. COST
# ------------------------------------------------------------

print("\n========== 8. CORRECTIVE ACTION COST ==========")

print(
    "Total Cost:",
    round(
        fact_hse_corrective_action[
            "Corrective_Action_Cost"
        ].sum(),
        2
    )
)

print(
    "Average Cost:",
    round(
        fact_hse_corrective_action[
            "Corrective_Action_Cost"
        ].mean(),
        2
    )
)

# ------------------------------------------------------------
# 9. DUPLICATES
# ------------------------------------------------------------

print("\n========== 9. DUPLICATES ==========")

print(
    "Duplicate Action IDs:",
    fact_hse_corrective_action[
        "Corrective_Action_ID"
    ].duplicated().sum()
)

# ------------------------------------------------------------
# 10. MISSING VALUES
# ------------------------------------------------------------

print("\n========== 10. MISSING VALUES ==========")

print(
    fact_hse_corrective_action.isna().sum()
)

# ------------------------------------------------------------
# 11. REFERENTIAL INTEGRITY
# ------------------------------------------------------------

print("\n========== 11. REFERENTIAL INTEGRITY ==========")

print(
    "Invalid Incident IDs:",
    (
        ~fact_hse_corrective_action[
            "Incident_ID"
        ].isin(
            fact_hse_incident[
                "Incident_ID"
            ]
        )
    ).sum()
)

print(
    "Invalid Employee IDs:",
    (
        ~fact_hse_corrective_action[
            "Employee_ID"
        ].isin(
            dim_employee[
                "Employee_ID"
            ]
        )
    ).sum()
)

print(
    "Invalid BusinessUnit IDs:",
    (
        ~fact_hse_corrective_action[
            "BusinessUnit_ID"
        ].isin(
            dim_business_unit[
                "BusinessUnit_ID"
            ]
        )
    ).sum()
)

print(
    "Invalid Department IDs:",
    (
        ~fact_hse_corrective_action[
            "Department_ID"
        ].isin(
            dim_department[
                "Department_ID"
            ]
        )
    ).sum()
)

print(
    "Invalid Asset IDs:",
    (
        ~fact_hse_corrective_action[
            "Asset_ID"
        ].isin(
            dim_asset[
                "Asset_ID"
            ]
        )
    ).sum()
)

print(
    "Invalid Action Type IDs:",
    (
        ~fact_hse_corrective_action[
            "Corrective_Action_Type_ID"
        ].isin(
            dim_corrective_action[
                "Corrective_Action_Type_ID"
            ]
        )
    ).sum()
)

# ------------------------------------------------------------
# 12. TIMELINE VALIDATION
# ------------------------------------------------------------

reference_date = pd.Timestamp("2026-07-31")

print("\n========== 12. TIMELINE VALIDATION ==========")

print(
    "Action Before Incident:",
    (
        fact_hse_corrective_action[
            "Action_Date"
        ]
        <
        fact_hse_corrective_action[
            "Incident_Date"
        ]
    ).sum()
)

print(
    "Action After Cutoff:",
    (
        fact_hse_corrective_action[
            "Action_Date"
        ] > reference_date
    ).sum()
)

print(
    "Due Before Action:",
    (
        fact_hse_corrective_action[
            "Due_Date"
        ]
        <
        fact_hse_corrective_action[
            "Action_Date"
        ]
    ).sum()
)

print(
    "Closed Without Closure Date:",
    (
        (
            fact_hse_corrective_action[
                "Action_Status"
            ] == "Closed"
        )
        &
        fact_hse_corrective_action[
            "Closure_Date"
        ].isna()
    ).sum()
)

print(
    "Open/Overdue With Closure Date:",
    (
        fact_hse_corrective_action[
            "Action_Status"
        ].isin(["Open", "Overdue"])
        &
        fact_hse_corrective_action[
            "Closure_Date"
        ].notna()
    ).sum()
)

print(
    "Closure Before Action:",
    (
        fact_hse_corrective_action[
            "Closure_Date"
        ]
        <
        fact_hse_corrective_action[
            "Action_Date"
        ]
    ).sum()
)

print(
    "Closure After Cutoff:",
    (
        fact_hse_corrective_action[
            "Closure_Date"
        ] > reference_date
    ).sum()
)

print(
    "Negative Days Open:",
    (
        fact_hse_corrective_action[
            "Days_Open"
        ] < 0
    ).sum()
)

# ------------------------------------------------------------
# 13. FLAG VALIDATION
# ------------------------------------------------------------

print("\n========== 13. FLAG VALIDATION ==========")

print(
    "Incorrect Overdue Flags:",
    (
        fact_hse_corrective_action[
            "Overdue_Flag"
        ]
        !=
        (
            fact_hse_corrective_action[
                "Action_Status"
            ] == "Overdue"
        ).astype(int)
    ).sum()
)

print(
    "Incorrect Closed Flags:",
    (
        fact_hse_corrective_action[
            "Closed_Flag"
        ]
        !=
        (
            fact_hse_corrective_action[
                "Action_Status"
            ] == "Closed"
        ).astype(int)
    ).sum()
)

# ------------------------------------------------------------
# 14. EFFECTIVENESS VALIDATION
# ------------------------------------------------------------

print("\n========== 14. EFFECTIVENESS VALIDATION ==========")

print(
    "Verification After Cutoff:",
    (
        fact_hse_corrective_action[
            "Verification_Date"
        ] > reference_date
    ).sum()
)

print(
    "Verification Before Closure:",
    (
        fact_hse_corrective_action[
            "Verification_Date"
        ]
        <
        fact_hse_corrective_action[
            "Closure_Date"
        ]
    ).sum()
)

# ------------------------------------------------------------
# 15. FINAL SUMMARY
# ------------------------------------------------------------

print("\n============================================================")
print(" FINAL VALIDATION COMPLETE")
print("============================================================")

============================================================
 FINAL FACT_HSE_CORRECTIVE_ACTION VALIDATION
============================================================

========== 1. BASIC STRUCTURE ==========
Total Rows: 3060
Total Columns: 24
Unique Action IDs: 3060

========== 2. ACTION STATUS ==========
Action_Status
Closed     2107
Open        590
Overdue     363
Name: count, dtype: int64

========== 3. PRIORITY ==========
Priority
Medium      1531
Low          743
High         648
Critical     138
Name: count, dtype: int64

========== 4. CLOSURE / OVERDUE RATES ==========
Closure Rate: 68.86 %
Overdue Rate: 11.86 %

========== 5. DAYS OPEN ==========
count    3060.000000
mean      547.256209
std       448.762743
min         0.000000
25%       169.000000
50%       438.000000
75%       841.250000
max      1664.000000
Name: Days_Open, dtype: float64

Average Days Open: 547.26

========== 6. HIGH-RISK OPEN ACTIONS ==========
Critical Open/Overdue: 44
High Open/Overdue: 200

========== 7. EFFECTIVENESS ==========
Effectiveness_Status
Effective              1448
Not Yet Verified        953
Partially Effective     538
Ineffective             121
Name: count, dtype: int64

========== 8. CORRECTIVE ACTION COST ==========
Total Cost: 135356622.8
Average Cost: 44234.19

========== 9. DUPLICATES ==========
Duplicate Action IDs: 0

========== 10. MISSING VALUES ==========
Corrective_Action_ID           0
Incident_ID                    0
Employee_ID                    0
BusinessUnit_ID                0
Department_ID                  0
Asset_ID                       0
Incident_Type_ID               0
Hazard_ID                      0
Incident_Date                  0
Corrective_Action_Type_ID      0
Priority                       0
Responsible_Function           0
Investigation_Status           0
Action_Date                    0
Target_Closure_Days            0
Due_Date                       0
Action_Status                  0
Closure_Date                 953
Days_Open                      0
Overdue_Flag                   0
Closed_Flag                    0
Effectiveness_Status           0
Verification_Date            960
Corrective_Action_Cost         0
dtype: int64

========== 11. REFERENTIAL INTEGRITY ==========
Invalid Incident IDs: 0
Invalid Employee IDs: 0
Invalid BusinessUnit IDs: 0
Invalid Department IDs: 0
Invalid Asset IDs: 0
Invalid Action Type IDs: 0

========== 12. TIMELINE VALIDATION ==========
Action Before Incident: 0
Action After Cutoff: 0
Due Before Action: 0
Closed Without Closure Date: 0
Open/Overdue With Closure Date: 0
Closure Before Action: 0
Closure After Cutoff: 0
Negative Days Open: 0

========== 13. FLAG VALIDATION ==========
Incorrect Overdue Flags: 0
Incorrect Closed Flags: 0

========== 14. EFFECTIVENESS VALIDATION ==========
Verification After Cutoff: 0
Verification Before Closure: 0

============================================================
 FINAL VALIDATION COMPLETE
============================================================

In [324]:
# ============================================================
# STEP 9 — FINAL COLUMN ORDER
# ============================================================

final_column_order = [
    "Corrective_Action_ID",
    "Incident_ID",
    "Employee_ID",
    "BusinessUnit_ID",
    "Department_ID",
    "Asset_ID",
    "Incident_Type_ID",
    "Hazard_ID",
    "Corrective_Action_Type_ID",
    "Priority",
    "Responsible_Function",
    "Investigation_Status",
    "Incident_Date",
    "Action_Date",
    "Target_Closure_Days",
    "Due_Date",
    "Action_Status",
    "Closure_Date",
    "Days_Open",
    "Overdue_Flag",
    "Closed_Flag",
    "Effectiveness_Status",
    "Verification_Date",
    "Corrective_Action_Cost"
]

fact_hse_corrective_action = (
    fact_hse_corrective_action[
        final_column_order
    ]
)

print("========== STEP 9 CHECK ==========")

print("Rows:",
      len(fact_hse_corrective_action))

print("Columns:",
      len(fact_hse_corrective_action.columns))

print("\nFinal Column Order:")
print(
    fact_hse_corrective_action.columns.tolist()
)

print("\nMissing Columns:")
print(
    set(final_column_order)
    - set(fact_hse_corrective_action.columns)
)

print("\nExtra Columns:")
print(
    set(fact_hse_corrective_action.columns)
    - set(final_column_order)
)

display(
    fact_hse_corrective_action.head(10)
)

========== STEP 9 CHECK ==========
Rows: 3060
Columns: 24

Final Column Order:
['Corrective_Action_ID', 'Incident_ID', 'Employee_ID', 'BusinessUnit_ID', 'Department_ID', 'Asset_ID', 'Incident_Type_ID', 'Hazard_ID', 'Corrective_Action_Type_ID', 'Priority', 'Responsible_Function', 'Investigation_Status', 'Incident_Date', 'Action_Date', 'Target_Closure_Days', 'Due_Date', 'Action_Status', 'Closure_Date', 'Days_Open', 'Overdue_Flag', 'Closed_Flag', 'Effectiveness_Status', 'Verification_Date', 'Corrective_Action_Cost']

Missing Columns:
set()

Extra Columns:
set()

,Corrective_Action_ID,Incident_ID,Employee_ID,BusinessUnit_ID,Department_ID,Asset_ID,Incident_Type_ID,Hazard_ID,Corrective_Action_Type_ID,Priority,...,Target_Closure_Days,Due_Date,Action_Status,Closure_Date,Days_Open,Overdue_Flag,Closed_Flag,Effectiveness_Status,Verification_Date,Corrective_Action_Cost
0,CA000001,INC000861,EMP03113,BU002,DEP002,AST007,IT004,HZ009,CA003,Medium,...,65,2025-10-03,Closed,2025-12-17,140.0,0,1,Effective,2026-01-13,29966.89
1,CA000002,INC005391,EMP00558,BU003,DEP001,AST009,IT001,HZ002,CA008,High,...,41,2022-09-21,Closed,2025-06-08,1032.0,0,1,Ineffective,2025-06-17,119147.32
2,CA000003,INC005227,EMP02328,BU004,DEP003,AST010,IT002,HZ007,CA006,Medium,...,67,2024-12-08,Closed,2024-11-22,51.0,0,1,Partially Effective,2024-12-14,111139.12
3,CA000004,INC005192,EMP02814,BU002,DEP005,AST006,IT003,HZ009,CA004,Medium,...,68,2025-05-20,Open,NaT,505.0,0,0,Not Yet Verified,NaT,24347.68
4,CA000005,INC003773,EMP01378,BU003,DEP005,AST009,IT001,HZ005,CA001,Medium,...,66,2023-09-28,Open,NaT,1103.0,0,0,Not Yet Verified,NaT,51664.38
5,CA000006,INC003093,EMP01602,BU003,DEP002,AST009,IT001,HZ005,CA001,Medium,...,64,2024-01-03,Closed,2024-02-06,98.0,0,1,Effective,2024-02-26,51658.71
6,CA000007,INC005735,EMP02712,BU002,DEP004,AST005,IT003,HZ009,CA001,Critical,...,13,2025-03-13,Closed,2025-10-03,217.0,0,1,Effective,2025-10-15,42974.48
7,CA000008,INC006266,EMP02009,BU001,DEP002,AST003,IT002,HZ006,CA007,Low,...,71,2024-07-08,Closed,2025-07-12,440.0,0,1,Partially Effective,2025-07-31,32581.97
8,CA000009,INC000467,EMP01138,BU002,DEP003,AST005,IT001,HZ004,CA004,Medium,...,57,2023-06-07,Closed,2025-08-14,856.0,0,1,Effective,2025-09-03,24443.49
9,CA000010,INC005335,EMP03872,BU001,DEP001,AST001,IT010,HZ012,CA005,Medium,...,51,2026-08-23,Closed,2026-07-11,8.0,0,1,Partially Effective,2026-07-14,17847.78

In [325]:
# ============================================================
# STEP 9 — TIMELINE SPOT CHECK
# ============================================================

reference_date = pd.Timestamp("2026-07-31")

print("========== STEP 9 TIMELINE SPOT CHECK ==========")

# 1. Action dates after cutoff
future_actions = fact_hse_corrective_action[
    fact_hse_corrective_action["Action_Date"] > reference_date
]

print("\nAction Dates After July 31, 2026:")
print("Count:", len(future_actions))

display(
    future_actions[
        [
            "Corrective_Action_ID",
            "Incident_ID",
            "Incident_Date",
            "Action_Date",
            "Due_Date",
            "Closure_Date",
            "Action_Status",
            "Days_Open"
        ]
    ].head(20)
)


# 2. Closure before action
closure_before_action = fact_hse_corrective_action[
    fact_hse_corrective_action["Closure_Date"]
    < fact_hse_corrective_action["Action_Date"]
]

print("\nClosure Dates Before Action Dates:")
print("Count:", len(closure_before_action))

display(
    closure_before_action[
        [
            "Corrective_Action_ID",
            "Incident_ID",
            "Incident_Date",
            "Action_Date",
            "Due_Date",
            "Closure_Date",
            "Action_Status",
            "Days_Open"
        ]
    ].head(20)
)


# 3. Action before incident
action_before_incident = fact_hse_corrective_action[
    fact_hse_corrective_action["Action_Date"]
    < fact_hse_corrective_action["Incident_Date"]
]

print("\nAction Dates Before Incident Dates:")
print("Count:", len(action_before_incident))

display(
    action_before_incident[
        [
            "Corrective_Action_ID",
            "Incident_ID",
            "Incident_Date",
            "Action_Date",
            "Due_Date",
            "Closure_Date",
            "Action_Status",
            "Days_Open"
        ]
    ].head(20)
)

========== STEP 9 TIMELINE SPOT CHECK ==========

Action Dates After July 31, 2026:
Count: 0

Empty DataFrame
Columns: [Corrective_Action_ID, Incident_ID, Incident_Date, Action_Date, Due_Date, Closure_Date, Action_Status, Days_Open]
Index: []

Closure Dates Before Action Dates:
Count: 0

Empty DataFrame
Columns: [Corrective_Action_ID, Incident_ID, Incident_Date, Action_Date, Due_Date, Closure_Date, Action_Status, Days_Open]
Index: []

Action Dates Before Incident Dates:
Count: 0

Empty DataFrame
Columns: [Corrective_Action_ID, Incident_ID, Incident_Date, Action_Date, Due_Date, Closure_Date, Action_Status, Days_Open]
Index: []

In [326]:
# ============================================================
# STEP 10 — FINAL RELATIONSHIP / REFERENTIAL INTEGRITY CHECK
# ============================================================

print("============================================================")
print(" STEP 10 — FINAL RELATIONSHIP CHECK")
print("============================================================")

# ------------------------------------------------------------
# 1. Incident_ID
# ------------------------------------------------------------

invalid_incidents = (
    ~fact_hse_corrective_action["Incident_ID"]
    .isin(fact_hse_incident["Incident_ID"])
).sum()

print("\nInvalid Incident IDs:", invalid_incidents)


# ------------------------------------------------------------
# 2. Employee_ID
# ------------------------------------------------------------

invalid_employees = (
    ~fact_hse_corrective_action["Employee_ID"]
    .isin(dim_employee["Employee_ID"])
).sum()

print("Invalid Employee IDs:", invalid_employees)


# ------------------------------------------------------------
# 3. BusinessUnit_ID
# ------------------------------------------------------------

invalid_business_units = (
    ~fact_hse_corrective_action["BusinessUnit_ID"]
    .isin(dim_business_unit["BusinessUnit_ID"])
).sum()

print("Invalid BusinessUnit IDs:", invalid_business_units)


# ------------------------------------------------------------
# 4. Department_ID
# ------------------------------------------------------------

invalid_departments = (
    ~fact_hse_corrective_action["Department_ID"]
    .isin(dim_department["Department_ID"])
).sum()

print("Invalid Department IDs:", invalid_departments)


# ------------------------------------------------------------
# 5. Asset_ID
# ------------------------------------------------------------

invalid_assets = (
    ~fact_hse_corrective_action["Asset_ID"]
    .isin(dim_asset["Asset_ID"])
).sum()

print("Invalid Asset IDs:", invalid_assets)


# ------------------------------------------------------------
# 6. Corrective Action Type
# ------------------------------------------------------------

invalid_action_types = (
    ~fact_hse_corrective_action["Corrective_Action_Type_ID"]
    .isin(dim_corrective_action["Corrective_Action_Type_ID"])
).sum()

print("Invalid Corrective Action Type IDs:", invalid_action_types)


# ------------------------------------------------------------
# 7. Duplicate IDs on the dimension side
# ------------------------------------------------------------

print("\n========== DIMENSION KEY CHECK ==========")

print(
    "Duplicate Employee IDs:",
    dim_employee["Employee_ID"].duplicated().sum()
)

print(
    "Duplicate BusinessUnit IDs:",
    dim_business_unit["BusinessUnit_ID"].duplicated().sum()
)

print(
    "Duplicate Department IDs:",
    dim_department["Department_ID"].duplicated().sum()
)

print(
    "Duplicate Asset IDs:",
    dim_asset["Asset_ID"].duplicated().sum()
)

print(
    "Duplicate Corrective Action Type IDs:",
    dim_corrective_action[
        "Corrective_Action_Type_ID"
    ].duplicated().sum()
)


# ------------------------------------------------------------
# FINAL RESULT
# ------------------------------------------------------------

total_invalid = (
    invalid_incidents
    + invalid_employees
    + invalid_business_units
    + invalid_departments
    + invalid_assets
    + invalid_action_types
)

print("\n============================================================")
print(" TOTAL INVALID RELATIONSHIPS:", total_invalid)
print("============================================================")

============================================================
 STEP 10 — FINAL RELATIONSHIP CHECK
============================================================

Invalid Incident IDs: 0
Invalid Employee IDs: 0
Invalid BusinessUnit IDs: 0
Invalid Department IDs: 0
Invalid Asset IDs: 0
Invalid Corrective Action Type IDs: 0

========== DIMENSION KEY CHECK ==========
Duplicate Employee IDs: 0
Duplicate BusinessUnit IDs: 0
Duplicate Department IDs: 0
Duplicate Asset IDs: 0
Duplicate Corrective Action Type IDs: 0

============================================================
 TOTAL INVALID RELATIONSHIPS: 0
============================================================

In [327]:
# ============================================================
# STEP 11A — CHECK DIM_CORRECTIVE_ACTION
# ============================================================

print("========== DIM_CORRECTIVE_ACTION CHECK ==========")

print("Rows:", len(dim_corrective_action))
print("Columns:", len(dim_corrective_action.columns))

print("\nColumns:")
print(dim_corrective_action.columns.tolist())

print("\nDuplicate IDs:",
      dim_corrective_action["Corrective_Action_Type_ID"].duplicated().sum())

print("\nMissing Values:")
print(dim_corrective_action.isna().sum())

display(dim_corrective_action)

========== DIM_CORRECTIVE_ACTION CHECK ==========
Rows: 8
Columns: 2

Columns:
['Corrective_Action_Type_ID', 'Corrective_Action_Type']

Duplicate IDs: 0

Missing Values:
Corrective_Action_Type_ID    0
Corrective_Action_Type       0
dtype: int64

  Corrective_Action_Type_ID        Corrective_Action_Type
0                     CA001           Engineering Control
1                     CA002        Administrative Control
2                     CA003  Procedure / Process Revision
3                     CA004         Training / Competency
4                     CA005               PPE Improvement
5                     CA006          Maintenance / Repair
6                     CA007       Inspection / Monitoring
7                     CA008        Emergency Preparedness

In [328]:
# ============================================================
# STEP 11B — SAVE BOTH VALIDATED TABLES
# ============================================================

dim_corrective_action.to_csv(
    "Dim_CorrectiveAction.csv",
    index=False
)

fact_hse_corrective_action.to_csv(
    "Fact_HSE_CorrectiveAction.csv",
    index=False
)

print("========== FILES SAVED ==========")
print("Dim_CorrectiveAction.csv ✅")
print("Fact_HSE_CorrectiveAction.csv ✅")

========== FILES SAVED ==========
Dim_CorrectiveAction.csv ✅
Fact_HSE_CorrectiveAction.csv ✅

In [329]:
import os
import zipfile

# ============================================================
# KEYSTRA SOLUTION 3 — FINAL DATA PACKAGE
# ============================================================

final_folder = "Keystra_Solution_3_Final_Data"
os.makedirs(final_folder, exist_ok=True)

# ALL FINAL TABLES
tables = {

    # =========================
    # FACT TABLES
    # =========================
    "Fact_HSE_Incident.csv": fact_hse_incident,
    "Fact_HSE_Exposure.csv": fact_hse_exposure,
    "Fact_HSE_CorrectiveAction.csv": fact_hse_corrective_action,

    # =========================
    # DIMENSION TABLES
    # =========================
    "Dim_Date.csv": dim_date,
    "Dim_Employee.csv": dim_employee,
    "Dim_BusinessUnit.csv": dim_business_unit,
    "Dim_Department.csv": dim_department,
    "Dim_Asset.csv": dim_asset,
    "Dim_JobRole.csv": dim_job_role,
    "Dim_IncidentType.csv": dim_incident_type,
    "Dim_Hazard.csv": dim_hazard,
    "Dim_Shift.csv": dim_shift,
    "Dim_Contractor.csv": dim_contractor,
    "Dim_Location.csv": dim_location,
    "Dim_CorrectiveAction.csv": dim_corrective_action
}


# ============================================================
# SAVE EVERY TABLE
# ============================================================

for filename, df in tables.items():

    df.to_csv(
        os.path.join(final_folder, filename),
        index=False
    )


# ============================================================
# CREATE ZIP
# ============================================================

zip_filename = "Keystra_Solution_3_Final_Data.zip"

with zipfile.ZipFile(
    zip_filename,
    "w",
    zipfile.ZIP_DEFLATED
) as zipf:

    for filename in tables:

        filepath = os.path.join(
            final_folder,
            filename
        )

        zipf.write(
            filepath,
            arcname=filename
        )


# ============================================================
# FINAL PACKAGE CHECK
# ============================================================

print("==============================================")
print("✅ KEYSTRA SOLUTION 3 — FINAL DATA PACKAGE")
print("==============================================")

for filename, df in tables.items():

    print(
        f"{filename}: "
        f"{df.shape[0]} rows × "
        f"{df.shape[1]} columns"
    )

print()
print("Total tables:", len(tables))
print()
print(f"✅ ZIP created: {zip_filename}")

==============================================
✅ KEYSTRA SOLUTION 3 — FINAL DATA PACKAGE
==============================================
Fact_HSE_Incident.csv: 6370 rows × 27 columns
Fact_HSE_Exposure.csv: 220000 rows × 13 columns
Fact_HSE_CorrectiveAction.csv: 3060 rows × 24 columns
Dim_Date.csv: 1673 rows × 11 columns
Dim_Employee.csv: 4000 rows × 24 columns
Dim_BusinessUnit.csv: 5 rows × 2 columns
Dim_Department.csv: 7 rows × 2 columns
Dim_Asset.csv: 13 rows × 3 columns
Dim_JobRole.csv: 35 rows × 3 columns
Dim_IncidentType.csv: 10 rows × 3 columns
Dim_Hazard.csv: 12 rows × 3 columns
Dim_Shift.csv: 3 rows × 2 columns
Dim_Contractor.csv: 8 rows × 4 columns
Dim_Location.csv: 8 rows × 5 columns
Dim_CorrectiveAction.csv: 8 rows × 2 columns

Total tables: 15

✅ ZIP created: Keystra_Solution_3_Final_Data.zip

In [330]:
from google.colab import files

files.download("Keystra_Solution_3_Final_Data.zip")

In [331]:
print(
    fact_hse_incident[
        ["Incident_ID", "Incident_Month", "Department_ID", "Asset_ID"]
    ].head(20)
)

print("\n--- LAST 20 ROWS ---")

print(
    fact_hse_incident[
        ["Incident_ID", "Incident_Month", "Department_ID", "Asset_ID"]
    ].tail(20)
)

   Incident_ID Incident_Month Department_ID Asset_ID
0    INC000001     2023-09-01        DEP002   AST008
1    INC000002     2026-05-01        DEP001   AST010
2    INC000003     2025-05-01        DEP001   AST002
3    INC000004     2024-09-01        DEP003   AST002
4    INC000005     2022-09-01        DEP001   AST009
5    INC000006     2022-09-01        DEP001   AST009
6    INC000007     2022-04-01        DEP001   AST002
7    INC000008     2025-12-01        DEP001   AST003
8    INC000009     2024-10-01        DEP001   AST007
9    INC000010     2025-03-01        DEP001   AST008
10   INC000011     2022-02-01        DEP001   AST009
11   INC000012     2026-06-01        DEP001   AST005
12   INC000013     2025-10-01        DEP001   AST008
13   INC000014     2022-12-01        DEP004   AST002
14   INC000015     2022-11-01        DEP001   AST008
15   INC000016     2022-11-01        DEP001   AST010
16   INC000017     2023-05-01        DEP001   AST002
17   INC000018     2024-05-01        DEP001   AST009
18   INC000019     2023-12-01        DEP002   AST008
19   INC000020     2023-05-01        DEP001   AST003

--- LAST 20 ROWS ---
     Incident_ID Incident_Month Department_ID Asset_ID
6350   INC006351     2022-01-01        DEP003   AST004
6351   INC006352     2024-05-01        DEP001   AST001
6352   INC006353     2022-03-01        DEP007   AST005
6353   INC006354     2024-08-01        DEP005   AST010
6354   INC006355     2026-03-01        DEP003   AST001
6355   INC006356     2026-06-01        DEP001   AST009
6356   INC006357     2024-06-01        DEP001   AST003
6357   INC006358     2024-02-01        DEP002   AST003
6358   INC006359     2026-04-01        DEP001   AST003
6359   INC006360     2025-02-01        DEP002   AST002
6360   INC006361     2022-04-01        DEP001   AST005
6361   INC006362     2024-02-01        DEP004   AST010
6362   INC006363     2023-02-01        DEP001   AST001
6363   INC006364     2024-02-01        DEP001   AST003
6364   INC006365     2024-02-01        DEP004   AST003
6365   INC006366     2024-09-01        DEP001   AST008
6366   INC006367     2023-08-01        DEP001   AST001
6367   INC006368     2022-10-01        DEP004   AST001
6368   INC006369     2024-04-01        DEP001   AST009
6369   INC006370     2025-10-01        DEP003   AST010

In [332]:
print(
    fact_hse_incident["Incident_Month"]
    .dt.year
    .value_counts()
    .sort_index()
)

Incident_Month
2022    1421
2023    1400
2024    1378
2025    1378
2026     793
Name: count, dtype: int64

In [333]:
print(
    fact_hse_incident[
        ["Incident_ID", "Incident_Month"]
    ].head(100)
)

   Incident_ID Incident_Month
0    INC000001     2023-09-01
1    INC000002     2026-05-01
2    INC000003     2025-05-01
3    INC000004     2024-09-01
4    INC000005     2022-09-01
..         ...            ...
95   INC000096     2024-04-01
96   INC000097     2024-05-01
97   INC000098     2023-12-01
98   INC000099     2022-02-01
99   INC000100     2022-06-01

[100 rows x 2 columns]

In [334]:
# ============================================================
# CHECK — INCIDENT TYPE WEIGHTS
# ============================================================

print("BASE WEIGHTS:")
print(incident_type_weights)
print("BASE TOTAL:", sum(incident_type_weights.values()))

print("\nDEP001 + AST001:")
print(get_incident_type_weights("DEP001", "AST001"))

print("\nDEP003 + AST001:")
print(get_incident_type_weights("DEP003", "AST001"))

print("\nDEP001 + AST008:")
print(get_incident_type_weights("DEP001", "AST008"))

BASE WEIGHTS:
{'IT001': 0.5, 'IT002': 0.16, 'IT003': 0.1, 'IT004': 0.06, 'IT005': 0.035, 'IT006': 0.002, 'IT007': 0.06, 'IT008': 0.025, 'IT009': 0.025, 'IT010': 0.033}
BASE TOTAL: 1.0

DEP001 + AST001:
{'IT001': 0.49763299782772374, 'IT002': 0.13847179069988835, 'IT003': 0.08654486918743023, 'IT004': 0.05192692151245813, 'IT005': 0.03029070421560058, 'IT006': 0.0017308973837486044, 'IT007': 0.05192692151245813, 'IT008': 0.025963460756229066, 'IT009': 0.048681488917929505, 'IT010': 0.06682994798653363}

DEP003 + AST001:
{'IT001': 0.4345370008256203, 'IT002': 0.17381480033024813, 'IT003': 0.11297962021466129, 'IT004': 0.06257332811888933, 'IT005': 0.034980228566462435, 'IT006': 0.0017381480033024812, 'IT007': 0.06257332811888933, 'IT008': 0.026072220049537218, 'IT009': 0.039108330074305836, 'IT010': 0.05162299569808369}

DEP001 + AST008:
{'IT001': 0.49763299782772374, 'IT002': 0.13847179069988835, 'IT003': 0.08654486918743023, 'IT004': 0.05192692151245813, 'IT005': 0.03029070421560058, 'IT006': 0.0017308973837486044, 'IT007': 0.05192692151245813, 'IT008': 0.025963460756229066, 'IT009': 0.048681488917929505, 'IT010': 0.06682994798653363}

In [335]:
# ============================================================
# CHECK — RANDOM INCIDENT TYPE GENERATION
# ============================================================

np.random.seed(42)

test_types = []

for _ in range(10000):
    profile = get_incident_type_weights("DEP001", "AST001")

    test_types.append(
        np.random.choice(
            list(profile.keys()),
            p=list(profile.values())
        )
    )

print(
    pd.Series(test_types)
    .value_counts(normalize=True)
    .sort_index()
)

IT001    0.5055
IT002    0.1405
IT003    0.0871
IT004    0.0485
IT005    0.0284
IT006    0.0025
IT007    0.0503
IT008    0.0264
IT009    0.0445
IT010    0.0663
Name: proportion, dtype: float64

In [336]:
print("========== INCIDENT TYPE DISTRIBUTION ==========")

print(
    fact_hse_incident["Incident_Type_ID"]
    .value_counts()
    .sort_index()
)

print("\nPercent Distribution:")

print(
    (
        fact_hse_incident["Incident_Type_ID"]
        .value_counts(normalize=True)
        .sort_index()
        * 100
    ).round(2)
)

print("\n========== CONSEQUENCE FLAGS ==========")

print(
    "Total Events:",
    len(fact_hse_incident)
)

print(
    "Recordable Incidents:",
    fact_hse_incident["Recordable_Flag"].sum()
)

print(
    "LTIs:",
    fact_hse_incident["LTI_Flag"].sum()
)

print(
    "Fatalities:",
    fact_hse_incident["Fatality_Flag"].sum()
)

print(
    "Near Misses:",
    fact_hse_incident["Near_Miss_Flag"].sum()
)

========== INCIDENT TYPE DISTRIBUTION ==========
Incident_Type_ID
IT001    3144
IT002     948
IT003     602
IT004     392
IT005     175
IT006      14
IT007     320
IT008     166
IT009     265
IT010     344
Name: count, dtype: int64

Percent Distribution:
Incident_Type_ID
IT001    49.36
IT002    14.88
IT003     9.45
IT004     6.15
IT005     2.75
IT006     0.22
IT007     5.02
IT008     2.61
IT009     4.16
IT010     5.40
Name: proportion, dtype: float64

========== CONSEQUENCE FLAGS ==========
Total Events: 6370
Recordable Incidents: 1183
LTIs: 175
Fatalities: 14
Near Misses: 3144

In [337]:
print(dim_incident_type)

  Incident_Type_ID           Incident_Type Incident_Category
0            IT001               Near Miss         Near Miss
1            IT002          First Aid Case  Injury / Illness
2            IT003  Medical Treatment Case  Injury / Illness
3            IT004    Restricted Work Case  Injury / Illness
4            IT005        Lost Time Injury  Injury / Illness
5            IT006                Fatality          Fatality
6            IT007         Property Damage  Property / Asset
7            IT008  Environmental Incident     Environmental
8            IT009        Fire / Explosion    Process / Fire
9            IT010    Process Safety Event    Process Safety

In [348]:
# ============================================================
# STEP 19 — REVISED INCIDENT TYPE PROFILE
# REALISTIC HSE SEVERITY DISTRIBUTION
# ============================================================

incident_type_weights = {
    "IT001": 0.58,   # Near Miss
    "IT002": 0.18,   # First Aid Case
    "IT003": 0.07,   # Medical Treatment Case
    "IT004": 0.035,  # Restricted Work Case
    "IT005": 0.015,  # Lost Time Injury
    "IT006": 0.001,  # Fatality
    "IT007": 0.055,  # Property Damage
    "IT008": 0.020,  # Environmental Incident
    "IT009": 0.018,  # Fire / Explosion
    "IT010": 0.026,  # Process Safety Event
}

print("Total Weight:", sum(incident_type_weights.values()))

Total Weight: 1.0

In [349]:
# ============================================================
# STEP 19B — HSE INCIDENT TYPE PROFILE BY RISK CONTEXT
# ============================================================

def get_incident_type_weights(department_id, asset_id):

    weights = incident_type_weights.copy()

    # --------------------------------------------------------
    # HIGH-HAZARD OPERATING ASSETS
    # Offshore, gas, refinery, LNG
    # --------------------------------------------------------

    high_hazard_assets = [
        "AST001", "AST002", "AST003",
        "AST006", "AST007",
        "AST008",
        "AST010"
    ]

    if asset_id in high_hazard_assets:
        weights["IT009"] *= 1.40   # Fire / Explosion
        weights["IT010"] *= 1.40   # Process Safety
        weights["IT008"] *= 1.15   # Environmental

    # --------------------------------------------------------
    # MAINTENANCE
    # --------------------------------------------------------

    if department_id == "DEP003":
        weights["IT002"] *= 1.10   # First Aid
        weights["IT003"] *= 1.15   # Medical Treatment
        weights["IT004"] *= 1.10   # Restricted Work
        weights["IT005"] *= 1.05   # LTI
        weights["IT007"] *= 1.15   # Property Damage

    # --------------------------------------------------------
    # OPERATIONS
    # --------------------------------------------------------

    if department_id == "DEP001":
        weights["IT001"] *= 1.10   # Near Miss
        weights["IT009"] *= 1.15
        weights["IT010"] *= 1.20

    # --------------------------------------------------------
    # LOGISTICS
    # --------------------------------------------------------

    if department_id == "DEP005":
        weights["IT007"] *= 1.20
        weights["IT002"] *= 1.10

    # --------------------------------------------------------
    # OFFICE-BASED FUNCTIONS
    # --------------------------------------------------------

    if department_id in ["DEP006", "DEP007"]:
        weights["IT001"] *= 1.20
        weights["IT002"] *= 1.10
        weights["IT009"] *= 0.40
        weights["IT010"] *= 0.35
        weights["IT008"] *= 0.50

    # --------------------------------------------------------
    # NORMALIZE
    # --------------------------------------------------------

    total = sum(weights.values())

    weights = {
        k: v / total
        for k, v in weights.items()
    }

    return weights

In [350]:
# ============================================================
# STEP 21 — REASSIGN INCIDENT TYPE
# ============================================================

np.random.seed(42)

incident_type_ids = []

for _, row in fact_hse_incident.iterrows():

    profile = get_incident_type_weights(
        row["Department_ID"],
        row["Asset_ID"]
    )

    incident_type = np.random.choice(
        list(profile.keys()),
        p=list(profile.values())
    )

    incident_type_ids.append(incident_type)

fact_hse_incident["Incident_Type_ID"] = incident_type_ids

print("Missing Incident Types:",
      fact_hse_incident["Incident_Type_ID"].isna().sum())

print("\nOverall Incident Type Distribution:")
print(
    fact_hse_incident["Incident_Type_ID"]
    .value_counts()
    .sort_index()
)

Missing Incident Types: 0

Overall Incident Type Distribution:
Incident_Type_ID
IT001    3710
IT002    1118
IT003     413
IT004     212
IT005      75
IT006       2
IT007     342
IT008     120
IT009     162
IT010     216
Name: count, dtype: int64

In [351]:
# ============================================================
# INCIDENT TYPE DISTRIBUTION CHECK
# ============================================================

incident_distribution = (
    fact_hse_incident["Incident_Type_ID"]
    .value_counts()
    .sort_index()
)

incident_percent = (
    fact_hse_incident["Incident_Type_ID"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

print("========== INCIDENT TYPE DISTRIBUTION ==========")
print(incident_distribution)

print("\nPercent Distribution:")
print(incident_percent)

========== INCIDENT TYPE DISTRIBUTION ==========
Incident_Type_ID
IT001    3710
IT002    1118
IT003     413
IT004     212
IT005      75
IT006       2
IT007     342
IT008     120
IT009     162
IT010     216
Name: count, dtype: int64

Percent Distribution:
Incident_Type_ID
IT001    58.24
IT002    17.55
IT003     6.48
IT004     3.33
IT005     1.18
IT006     0.03
IT007     5.37
IT008     1.88
IT009     2.54
IT010     3.39
Name: proportion, dtype: float64

In [352]:
# ============================================================
# STEP 32 — HSE CONSEQUENCE FLAGS
# ============================================================

fact_hse_incident["Recordable_Flag"] = (
    fact_hse_incident["Incident_Type_ID"].isin([
        "IT003",
        "IT004",
        "IT005",
        "IT006"
    ])
).astype(int)

fact_hse_incident["LTI_Flag"] = (
    fact_hse_incident["Incident_Type_ID"] == "IT005"
).astype(int)

fact_hse_incident["Fatality_Flag"] = (
    fact_hse_incident["Incident_Type_ID"] == "IT006"
).astype(int)

fact_hse_incident["Near_Miss_Flag"] = (
    fact_hse_incident["Incident_Type_ID"] == "IT001"
).astype(int)

In [353]:
# ============================================================
# CONSEQUENCE CHECK
# ============================================================

print("========== CONSEQUENCE FLAGS ==========")

print(
    "Total Events:",
    len(fact_hse_incident)
)

print(
    "Recordable Incidents:",
    fact_hse_incident["Recordable_Flag"].sum()
)

print(
    "LTIs:",
    fact_hse_incident["LTI_Flag"].sum()
)

print(
    "Fatalities:",
    fact_hse_incident["Fatality_Flag"].sum()
)

print(
    "Near Misses:",
    fact_hse_incident["Near_Miss_Flag"].sum()
)

========== CONSEQUENCE FLAGS ==========
Total Events: 6370
Recordable Incidents: 702
LTIs: 75
Fatalities: 2
Near Misses: 3710

In [354]:
# ============================================================
# FINAL HSE INCIDENT INTEGRITY + TRIFR CHECK
# ============================================================

print("========== FINAL HSE INCIDENT CHECK ==========")

print("Total Incidents:", len(fact_hse_incident))

print("\nIncident Type Distribution:")
print(
    fact_hse_incident["Incident_Type_ID"]
    .value_counts()
    .sort_index()
)

print("\nIncident Type Percentage:")
print(
    (
        fact_hse_incident["Incident_Type_ID"]
        .value_counts(normalize=True)
        .sort_index()
        .mul(100)
        .round(2)
    )
)

print("\n========== CONSEQUENCE SUMMARY ==========")

print("Total Events:",
      len(fact_hse_incident))

print("Recordable Incidents:",
      fact_hse_incident["Recordable_Flag"].sum())

print("LTIs:",
      fact_hse_incident["LTI_Flag"].sum())

print("Fatalities:",
      fact_hse_incident["Fatality_Flag"].sum())

print("Near Misses:",
      fact_hse_incident["Near_Miss_Flag"].sum())

========== FINAL HSE INCIDENT CHECK ==========
Total Incidents: 6370

Incident Type Distribution:
Incident_Type_ID
IT001    3710
IT002    1118
IT003     413
IT004     212
IT005      75
IT006       2
IT007     342
IT008     120
IT009     162
IT010     216
Name: count, dtype: int64

Incident Type Percentage:
Incident_Type_ID
IT001    58.24
IT002    17.55
IT003     6.48
IT004     3.33
IT005     1.18
IT006     0.03
IT007     5.37
IT008     1.88
IT009     2.54
IT010     3.39
Name: proportion, dtype: float64

========== CONSEQUENCE SUMMARY ==========
Total Events: 6370
Recordable Incidents: 702
LTIs: 75
Fatalities: 2
Near Misses: 3710

In [355]:
# ============================================================
# FINAL TRIFR CHECK
# ============================================================

total_exposure_hours = fact_hse_exposure["Exposure_Hours"].sum()

recordable_incidents = fact_hse_incident["Recordable_Flag"].sum()

lti_count = fact_hse_incident["LTI_Flag"].sum()

fatality_count = fact_hse_incident["Fatality_Flag"].sum()

trifr = (
    recordable_incidents
    / total_exposure_hours
) * 200_000

ltifr = (
    lti_count
    / total_exposure_hours
) * 200_000

print("\n========== FINAL HSE RATES ==========")

print("Total Exposure Hours:",
      round(total_exposure_hours, 2))

print("Recordable Incidents:",
      recordable_incidents)

print("LTIs:",
      lti_count)

print("Fatalities:",
      fatality_count)

print("TRIFR:",
      round(trifr, 2))

print("LTIFR:",
      round(ltifr, 2))

========== FINAL HSE RATES ==========
Total Exposure Hours: 36371332.71
Recordable Incidents: 702
LTIs: 75
Fatalities: 2
TRIFR: 3.86
LTIFR: 0.41

In [360]:
recordable_percentage = (
    recordable_incidents
    / len(fact_hse_incident)
) * 100

print("Recordable Event Percentage:",
      round(recordable_percentage, 2), "%")

Recordable Event Percentage: 11.02 %

In [368]:
print("========== FINAL CONSEQUENCE VALIDATION ==========")

print("Total Incidents:",
      len(fact_hse_incident))

print("\nIncident Type Distribution:")
print(
    fact_hse_incident["Incident_Type_ID"]
    .value_counts()
    .sort_index()
)

print("\nExpected Recordable Incidents:")

expected_recordables = (
    (fact_hse_incident["Incident_Type_ID"] == "IT003").sum()
    + (fact_hse_incident["Incident_Type_ID"] == "IT004").sum()
    + (fact_hse_incident["Incident_Type_ID"] == "IT005").sum()
    + (fact_hse_incident["Incident_Type_ID"] == "IT006").sum()
)

print(expected_recordables)

print("\nActual Recordable Incidents:",
      fact_hse_incident["Recordable_Flag"].sum())

print("Actual LTIs:",
      fact_hse_incident["LTI_Flag"].sum())

print("Actual Fatalities:",
      fact_hse_incident["Fatality_Flag"].sum())

print("Actual Near Misses:",
      fact_hse_incident["Near_Miss_Flag"].sum())

========== FINAL CONSEQUENCE VALIDATION ==========
Total Incidents: 6370

Incident Type Distribution:
Incident_Type_ID
IT001    3710
IT002    1118
IT003     413
IT004     212
IT005      75
IT006       2
IT007     342
IT008     120
IT009     162
IT010     216
Name: count, dtype: int64

Expected Recordable Incidents:
702

Actual Recordable Incidents: 702
Actual LTIs: 75
Actual Fatalities: 2
Actual Near Misses: 3710

In [369]:
# ============================================================
# VERIFY ALL TABLES EXIST BEFORE FINAL SAVE
# ============================================================

print("========== FINAL TABLE EXISTENCE CHECK ==========")

for filename, df in tables.items():
    print(
        f"✅ {filename} — "
        f"{len(df):,} rows × {len(df.columns)} columns"
    )

print("\nTotal tables:", len(tables))

========== FINAL TABLE EXISTENCE CHECK ==========
✅ Fact_HSE_Incident.csv — 6,370 rows × 27 columns
✅ Fact_HSE_Exposure.csv — 220,000 rows × 13 columns
✅ Fact_HSE_CorrectiveAction.csv — 3,060 rows × 24 columns
✅ Dim_Date.csv — 1,673 rows × 11 columns
✅ Dim_Employee.csv — 4,000 rows × 24 columns
✅ Dim_BusinessUnit.csv — 5 rows × 2 columns
✅ Dim_Department.csv — 7 rows × 2 columns
✅ Dim_Asset.csv — 13 rows × 3 columns
✅ Dim_JobRole.csv — 35 rows × 3 columns
✅ Dim_IncidentType.csv — 10 rows × 3 columns
✅ Dim_Hazard.csv — 12 rows × 3 columns
✅ Dim_Shift.csv — 3 rows × 2 columns
✅ Dim_Contractor.csv — 8 rows × 4 columns
✅ Dim_Location.csv — 8 rows × 5 columns
✅ Dim_CorrectiveAction.csv — 8 rows × 2 columns

Total tables: 15

In [370]:
import os
import zipfile

# ============================================================
# KEYSTRA SOLUTION 3 — FINAL DATA PACKAGE
# ============================================================

final_folder = "Keystra_Solution_3_Final_Data"
os.makedirs(final_folder, exist_ok=True)

# ALL FINAL TABLES
tables = {

    # =========================
    # FACT TABLES
    # =========================
    "Fact_HSE_Incident.csv": fact_hse_incident,
    "Fact_HSE_Exposure.csv": fact_hse_exposure,
    "Fact_HSE_CorrectiveAction.csv": fact_hse_corrective_action,

    # =========================
    # DIMENSION TABLES
    # =========================
    "Dim_Date.csv": dim_date,
    "Dim_Employee.csv": dim_employee,
    "Dim_BusinessUnit.csv": dim_business_unit,
    "Dim_Department.csv": dim_department,
    "Dim_Asset.csv": dim_asset,
    "Dim_JobRole.csv": dim_job_role,
    "Dim_IncidentType.csv": dim_incident_type,
    "Dim_Hazard.csv": dim_hazard,
    "Dim_Shift.csv": dim_shift,
    "Dim_Contractor.csv": dim_contractor,
    "Dim_Location.csv": dim_location,
    "Dim_CorrectiveAction.csv": dim_corrective_action
}

# ============================================================
# SAVE EVERY TABLE
# ============================================================

for filename, df in tables.items():

    df.to_csv(
        os.path.join(final_folder, filename),
        index=False
    )

# ============================================================
# CREATE ZIP
# ============================================================

zip_filename = "Keystra_Solution_3_Final_Data.zip"

with zipfile.ZipFile(
    zip_filename,
    "w",
    zipfile.ZIP_DEFLATED
) as zipf:

    for filename in tables:

        filepath = os.path.join(
            final_folder,
            filename
        )

        zipf.write(
            filepath,
            arcname=filename
        )

# ============================================================
# FINAL PACKAGE CHECK
# ============================================================

print("==============================================")
print("✅ KEYSTRA SOLUTION 3 — FINAL DATA PACKAGE")
print("==============================================")

for filename, df in tables.items():

    print(
        f"{filename}: "
        f"{df.shape[0]} rows × "
        f"{df.shape[1]} columns"
    )

print()
print("Total tables:", len(tables))
print()
print(f"✅ ZIP created: {zip_filename}")

==============================================
✅ KEYSTRA SOLUTION 3 — FINAL DATA PACKAGE
==============================================
Fact_HSE_Incident.csv: 6370 rows × 27 columns
Fact_HSE_Exposure.csv: 220000 rows × 13 columns
Fact_HSE_CorrectiveAction.csv: 3060 rows × 24 columns
Dim_Date.csv: 1673 rows × 11 columns
Dim_Employee.csv: 4000 rows × 24 columns
Dim_BusinessUnit.csv: 5 rows × 2 columns
Dim_Department.csv: 7 rows × 2 columns
Dim_Asset.csv: 13 rows × 3 columns
Dim_JobRole.csv: 35 rows × 3 columns
Dim_IncidentType.csv: 10 rows × 3 columns
Dim_Hazard.csv: 12 rows × 3 columns
Dim_Shift.csv: 3 rows × 2 columns
Dim_Contractor.csv: 8 rows × 4 columns
Dim_Location.csv: 8 rows × 5 columns
Dim_CorrectiveAction.csv: 8 rows × 2 columns

Total tables: 15

✅ ZIP created: Keystra_Solution_3_Final_Data.zip

In [372]:
from google.colab import files

files.download("Keystra_Solution_3_Final_Data.zip")